//! TypeScript backend orchestration for typed Radix HIR.
//!
//! This module is the target boundary between Radix's checked, compiler-facing
//! HIR and generated TypeScript text. It owns target-wide name resolution,
//! item dispatch, and entry-block wrapping; declaration, statement, expression,
//! and type details stay in sibling modules so target policy remains easy to
//! audit by surface area.
//!
//! CODEGEN CONTRACT
//! ================
//! The TypeScript backend assumes parsing, name resolution, lowering, and
//! semantic typechecking have already accepted the program. It may choose a
//! TypeScript representation that is looser than Faber's source semantics, but
//! it should not rely on TypeScript to catch language rules that Radix has
//! already proven or rejected earlier in the pipeline.
//!
//! TARGET POLICY
//! =============
//! Generated output is intentionally plain TypeScript: stable names, direct
//! declarations, lightweight IIFEs for top-level entry code, and no formatter
//! dependency. This keeps backend behavior deterministic for compiler tests and
//! leaves idiomatic cleanup to downstream tooling when users want it.

mod decl;
mod expr;
mod stmt;
mod types;

use super::{names::NameCatalog, CodeWriter, Codegen, CodegenError};
use crate::hir::{DefId, HirItem, HirItemKind, HirProgram};
use crate::lexer::{Interner, Symbol};
use crate::semantic::TypeTable;
use crate::TypeScriptOutput;
use std::cell::Cell;

pub struct TsCodegen<'a> {
    names: NameCatalog<'a>,
    current_self_def: Cell<Option<DefId>>,
}

impl<'a> TsCodegen<'a> {
    /// Builds the target name catalog used by every TypeScript emission pass.
    ///
    /// The catalog is constructed from HIR rather than lazily during printing so
    /// declaration, expression, and type emission all share the same spelling
    /// decisions. That keeps cross-file helpers from inventing target names
    /// independently.
    pub fn new(hir: &HirProgram, interner: &'a Interner) -> Self {
        Self { names: NameCatalog::new(hir, interner), current_self_def: Cell::new(None) }
    }

    /// Resolves a source symbol into the spelling selected for TypeScript text.
    pub(super) fn resolve_symbol(&self, sym: Symbol) -> &str {
        self.names.resolve_symbol(sym)
    }

    /// Resolves a semantic definition id into its target declaration name.
    pub(super) fn resolve_def(&self, def_id: DefId) -> &str {
        self.names.resolve_def(def_id)
    }

    pub(super) fn resolve_expr_def(&self, def_id: DefId) -> &str {
        if self.current_self_def.get() == Some(def_id) {
            return "this";
        }
        self.resolve_def(def_id)
    }

    pub(super) fn replace_current_self_def(&self, def_id: Option<DefId>) -> Option<DefId> {
        let previous = self.current_self_def.get();
        self.current_self_def.set(def_id);
        previous
    }

    /// Dispatches one top-level HIR item to the declaration emitter.
    ///
    /// Item-specific formatting lives in `decl` so this module can remain the
    /// backend's phase coordinator instead of accumulating every TypeScript
    /// surface form in one file.
    fn generate_item(&self, item: &HirItem, types: &TypeTable, w: &mut CodeWriter) -> Result<(), CodegenError> {
        match &item.kind {
            HirItemKind::Function(func) => decl::generate_function(self, func, types, w)?,
            HirItemKind::Struct(strukt) => decl::generate_class(self, item.def_id, strukt, types, w)?,
            HirItemKind::Enum(enum_item) => decl::generate_enum(self, enum_item, types, w)?,
            HirItemKind::Interface(interface) => decl::generate_interface(self, interface, types, w)?,
            HirItemKind::TypeAlias(alias) => decl::generate_type_alias(self, alias, types, w)?,
            HirItemKind::Const(constant) => decl::generate_const(self, constant, types, w)?,
            HirItemKind::Import(import) => decl::generate_import(self, import, w)?,
        }
        Ok(())
    }
}

impl Codegen for TsCodegen<'_> {
    type Output = TypeScriptOutput;

    /// Emits a complete TypeScript compilation unit from checked HIR.
    ///
    /// Top-level declarations are emitted first, followed by the optional entry
    /// block. Entry code is wrapped in an IIFE so Faber's package entry can
    /// contain statements without becoming ambient TypeScript; the wrapper is
    /// marked `async` only when the lowered block actually contains `await`.
    fn generate(
        &self,
        hir: &HirProgram,
        types: &TypeTable,
        _interner: &Interner,
    ) -> Result<TypeScriptOutput, CodegenError> {
        let mut w = CodeWriter::new();
        w.writeln("// Generated by radix - do not edit");
        w.newline();

        for item in &hir.items {
            self.generate_item(item, types, &mut w)?;
            w.newline();
        }

        if let Some(entry) = &hir.entry {
            let entry_is_async = expr::contains_await_in_block(entry);
            if entry_is_async {
                w.writeln("(async () => {");
            } else {
                w.writeln("(() => {");
            }
            let mut block_result = Ok(());
            w.indented(|w| {
                block_result = stmt::generate_block(self, entry, types, w);
            });
            block_result?;
            w.writeln("})();");
        }

        Ok(TypeScriptOutput { code: w.finish() })
    }
}

#[cfg(test)]
#[path = "mod_test.rs"]
mod tests;
