mod decl;
mod expr;
mod stmt;
mod types;

use super::{names::NameCatalog, CodeWriter, Codegen, CodegenError};
use crate::hir::{DefId, HirItem, HirItemKind, HirProgram};
use crate::lexer::{Interner, Symbol};
use crate::semantic::TypeTable;
use crate::TypeScriptOutput;

pub struct TsCodegen<'a> {
    names: NameCatalog<'a>,
}

impl<'a> TsCodegen<'a> {
    pub fn new(hir: &HirProgram, interner: &'a Interner) -> Self {
        Self { names: NameCatalog::new(hir, interner) }
    }

    pub(super) fn resolve_symbol(&self, sym: Symbol) -> &str {
        self.names.resolve_symbol(sym)
    }

    pub(super) fn resolve_def(&self, def_id: DefId) -> &str {
        self.names.resolve_def(def_id)
    }

    fn generate_item(&self, item: &HirItem, types: &TypeTable, w: &mut CodeWriter) -> Result<(), CodegenError> {
        match &item.kind {
            HirItemKind::Function(func) => decl::generate_function(self, func, types, w)?,
            HirItemKind::Struct(strukt) => decl::generate_class(self, strukt, types, w)?,
            HirItemKind::Enum(enum_item) => decl::generate_enum(self, enum_item, types, w)?,
            HirItemKind::Interface(interface) => decl::generate_interface(self, interface, types, w)?,
            HirItemKind::TypeAlias(alias) => decl::generate_type_alias(self, alias, types, w)?,
            HirItemKind::Const(constant) => decl::generate_const(self, constant, types, w)?,
            HirItemKind::Import(import) => decl::generate_import(self, import, w)?,
        }
        Ok(())
    }
}

impl Codegen for TsCodegen<'_> {
    type Output = TypeScriptOutput;

    fn generate(
        &self,
        hir: &HirProgram,
        types: &TypeTable,
        _interner: &Interner,
    ) -> Result<TypeScriptOutput, CodegenError> {
        let mut w = CodeWriter::new();
        w.writeln("// Generated by radix - do not edit");
        w.newline();

        for item in &hir.items {
            self.generate_item(item, types, &mut w)?;
            w.newline();
        }

        if let Some(entry) = &hir.entry {
            let entry_is_async = expr::contains_await_in_block(entry);
            if entry_is_async {
                w.writeln("(async () => {");
            } else {
                w.writeln("(() => {");
            }
            let mut block_result = Ok(());
            w.indented(|w| {
                block_result = stmt::generate_block(self, entry, types, w);
            });
            block_result?;
            w.writeln("})();");
        }

        Ok(TypeScriptOutput { code: w.finish() })
    }
}

#[cfg(test)]
#[path = "mod_test.rs"]
mod tests;
