/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: bun run build:norma
 * Source: fons/norma/*.fab
 * Generated: 2026-01-06T15:38:43.449Z
 */

import type { NormaCollection } from './norma-registry';

export const registry: Map<string, NormaCollection> = new Map([
    ['lista', {
        name: 'lista',
        innatum: new Map([
            ['ts', 'Array'],
            ['py', 'list'],
            ['rs', 'Vec'],
            ['cpp', 'std::vector'],
            ['zig', 'Lista'],
        ]),
        methods: new Map([
            ['adde', {
                name: 'adde',
                translations: new Map([
                    ['ts', { method: 'push' }],
                    ['py', { method: 'append' }],
                    ['rs', { method: 'push' }],
                    ['cpp', { method: 'push_back' }],
                    ['zig', { template: '§.adde(§, §)', params: ['ego', 'elem', 'alloc'] }],
                ]),
                radixForms: ['add', 'imperativus', 'perfectum'],
            }],
            ['addita', {
                name: 'addita',
                translations: new Map([
                    ['ts', { template: '[...§, §]', params: ['ego', 'elem'] }],
                    ['py', { template: '[*§, §]', params: ['ego', 'elem'] }],
                    ['rs', { template: '{ let mut v = §.clone(); v.push(§); v }', params: ['ego', 'elem'] }],
                    ['cpp', { template: '[&]{ auto v = §; v.push_back(§); return v; }()', params: ['ego', 'elem'] }],
                    ['zig', { template: '§.addita(§, §)', params: ['ego', 'elem', 'alloc'] }],
                ]),
            }],
        ]),
    }],
]);
