//! Rust Code Generation
//!
//! ARCHITECTURE OVERVIEW
//! =====================
//! This module implements Faber-to-Rust transpilation. It transforms HIR into
//! idiomatic Rust source code, handling error propagation (Result<T, String>),
//! reference modes (de/in/ex), and async/await desugaring.
//!
//! COMPILER PHASE: Codegen
//! INPUT: HirProgram (fully-analyzed HIR), TypeTable, Interner
//! OUTPUT: RustOutput (compilable Rust source code)
//!
//! DESIGN PHILOSOPHY
//! =================
//! - Idiomatic Rust: Generate code that a Rust programmer would write.
//!   WHY: Output should integrate seamlessly with existing Rust ecosystems.
//! - Error propagation analysis: Automatically determine which functions return Result.
//!   WHY: Faber's `iace` (throw) requires Result wrapper; propagate upward transitively.
//! - Reference mode mapping: Translate de/in/ex to &T, &mut T, and owned T.
//!   WHY: Faber's borrow semantics map directly to Rust's ownership system.
//!
//! TRADE-OFFS
//! ==========
//! - All failable functions use String error type (simple but untyped).
//! - Imports are collected post-codegen by scanning output text (avoids complex tracking).
//! - Entry point `incipit` blocks never propagate errors (always use panic! for throws).

mod decl;
mod expr;
mod stmt;
mod types;

use super::{CodeWriter, Codegen, CodegenError};
use crate::hir::{
    DefId, HirBlock, HirExpr, HirExprKind, HirFunction, HirItem, HirItemKind, HirPattern, HirProgram, HirStmtKind,
};
use crate::lexer::{Interner, Symbol};
use crate::semantic::TypeTable;
use crate::RustOutput;
use rustc_hash::{FxHashMap, FxHashSet};
use std::collections::BTreeSet;

// =============================================================================
// CORE
// =============================================================================
//
// The RustCodegen struct pre-computes name resolution and failable function
// analysis during construction, then uses this information during generation.
// This two-phase approach simplifies code generation logic.

/// Rust code generator.
///
/// WHY: Holds pre-analyzed state (names, failable functions) to enable correct
/// error propagation and reference resolution during code generation.
pub struct RustCodegen<'a> {
    /// DefId -> Symbol map for all definitions
    names: FxHashMap<DefId, Symbol>,

    /// Set of DefIds for functions that can throw (return Result)
    failable_defs: FxHashSet<DefId>,

    /// Interner for symbol resolution
    interner: &'a Interner,
}

impl<'a> RustCodegen<'a> {
    pub fn new(hir: &HirProgram, interner: &'a Interner) -> Self {
        let mut codegen = Self { names: FxHashMap::default(), failable_defs: FxHashSet::default(), interner };
        codegen.names = codegen.collect_names(hir);
        codegen.failable_defs = codegen.collect_failable_functions(hir);
        codegen
    }

    fn generate_prelude(&self, w: &mut CodeWriter, imports: &BTreeSet<String>) {
        w.writeln("// Generated by radix - do not edit");
        w.newline();
        w.writeln("#![allow(unused_imports)]");
        w.writeln("#![allow(unused_variables)]");
        w.writeln("#![allow(dead_code)]");
        w.newline();

        for import in imports {
            w.write("use ");
            w.write(import);
            w.writeln(";");
        }

        if !imports.is_empty() {
            w.newline();
        }
    }

    pub(super) fn resolve_symbol(&self, sym: Symbol) -> &str {
        self.interner.resolve(sym)
    }

    pub(super) fn resolve_def(&self, def_id: DefId) -> &str {
        self.names
            .get(&def_id)
            .map(|sym| self.resolve_symbol(*sym))
            .unwrap_or("unresolved_def")
    }

    pub(super) fn is_failable_def(&self, def_id: DefId) -> bool {
        self.failable_defs.contains(&def_id)
    }

    pub(super) fn is_failable_method_name(&self, method: Symbol) -> bool {
        self.names
            .iter()
            .any(|(def_id, name)| *name == method && self.failable_defs.contains(def_id))
    }

    fn generate_item(&self, item: &HirItem, types: &TypeTable, w: &mut CodeWriter) -> Result<(), CodegenError> {
        match &item.kind {
            HirItemKind::Function(func) => {
                decl::generate_function(self, item.def_id, func, types, w)?;
            }
            HirItemKind::Struct(s) => {
                decl::generate_struct(self, s, types, w)?;
            }
            HirItemKind::Enum(e) => {
                decl::generate_enum(self, e, types, w)?;
            }
            HirItemKind::Interface(i) => {
                decl::generate_trait(self, i, types, w)?;
            }
            HirItemKind::TypeAlias(a) => {
                decl::generate_type_alias(self, a, types, w)?;
            }
            HirItemKind::Const(c) => {
                decl::generate_const(self, c, types, w)?;
            }
            HirItemKind::Import(_) => {
                // Handled in prelude or use statements
            }
        }
        Ok(())
    }

    fn collect_names(&self, hir: &HirProgram) -> FxHashMap<DefId, Symbol> {
        let mut names = FxHashMap::default();
        for item in &hir.items {
            match &item.kind {
                HirItemKind::Function(func) => {
                    names.insert(item.def_id, func.name);
                    for type_param in &func.type_params {
                        names.insert(type_param.def_id, type_param.name);
                    }
                    for param in &func.params {
                        names.insert(param.def_id, param.name);
                    }
                    self.collect_block_names(&mut names, func.body.as_ref());
                }
                HirItemKind::Struct(strukt) => {
                    names.insert(item.def_id, strukt.name);
                    for type_param in &strukt.type_params {
                        names.insert(type_param.def_id, type_param.name);
                    }
                    for field in &strukt.fields {
                        names.insert(field.def_id, field.name);
                    }
                    for method in &strukt.methods {
                        names.insert(method.def_id, method.func.name);
                        for type_param in &method.func.type_params {
                            names.insert(type_param.def_id, type_param.name);
                        }
                        for param in &method.func.params {
                            names.insert(param.def_id, param.name);
                        }
                        self.collect_block_names(&mut names, method.func.body.as_ref());
                    }
                }
                HirItemKind::Enum(enum_item) => {
                    names.insert(item.def_id, enum_item.name);
                    for type_param in &enum_item.type_params {
                        names.insert(type_param.def_id, type_param.name);
                    }
                    for variant in &enum_item.variants {
                        names.insert(variant.def_id, variant.name);
                    }
                }
                HirItemKind::Interface(interface) => {
                    names.insert(item.def_id, interface.name);
                    for type_param in &interface.type_params {
                        names.insert(type_param.def_id, type_param.name);
                    }
                }
                HirItemKind::TypeAlias(alias) => {
                    names.insert(item.def_id, alias.name);
                }
                HirItemKind::Const(const_item) => {
                    names.insert(item.def_id, const_item.name);
                }
                HirItemKind::Import(import) => {
                    for item in &import.items {
                        let name = item.alias.unwrap_or(item.name);
                        names.insert(item.def_id, name);
                    }
                }
            }
        }

        if let Some(entry) = &hir.entry {
            self.collect_block_names(&mut names, Some(entry));
        }

        names
    }

    fn collect_block_names(&self, names: &mut FxHashMap<DefId, Symbol>, block: Option<&HirBlock>) {
        let Some(block) = block else {
            return;
        };
        for stmt in &block.stmts {
            match &stmt.kind {
                HirStmtKind::Local(local) => {
                    names.insert(local.def_id, local.name);
                    if let Some(init) = &local.init {
                        self.collect_expr_names(names, init);
                    }
                }
                HirStmtKind::Expr(expr) => self.collect_expr_names(names, expr),
                HirStmtKind::Redde(value) => {
                    if let Some(expr) = value {
                        self.collect_expr_names(names, expr);
                    }
                }
                HirStmtKind::Rumpe | HirStmtKind::Perge => {}
            }
        }
        if let Some(expr) = &block.expr {
            self.collect_expr_names(names, expr);
        }
    }

    fn collect_expr_names(&self, names: &mut FxHashMap<DefId, Symbol>, expr: &HirExpr) {
        match &expr.kind {
            HirExprKind::Binary(_, lhs, rhs) | HirExprKind::Assign(lhs, rhs) | HirExprKind::AssignOp(_, lhs, rhs) => {
                self.collect_expr_names(names, lhs);
                self.collect_expr_names(names, rhs);
            }
            HirExprKind::Unary(_, operand)
            | HirExprKind::Cede(operand)
            | HirExprKind::Qua(operand, _)
            | HirExprKind::Ref(_, operand)
            | HirExprKind::Deref(operand) => self.collect_expr_names(names, operand),
            HirExprKind::Call(callee, args) => {
                self.collect_expr_names(names, callee);
                for arg in args {
                    self.collect_expr_names(names, arg);
                }
            }
            HirExprKind::MethodCall(receiver, _, args) => {
                self.collect_expr_names(names, receiver);
                for arg in args {
                    self.collect_expr_names(names, arg);
                }
            }
            HirExprKind::Field(object, _) | HirExprKind::Index(object, _) => {
                self.collect_expr_names(names, object);
            }
            HirExprKind::Block(block) => self.collect_block_names(names, Some(block)),
            HirExprKind::Si(cond, then_block, else_block) => {
                self.collect_expr_names(names, cond);
                self.collect_block_names(names, Some(then_block));
                self.collect_block_names(names, else_block.as_ref());
            }
            HirExprKind::Discerne(scrutinee, arms) => {
                self.collect_expr_names(names, scrutinee);
                for arm in arms {
                    self.collect_pattern_names(names, &arm.pattern);
                    if let Some(guard) = &arm.guard {
                        self.collect_expr_names(names, guard);
                    }
                    self.collect_expr_names(names, &arm.body);
                }
            }
            HirExprKind::Loop(block) | HirExprKind::Dum(_, block) => {
                self.collect_block_names(names, Some(block));
            }
            HirExprKind::Itera(_, iter, block) => {
                self.collect_expr_names(names, iter);
                self.collect_block_names(names, Some(block));
            }
            HirExprKind::Array(elements) | HirExprKind::Tuple(elements) | HirExprKind::Scribe(elements) => {
                for element in elements {
                    self.collect_expr_names(names, element);
                }
            }
            HirExprKind::Scriptum(_, args) => {
                for arg in args {
                    self.collect_expr_names(names, arg);
                }
            }
            HirExprKind::Adfirma(cond, message) => {
                self.collect_expr_names(names, cond);
                if let Some(message) = message {
                    self.collect_expr_names(names, message);
                }
            }
            HirExprKind::Panic(value) => self.collect_expr_names(names, value),
            HirExprKind::Throw(value) => self.collect_expr_names(names, value),
            HirExprKind::Tempta { body, catch, finally } => {
                self.collect_block_names(names, Some(body));
                self.collect_block_names(names, catch.as_ref());
                self.collect_block_names(names, finally.as_ref());
            }
            HirExprKind::Struct(_, fields) => {
                for (_, value) in fields {
                    self.collect_expr_names(names, value);
                }
            }
            HirExprKind::Clausura(params, _, body) => {
                for param in params {
                    names.insert(param.def_id, param.name);
                }
                self.collect_expr_names(names, body);
            }
            HirExprKind::Path(_) | HirExprKind::Literal(_) | HirExprKind::Error => {}
        }
    }

    #[allow(clippy::only_used_in_recursion)]
    fn collect_pattern_names(&self, names: &mut FxHashMap<DefId, Symbol>, pattern: &HirPattern) {
        match pattern {
            HirPattern::Wildcard => {}
            HirPattern::Binding(def_id, name) => {
                names.insert(*def_id, *name);
            }
            HirPattern::Variant(_, patterns) => {
                for pattern in patterns {
                    self.collect_pattern_names(names, pattern);
                }
            }
            HirPattern::Literal(_) => {}
        }
    }

    /// Transitively compute which functions can throw errors.
    ///
    /// WHY: Functions that call throwing functions must propagate Result, but
    /// this is a transitive property requiring fixed-point analysis. We compute
    /// it upfront to avoid repeated traversals during codegen.
    ///
    /// EDGE: `tempta` with catch block suppresses error propagation from body.
    fn collect_failable_functions(&self, hir: &HirProgram) -> FxHashSet<DefId> {
        #[derive(Default)]
        struct FnDeps {
            direct_throw: bool,
            calls: FxHashSet<DefId>,
            method_calls: FxHashSet<Symbol>,
        }

        fn visit_block(block: &HirBlock, suppressed: bool, deps: &mut FnDeps) {
            for stmt in &block.stmts {
                match &stmt.kind {
                    HirStmtKind::Local(local) => {
                        if let Some(init) = &local.init {
                            visit_expr(init, suppressed, deps);
                        }
                    }
                    HirStmtKind::Expr(expr) => visit_expr(expr, suppressed, deps),
                    HirStmtKind::Redde(value) => {
                        if let Some(expr) = value {
                            visit_expr(expr, suppressed, deps);
                        }
                    }
                    HirStmtKind::Rumpe | HirStmtKind::Perge => {}
                }
            }
            if let Some(expr) = &block.expr {
                visit_expr(expr, suppressed, deps);
            }
        }

        fn visit_expr(expr: &HirExpr, suppressed: bool, deps: &mut FnDeps) {
            match &expr.kind {
                HirExprKind::Throw(value) => {
                    if !suppressed {
                        deps.direct_throw = true;
                    }
                    visit_expr(value, suppressed, deps);
                }
                HirExprKind::Call(callee, args) => {
                    if !suppressed {
                        if let HirExprKind::Path(def_id) = &callee.kind {
                            deps.calls.insert(*def_id);
                        }
                    }
                    visit_expr(callee, suppressed, deps);
                    for arg in args {
                        visit_expr(arg, suppressed, deps);
                    }
                }
                HirExprKind::MethodCall(receiver, method, args) => {
                    if !suppressed {
                        deps.method_calls.insert(*method);
                    }
                    visit_expr(receiver, suppressed, deps);
                    for arg in args {
                        visit_expr(arg, suppressed, deps);
                    }
                }
                HirExprKind::Tempta { body, catch, finally } => {
                    let body_suppressed = suppressed || catch.is_some();
                    visit_block(body, body_suppressed, deps);
                    if let Some(catch_block) = catch {
                        visit_block(catch_block, suppressed, deps);
                    }
                    if let Some(finally_block) = finally {
                        visit_block(finally_block, suppressed, deps);
                    }
                }
                HirExprKind::Binary(_, lhs, rhs)
                | HirExprKind::Assign(lhs, rhs)
                | HirExprKind::AssignOp(_, lhs, rhs) => {
                    visit_expr(lhs, suppressed, deps);
                    visit_expr(rhs, suppressed, deps);
                }
                HirExprKind::Unary(_, operand)
                | HirExprKind::Cede(operand)
                | HirExprKind::Qua(operand, _)
                | HirExprKind::Ref(_, operand)
                | HirExprKind::Deref(operand)
                | HirExprKind::Panic(operand) => visit_expr(operand, suppressed, deps),
                HirExprKind::Field(object, _) | HirExprKind::Index(object, _) => {
                    visit_expr(object, suppressed, deps);
                }
                HirExprKind::Block(block) | HirExprKind::Loop(block) => {
                    visit_block(block, suppressed, deps);
                }
                HirExprKind::Si(cond, then_block, else_block) => {
                    visit_expr(cond, suppressed, deps);
                    visit_block(then_block, suppressed, deps);
                    if let Some(else_block) = else_block {
                        visit_block(else_block, suppressed, deps);
                    }
                }
                HirExprKind::Discerne(scrutinee, arms) => {
                    visit_expr(scrutinee, suppressed, deps);
                    for arm in arms {
                        if let Some(guard) = &arm.guard {
                            visit_expr(guard, suppressed, deps);
                        }
                        visit_expr(&arm.body, suppressed, deps);
                    }
                }
                HirExprKind::Dum(cond, block) => {
                    visit_expr(cond, suppressed, deps);
                    visit_block(block, suppressed, deps);
                }
                HirExprKind::Itera(_, iter, block) => {
                    visit_expr(iter, suppressed, deps);
                    visit_block(block, suppressed, deps);
                }
                HirExprKind::Array(elements) | HirExprKind::Tuple(elements) | HirExprKind::Scribe(elements) => {
                    for element in elements {
                        visit_expr(element, suppressed, deps);
                    }
                }
                HirExprKind::Scriptum(_, args) => {
                    for arg in args {
                        visit_expr(arg, suppressed, deps);
                    }
                }
                HirExprKind::Adfirma(cond, message) => {
                    visit_expr(cond, suppressed, deps);
                    if let Some(message) = message {
                        visit_expr(message, suppressed, deps);
                    }
                }
                HirExprKind::Struct(_, fields) => {
                    for (_, value) in fields {
                        visit_expr(value, suppressed, deps);
                    }
                }
                HirExprKind::Clausura(_, _, body) => visit_expr(body, suppressed, deps),
                HirExprKind::Path(_) | HirExprKind::Literal(_) | HirExprKind::Error => {}
            }
        }

        let mut fn_deps: FxHashMap<DefId, FnDeps> = FxHashMap::default();
        let mut register_fn = |def_id: DefId, func: &HirFunction| {
            let mut deps = FnDeps::default();
            if let Some(body) = &func.body {
                visit_block(body, false, &mut deps);
            }
            fn_deps.insert(def_id, deps);
        };

        for item in &hir.items {
            match &item.kind {
                HirItemKind::Function(func) => register_fn(item.def_id, func),
                HirItemKind::Struct(strukt) => {
                    for method in &strukt.methods {
                        register_fn(method.def_id, &method.func);
                    }
                }
                _ => {}
            }
        }

        let mut failable = FxHashSet::default();
        for (def_id, deps) in &fn_deps {
            if deps.direct_throw {
                failable.insert(*def_id);
            }
        }

        let mut changed = true;
        while changed {
            changed = false;
            for (def_id, deps) in &fn_deps {
                if failable.contains(def_id) {
                    continue;
                }

                let mut dependent_failable = deps.calls.iter().any(|callee| failable.contains(callee));
                if !dependent_failable {
                    dependent_failable = deps.method_calls.iter().any(|method| {
                        self.names
                            .iter()
                            .any(|(callee_def, name)| name == method && failable.contains(callee_def))
                    });
                }

                if dependent_failable {
                    failable.insert(*def_id);
                    changed = true;
                }
            }
        }

        failable
    }
}

fn normalize_import_path(path: &str) -> String {
    path.replace("::", "/")
        .split('/')
        .filter(|segment| !segment.is_empty())
        .collect::<Vec<_>>()
        .join("::")
}

// =============================================================================
// HELPERS
// =============================================================================
//
// Import collection is done post-codegen by scanning the generated source text.
// WHY: Simpler than tracking imports during traversal; Rust types are known ahead.

/// Scan generated code for Rust types that require imports.
///
/// WHY: HashMap/HashSet aren't in Rust prelude; auto-import them if used.
fn collect_prelude_imports(code: &str) -> BTreeSet<String> {
    let mut imports = BTreeSet::new();
    if code.contains("HashMap<") {
        imports.insert("std::collections::HashMap".to_owned());
    }
    if code.contains("HashSet<") {
        imports.insert("std::collections::HashSet".to_owned());
    }
    if code.contains("Future<Output =") {
        imports.insert("std::future::Future".to_owned());
    }
    imports
}

fn collect_hir_imports(codegen: &RustCodegen<'_>, hir: &HirProgram) -> BTreeSet<String> {
    let mut imports = BTreeSet::new();
    for item in &hir.items {
        let HirItemKind::Import(import) = &item.kind else {
            continue;
        };

        let path = normalize_import_path(codegen.resolve_symbol(import.path));
        if path.is_empty() {
            continue;
        }

        for import_item in &import.items {
            let name = codegen.resolve_symbol(import_item.name);
            if let Some(alias) = import_item.alias {
                let alias_name = codegen.resolve_symbol(alias);
                if alias_name == name {
                    imports.insert(format!("{path} as {alias_name}"));
                } else {
                    imports.insert(format!("{path}::{name} as {alias_name}"));
                }
            } else {
                imports.insert(format!("{path}::{name}"));
            }
        }
    }
    imports
}

impl Codegen for RustCodegen<'_> {
    type Output = RustOutput;

    fn generate(&self, hir: &HirProgram, types: &TypeTable, _interner: &Interner) -> Result<RustOutput, CodegenError> {
        let mut body = CodeWriter::new();

        for item in &hir.items {
            self.generate_item(item, types, &mut body)?;
            body.newline();
        }

        // Generate main if there's an entry point
        if let Some(entry) = &hir.entry {
            body.writeln("fn main() {");
            body.indented(|w| {
                for stmt in &entry.stmts {
                    let _ = stmt::generate_stmt(self, stmt, types, w, false, true, false);
                }
                if let Some(expr) = &entry.expr {
                    let _ = expr::generate_expr(self, expr, types, w, false, true, false);
                    w.writeln(";");
                }
            });
            body.writeln("}");
        }

        let body_code = body.finish();
        let mut imports = collect_hir_imports(self, hir);
        imports.extend(collect_prelude_imports(&body_code));

        let mut w = CodeWriter::new();
        self.generate_prelude(&mut w, &imports);
        w.write(&body_code);

        Ok(RustOutput { code: w.finish() })
    }
}

#[cfg(test)]
#[path = "mod_test.rs"]
mod tests;
