#!/usr/bin/env bun
/**
 * Build standalone faber executable.
 *
 * Steps:
 *   1. Compile faber CLI to standalone binary
 *
 * Note: norma.gen.ts is now generated by build:norma (not here)
 */

import { mkdir, symlink, unlink } from 'fs/promises';
import { join } from 'path';
import { $ } from 'bun';

const ROOT = join(import.meta.dir, '..');

async function main() {
    const start = performance.now();

    // Typecheck fons/faber/ before compiling
    await $`tsc -p tsconfig.faber.json`.cwd(ROOT);

    const binDir = join(ROOT, 'opus', 'bin');
    await mkdir(binDir, { recursive: true });
    const outExe = join(binDir, 'faber-ts');
    await $`bun build ${join(ROOT, 'fons', 'faber', 'faber.ts')} --compile --outfile=${outExe}`.quiet();
    await $`bash -c 'rm -f .*.bun-build 2>/dev/null || true'`.quiet();

    // Create backward-compat symlink: faber -> faber-ts
    const symlinkPath = join(binDir, 'faber');
    try { await unlink(symlinkPath); } catch { /* ignore */ }
    await symlink('faber-ts', symlinkPath);

    const elapsed = performance.now() - start;
    console.log(`Built opus/bin/faber-ts (${elapsed.toFixed(0)}ms)`);
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
