//! Experimental LLVM text emitter for validated MIR.
//!
//! TARGET: LLVM backend lane proof. This module intentionally emits only a
//! small textual `.ll` subset so Faber can reserve an LLVM target surface
//! without taking a dependency on a local LLVM installation or an LLVM binding
//! crate before the MIR layout/ABI story is ready.

use crate::codegen::CodeWriter;
use crate::lexer::Interner;
use crate::mir::*;
use crate::semantic::{Primitive, Type, TypeTable};
use rustc_hash::FxHashMap;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MirLlvmTextProbeError {
    pub message: String,
}

impl MirLlvmTextProbeError {
    fn unsupported(shape: impl Into<String>) -> Self {
        Self { message: format!("MIR-to-LLVM unsupported: {}", shape.into()) }
    }
}

impl std::fmt::Display for MirLlvmTextProbeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for MirLlvmTextProbeError {}

pub fn emit_llvm_text_probe(
    program: &MirProgram,
    types: &TypeTable,
    interner: &Interner,
) -> Result<String, MirLlvmTextProbeError> {
    LlvmProbe { program, types, interner }.emit_program()
}

struct LlvmProbe<'a> {
    program: &'a MirProgram,
    types: &'a TypeTable,
    interner: &'a Interner,
}

struct FunctionContext {
    values: FxHashMap<MirValueId, String>,
    locals: FxHashMap<MirLocalId, String>,
    temps: FxHashMap<MirTempId, String>,
}

impl LlvmProbe<'_> {
    fn emit_program(&self) -> Result<String, MirLlvmTextProbeError> {
        let mut writer = CodeWriter::new();
        writer.writeln("; Generated by radix MIR LLVM IR probe - experimental artifact.");
        writer.newline();
        for function in &self.program.functions {
            self.emit_function(function, &mut writer)?;
            writer.newline();
        }
        Ok(writer.finish())
    }

    fn emit_function(&self, function: &MirFunction, writer: &mut CodeWriter) -> Result<(), MirLlvmTextProbeError> {
        let params = function
            .params
            .iter()
            .map(|param| Ok(format!("{} %{}", self.llvm_ty(param.ty)?, local_name(param.local))))
            .collect::<Result<Vec<_>, MirLlvmTextProbeError>>()?
            .join(", ");
        writer.writeln(&format!(
            "define {} @{}({}) {{",
            self.llvm_ty(function.return_ty)?,
            self.function_name(function),
            params
        ));
        writer.indented(|writer| {
            writer.writeln("entry:");
        });
        let mut context =
            FunctionContext { values: FxHashMap::default(), locals: FxHashMap::default(), temps: FxHashMap::default() };
        for block in &function.blocks {
            if block.id != MirBlockId(0) {
                return Err(MirLlvmTextProbeError::unsupported("multiple basic blocks"));
            }
            for stmt in &block.statements {
                self.emit_stmt(stmt, &mut context, writer)?;
            }
            self.emit_terminator(&block.terminator, &context, writer, function.return_ty)?;
        }
        writer.writeln("}");
        Ok(())
    }

    fn emit_stmt(
        &self,
        stmt: &MirStmt,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirLlvmTextProbeError> {
        let MirStmtKind::Assign { place, value } = &stmt.kind else {
            return Err(MirLlvmTextProbeError::unsupported(stmt_kind_name(&stmt.kind)));
        };
        if !place.projections.is_empty() {
            return Err(MirLlvmTextProbeError::unsupported("place projection"));
        }
        let expr = match &value.kind {
            MirValueKind::Operand(operand) => self.operand(operand, context)?,
            MirValueKind::Binary { op, lhs, rhs } => {
                let ty = self.llvm_ty(value.ty)?;
                let op = llvm_bin_op(*op)?;
                let lhs = self.operand(lhs, context)?;
                let rhs = self.operand(rhs, context)?;
                let dest = format!("%v{}", value.id.0);
                writer.indented(|writer| {
                    writer.writeln(&format!("  {} = {} {} {}, {}", dest, op, ty, lhs, rhs));
                });
                dest
            }
            MirValueKind::Unary { .. } => return Err(MirLlvmTextProbeError::unsupported("unary value")),
            MirValueKind::Option(_) => return Err(MirLlvmTextProbeError::unsupported("option value")),
        };
        context.values.insert(value.id, expr.clone());
        match place.base {
            MirPlaceBase::Local(id) => {
                context.locals.insert(id, expr);
            }
            MirPlaceBase::Temp(id) => {
                context.temps.insert(id, expr);
            }
        }
        Ok(())
    }

    fn emit_terminator(
        &self,
        terminator: &MirTerminator,
        context: &FunctionContext,
        writer: &mut CodeWriter,
        return_ty: MirType,
    ) -> Result<(), MirLlvmTextProbeError> {
        match &terminator.kind {
            MirTerminatorKind::Return(Some(operand)) => {
                let ty = self.llvm_ty(return_ty)?;
                let value = self.operand(operand, context)?;
                writer.indented(|writer| {
                    writer.writeln(&format!("  ret {} {}", ty, value));
                });
                Ok(())
            }
            MirTerminatorKind::Return(None) => {
                writer.indented(|writer| writer.writeln("  ret void"));
                Ok(())
            }
            other => Err(MirLlvmTextProbeError::unsupported(terminator_kind_name(other))),
        }
    }

    fn operand(&self, operand: &MirOperand, context: &FunctionContext) -> Result<String, MirLlvmTextProbeError> {
        match operand {
            MirOperand::Place(place) => self.place(place, context),
            MirOperand::Value(id) => context
                .values
                .get(id)
                .cloned()
                .ok_or_else(|| MirLlvmTextProbeError::unsupported(format!("undefined value v{}", id.0))),
            MirOperand::Constant(constant) => self.constant(constant),
            MirOperand::Temp(id) => context
                .temps
                .get(id)
                .cloned()
                .ok_or_else(|| MirLlvmTextProbeError::unsupported(format!("undefined temp t{}", id.0))),
        }
    }

    fn place(&self, place: &MirPlace, context: &FunctionContext) -> Result<String, MirLlvmTextProbeError> {
        if !place.projections.is_empty() {
            return Err(MirLlvmTextProbeError::unsupported("place projection"));
        }
        match place.base {
            MirPlaceBase::Local(id) => Ok(context
                .locals
                .get(&id)
                .cloned()
                .unwrap_or_else(|| format!("%{}", local_name(id)))),
            MirPlaceBase::Temp(_) => Err(MirLlvmTextProbeError::unsupported("temp place without assignment context")),
        }
    }

    fn constant(&self, constant: &MirConstant) -> Result<String, MirLlvmTextProbeError> {
        match constant {
            MirConstant::Int(value) => Ok(value.to_string()),
            MirConstant::Bool(value) => Ok(if *value { "1" } else { "0" }.to_owned()),
            MirConstant::Unit => Ok("0".to_owned()),
            MirConstant::Float(_) => Err(MirLlvmTextProbeError::unsupported("float constant")),
            MirConstant::String(_) => Err(MirLlvmTextProbeError::unsupported("string constant")),
            MirConstant::Nil => Err(MirLlvmTextProbeError::unsupported("nil constant")),
        }
    }

    fn llvm_ty(&self, ty: MirType) -> Result<&'static str, MirLlvmTextProbeError> {
        match self.types.get(ty.semantic_id()) {
            Type::Primitive(Primitive::Numerus) => Ok("i64"),
            Type::Primitive(Primitive::Bivalens) => Ok("i1"),
            Type::Primitive(Primitive::Vacuum) => Ok("void"),
            Type::Alias(_, target) => self.llvm_ty(MirType::semantic(*target)),
            other => Err(MirLlvmTextProbeError::unsupported(format!("type {other:?}"))),
        }
    }

    fn function_name(&self, function: &MirFunction) -> String {
        function
            .name
            .map(|symbol| sanitize_name(self.interner.resolve(symbol)))
            .unwrap_or_else(|| format!("f{}", function.id.0))
    }
}

fn local_name(id: MirLocalId) -> String {
    format!("l{}", id.0)
}

fn sanitize_name(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn llvm_bin_op(op: MirBinOp) -> Result<&'static str, MirLlvmTextProbeError> {
    match op {
        MirBinOp::Add => Ok("add"),
        MirBinOp::Sub => Ok("sub"),
        MirBinOp::Mul => Ok("mul"),
        MirBinOp::Div => Ok("sdiv"),
        MirBinOp::Mod => Ok("srem"),
        _ => Err(MirLlvmTextProbeError::unsupported(format!("binary op {op:?}"))),
    }
}

fn stmt_kind_name(kind: &MirStmtKind) -> &'static str {
    match kind {
        MirStmtKind::Assign { .. } => "assign",
        MirStmtKind::Call { .. } => "call",
        MirStmtKind::RuntimeCall { .. } => "runtime call",
        MirStmtKind::Construct { .. } => "construct",
    }
}

fn terminator_kind_name(kind: &MirTerminatorKind) -> &'static str {
    match kind {
        MirTerminatorKind::Return(_) => "return",
        MirTerminatorKind::ReturnError(_) => "return_error",
        MirTerminatorKind::TryCall { .. } => "try_call",
        MirTerminatorKind::Goto(_) => "goto",
        MirTerminatorKind::Branch { .. } => "branch",
        MirTerminatorKind::Switch { .. } => "switch",
        MirTerminatorKind::Unreachable => "unreachable",
    }
}

#[cfg(test)]
#[path = "llvm_text_test.rs"]
mod tests;
