//! Experimental LLVM text emitter for validated MIR.
//!
//! TARGET: LLVM backend lane proof. This module intentionally emits only a
//! small textual `.ll` subset so Faber can reserve an LLVM target surface
//! without taking a dependency on a local LLVM installation or an LLVM binding
//! crate before the MIR layout/ABI story is ready.

use crate::codegen::CodeWriter;
use crate::hir::DefId;
use crate::lexer::Interner;
use crate::mir::*;
use crate::semantic::{Primitive, Type, TypeTable};
use rustc_hash::FxHashMap;
use std::collections::BTreeMap;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MirLlvmTextProbeError {
    pub message: String,
}

impl MirLlvmTextProbeError {
    fn unsupported(shape: impl Into<String>) -> Self {
        Self { message: format!("MIR-to-LLVM unsupported: {}", shape.into()) }
    }
}

impl std::fmt::Display for MirLlvmTextProbeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for MirLlvmTextProbeError {}

pub fn emit_llvm_text_probe(
    program: &MirProgram,
    types: &TypeTable,
    interner: &Interner,
) -> Result<String, MirLlvmTextProbeError> {
    let validation = MirValidationContext::new(types);
    emit_llvm_text_probe_with_context(program, &validation, interner)
}

pub fn emit_llvm_text_probe_with_context(
    program: &MirProgram,
    validation: &MirValidationContext<'_>,
    interner: &Interner,
) -> Result<String, MirLlvmTextProbeError> {
    LlvmProbe { program, types: validation.types, validation, interner }.emit_program()
}

struct LlvmProbe<'a> {
    program: &'a MirProgram,
    types: &'a TypeTable,
    validation: &'a MirValidationContext<'a>,
    interner: &'a Interner,
}

struct FunctionContext {
    values: FxHashMap<MirValueId, String>,
    value_tys: FxHashMap<MirValueId, MirType>,
    local_tys: FxHashMap<MirLocalId, MirType>,
    temp_tys: FxHashMap<MirTempId, MirType>,
    load_counter: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum LlvmScalar {
    I1,
    I64,
    F64,
    Ptr,
    Void,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ExternalDecl {
    symbol: String,
    return_ty: &'static str,
    params: Vec<&'static str>,
}

impl LlvmProbe<'_> {
    fn emit_program(&self) -> Result<String, MirLlvmTextProbeError> {
        let mut writer = CodeWriter::new();
        writer.writeln("; Generated by radix MIR LLVM IR probe - experimental artifact.");
        for declaration in self.external_declarations()? {
            writer.writeln(&format!(
                "declare {} @{}({})",
                declaration.return_ty,
                declaration.symbol,
                declaration.params.join(", ")
            ));
        }
        writer.newline();
        for function in &self.program.functions {
            self.emit_function(function, &mut writer)?;
            writer.newline();
        }
        Ok(writer.finish())
    }

    fn emit_function(&self, function: &MirFunction, writer: &mut CodeWriter) -> Result<(), MirLlvmTextProbeError> {
        let params = function
            .params
            .iter()
            .map(|param| Ok(format!("{} %{}", self.llvm_ty(param.ty)?, local_name(param.local))))
            .collect::<Result<Vec<_>, MirLlvmTextProbeError>>()?
            .join(", ");
        writer.writeln(&format!(
            "define {} @{}({}) {{",
            self.llvm_function_return_ty(function.return_ty)?,
            self.function_name(function),
            params
        ));
        writer.indented(|writer| writer.writeln("entry:"));
        let mut context = FunctionContext {
            values: FxHashMap::default(),
            value_tys: FxHashMap::default(),
            local_tys: function
                .locals
                .iter()
                .map(|local| (local.id, local.ty))
                .chain(function.params.iter().map(|param| (param.local, param.ty)))
                .collect(),
            temp_tys: function
                .temps
                .iter()
                .map(|temp| (temp.id, temp.ty))
                .collect(),
            load_counter: 0,
        };
        for local in &function.locals {
            let ty = self.llvm_ty(local.ty)?;
            writer.indented(|writer| {
                writer.writeln(&format!("  {} = alloca {}", local_slot(local.id), ty));
            });
        }
        for temp in &function.temps {
            let ty = self.llvm_ty(temp.ty)?;
            writer.indented(|writer| {
                writer.writeln(&format!("  {} = alloca {}", temp_slot(temp.id), ty));
            });
        }
        for param in &function.params {
            let ty = self.llvm_ty(param.ty)?;
            writer.indented(|writer| {
                writer.writeln(&format!(
                    "  store {} %{}, ptr {}",
                    ty,
                    local_name(param.local),
                    local_slot(param.local)
                ));
            });
        }
        writer.indented(|writer| {
            writer.writeln("  br label %bb0");
        });
        for block in &function.blocks {
            writer.indented(|writer| writer.writeln(&format!("{}:", block_label(block.id))));
            for stmt in &block.statements {
                self.emit_stmt(stmt, &mut context, writer)?;
            }
            self.emit_terminator(&block.terminator, &mut context, writer, function.return_ty)?;
        }
        writer.writeln("}");
        Ok(())
    }

    fn emit_stmt(
        &self,
        stmt: &MirStmt,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirLlvmTextProbeError> {
        match &stmt.kind {
            MirStmtKind::Assign { place, value } => self.emit_assign(place, value, context, writer),
            MirStmtKind::Call { destination, callee, args } => {
                self.emit_call(destination.as_ref(), callee, args, context, writer)
            }
            MirStmtKind::RuntimeCall { destination, call } => {
                self.emit_runtime_call(destination.as_ref(), call, context, writer)
            }
            MirStmtKind::Construct { destination, aggregate } => {
                self.emit_construct(destination, aggregate, context, writer)
            }
        }
    }

    fn emit_assign(
        &self,
        place: &MirPlace,
        value: &MirValue,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirLlvmTextProbeError> {
        let expr = match &value.kind {
            MirValueKind::Operand(operand) => self.operand(operand, context, writer)?,
            MirValueKind::Binary { op, lhs, rhs } => {
                let lhs_ty = self.operand_ty(lhs, context)?;
                let ty = self.llvm_ty(lhs_ty)?;
                let op = self.llvm_bin_op(*op, lhs_ty)?;
                let lhs = self.operand(lhs, context, writer)?;
                let rhs = self.operand(rhs, context, writer)?;
                let dest = format!("%v{}", value.id.0);
                writer.indented(|writer| {
                    writer.writeln(&format!("  {} = {} {} {}, {}", dest, op, ty, lhs, rhs));
                });
                dest
            }
            MirValueKind::Unary { op, operand } => {
                let operand_ty = self.operand_ty(operand, context)?;
                let operand = self.operand(operand, context, writer)?;
                let dest = format!("%v{}", value.id.0);
                let expr = self.llvm_unary_expr(*op, operand_ty, &operand)?;
                writer.indented(|writer| {
                    writer.writeln(&format!("  {dest} = {expr}"));
                });
                dest
            }
            MirValueKind::Option(op) => self.option_expr(op, value.ty, context, writer)?,
        };
        context.values.insert(value.id, expr.clone());
        context.value_tys.insert(value.id, value.ty);
        self.store_place(place, &expr, context, writer)
    }

    fn emit_construct(
        &self,
        destination: &MirPlace,
        aggregate: &MirAggregate,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirLlvmTextProbeError> {
        let declaration = self.aggregate_declaration(aggregate, context)?;
        let mut rendered_args = Vec::new();
        if let Some(def_id) = aggregate_definition_id(&aggregate.kind) {
            rendered_args.push(format!("i64 {}", def_id.0));
        }
        for operand in aggregate_operands(&aggregate.fields)? {
            let arg_ty = self.llvm_ty(self.operand_ty(operand, context)?)?;
            let arg_value = self.operand(operand, context, writer)?;
            rendered_args.push(format!("{arg_ty} {arg_value}"));
        }
        let dest = format!("%agg{}", context.load_counter);
        context.load_counter += 1;
        writer.indented(|writer| {
            writer.writeln(&format!(
                "  {dest} = call {} @{}({})",
                declaration.return_ty,
                declaration.symbol,
                rendered_args.join(", ")
            ));
        });
        self.store_place(destination, &dest, context, writer)
    }

    fn option_expr(
        &self,
        op: &MirOptionOp,
        result_ty: MirType,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<String, MirLlvmTextProbeError> {
        let declaration = self.option_declaration(op, result_ty, context)?;
        let mut rendered_args = Vec::new();
        match op {
            MirOptionOp::None => {}
            MirOptionOp::Some(value) => {
                let ty = self.llvm_ty(self.operand_ty(value, context)?)?;
                let value = self.operand(value, context, writer)?;
                rendered_args.push(format!("{ty} {value}"));
            }
            MirOptionOp::IsNil(value) | MirOptionOp::IsNonNil(value) => {
                let value = self.operand(value, context, writer)?;
                rendered_args.push(format!("ptr {value}"));
            }
            MirOptionOp::Unwrap { value, .. } => {
                let value = self.operand(value, context, writer)?;
                rendered_args.push(format!("ptr {value}"));
            }
            MirOptionOp::Coalesce { value, fallback } => {
                let value = self.operand(value, context, writer)?;
                let fallback_ty = self.llvm_ty(self.operand_ty(fallback, context)?)?;
                let fallback = self.operand(fallback, context, writer)?;
                rendered_args.push(format!("ptr {value}"));
                rendered_args.push(format!("{fallback_ty} {fallback}"));
            }
            MirOptionOp::Chain { .. } => return Err(MirLlvmTextProbeError::unsupported("option chain value")),
        }
        let dest = format!("%opt{}", context.load_counter);
        context.load_counter += 1;
        writer.indented(|writer| {
            writer.writeln(&format!(
                "  {dest} = call {} @{}({})",
                declaration.return_ty,
                declaration.symbol,
                rendered_args.join(", ")
            ));
        });
        Ok(dest)
    }

    fn emit_call(
        &self,
        destination: Option<&MirPlace>,
        callee: &MirCallee,
        args: &[MirOperand],
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirLlvmTextProbeError> {
        let function = self.callee_function(callee)?;
        let return_ty = self.llvm_ty(function.return_ty)?;
        let mut rendered_args = Vec::with_capacity(args.len());
        for arg in args {
            let arg_ty = self.llvm_ty(self.operand_ty(arg, context)?)?;
            let arg_value = self.operand(arg, context, writer)?;
            rendered_args.push(format!("{arg_ty} {arg_value}"));
        }
        let call = format!(
            "call {return_ty} @{}({})",
            self.function_name(function),
            rendered_args.join(", ")
        );
        if let Some(destination) = destination {
            let dest = format!("%call{}", context.load_counter);
            context.load_counter += 1;
            writer.indented(|writer| writer.writeln(&format!("  {dest} = {call}")));
            self.store_place(destination, &dest, context, writer)
        } else {
            writer.indented(|writer| writer.writeln(&format!("  {call}")));
            Ok(())
        }
    }

    fn emit_runtime_call(
        &self,
        destination: Option<&MirPlace>,
        call: &MirRuntimeCall,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirLlvmTextProbeError> {
        let declaration = self.runtime_declaration(call, context)?;
        let mut rendered_args = Vec::with_capacity(call.args.len());
        for arg in &call.args {
            let arg_ty = self.llvm_ty(self.operand_ty(arg, context)?)?;
            let arg_value = self.operand(arg, context, writer)?;
            rendered_args.push(format!("{arg_ty} {arg_value}"));
        }
        let call_expr = format!(
            "call {} @{}({})",
            declaration.return_ty,
            declaration.symbol,
            rendered_args.join(", ")
        );
        match (destination, declaration.return_ty) {
            (Some(_), "void") => Err(MirLlvmTextProbeError::unsupported("void runtime destination")),
            (Some(destination), _) => {
                let dest = format!("%rtcall{}", context.load_counter);
                context.load_counter += 1;
                writer.indented(|writer| writer.writeln(&format!("  {dest} = {call_expr}")));
                self.store_place(destination, &dest, context, writer)
            }
            (None, _) => {
                writer.indented(|writer| writer.writeln(&format!("  {call_expr}")));
                Ok(())
            }
        }
    }

    fn store_place(
        &self,
        place: &MirPlace,
        expr: &str,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirLlvmTextProbeError> {
        if !place.projections.is_empty() {
            let (base_value, declaration, key_value) = self.projection_set_call_parts(place, context, writer)?;
            writer.indented(|writer| {
                writer.writeln(&format!(
                    "  call {} @{}({base_value}, {key_value}, {} {expr})",
                    declaration.return_ty,
                    declaration.symbol,
                    declaration.params.last().copied().unwrap_or("void")
                ));
            });
            return Ok(());
        }
        let ty = self.llvm_ty(self.place_ty(place, context)?)?;
        let slot = place_slot(place)?;
        writer.indented(|writer| {
            writer.writeln(&format!("  store {ty} {expr}, ptr {slot}"));
        });
        Ok(())
    }

    fn emit_terminator(
        &self,
        terminator: &MirTerminator,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
        return_ty: MirType,
    ) -> Result<(), MirLlvmTextProbeError> {
        match &terminator.kind {
            MirTerminatorKind::Return(Some(operand)) => {
                let ty = self.llvm_function_return_ty(return_ty)?;
                let value = self.operand(operand, context, writer)?;
                writer.indented(|writer| {
                    writer.writeln(&format!("  ret {} {}", ty, value));
                });
                Ok(())
            }
            MirTerminatorKind::Return(None) => {
                writer.indented(|writer| writer.writeln("  ret void"));
                Ok(())
            }
            MirTerminatorKind::Goto(target) => {
                writer.indented(|writer| {
                    writer.writeln(&format!("  br label %{}", block_label(*target)));
                });
                Ok(())
            }
            MirTerminatorKind::Branch { condition, then_block, else_block } => {
                let condition = self.operand(condition, context, writer)?;
                writer.indented(|writer| {
                    writer.writeln(&format!(
                        "  br i1 {condition}, label %{}, label %{}",
                        block_label(*then_block),
                        block_label(*else_block)
                    ));
                });
                Ok(())
            }
            other => Err(MirLlvmTextProbeError::unsupported(terminator_kind_name(other))),
        }
    }

    fn operand(
        &self,
        operand: &MirOperand,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<String, MirLlvmTextProbeError> {
        match operand {
            MirOperand::Place(place) => self.place(place, context, writer),
            MirOperand::Value(id) => context
                .values
                .get(id)
                .cloned()
                .ok_or_else(|| MirLlvmTextProbeError::unsupported(format!("undefined value v{}", id.0))),
            MirOperand::Constant(constant) => self.constant(constant),
            MirOperand::Temp(id) => self.load_slot(
                temp_slot(*id),
                *context
                    .temp_tys
                    .get(id)
                    .ok_or_else(|| MirLlvmTextProbeError::unsupported(format!("undefined temp type t{}", id.0)))?,
                context,
                writer,
            ),
        }
    }

    fn operand_ty(&self, operand: &MirOperand, context: &FunctionContext) -> Result<MirType, MirLlvmTextProbeError> {
        match operand {
            MirOperand::Place(place) => self.place_ty(place, context),
            MirOperand::Value(id) => context
                .value_tys
                .get(id)
                .copied()
                .ok_or_else(|| MirLlvmTextProbeError::unsupported(format!("undefined value type v{}", id.0))),
            MirOperand::Temp(id) => context
                .temp_tys
                .get(id)
                .copied()
                .ok_or_else(|| MirLlvmTextProbeError::unsupported(format!("undefined temp type t{}", id.0))),
            MirOperand::Constant(constant) => self.constant_ty(constant),
        }
    }

    fn place(
        &self,
        place: &MirPlace,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<String, MirLlvmTextProbeError> {
        let mut expr = self.load_slot(place_base_slot(place)?, self.place_base_ty(place, context)?, context, writer)?;
        let mut ty = self.place_base_ty(place, context)?;
        for projection in &place.projections {
            let (declaration, key_value, result_ty) = self.projection_declaration(projection, ty, context, writer)?;
            let dest = format!("%proj{}", context.load_counter);
            context.load_counter += 1;
            writer.indented(|writer| {
                writer.writeln(&format!(
                    "  {dest} = call {} @{}({} {expr}, {key_value})",
                    declaration.return_ty, declaration.symbol, declaration.params[0]
                ));
            });
            expr = dest;
            ty = result_ty;
        }
        Ok(expr)
    }

    fn load_slot(
        &self,
        slot: String,
        ty: MirType,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<String, MirLlvmTextProbeError> {
        let result = format!("%load{}", context.load_counter);
        context.load_counter += 1;
        let ty = self.llvm_ty(ty)?;
        writer.indented(|writer| {
            writer.writeln(&format!("  {result} = load {ty}, ptr {slot}"));
        });
        Ok(result)
    }

    fn place_ty(&self, place: &MirPlace, context: &FunctionContext) -> Result<MirType, MirLlvmTextProbeError> {
        let mut ty = self.place_base_ty(place, context)?;
        for projection in &place.projections {
            let (_, _, result_ty) = self.projection_declaration_for_context(projection, ty, context)?;
            ty = result_ty;
        }
        Ok(ty)
    }

    fn place_base_ty(&self, place: &MirPlace, context: &FunctionContext) -> Result<MirType, MirLlvmTextProbeError> {
        match place.base {
            MirPlaceBase::Local(id) => context
                .local_tys
                .get(&id)
                .copied()
                .ok_or_else(|| MirLlvmTextProbeError::unsupported(format!("undefined local type l{}", id.0))),
            MirPlaceBase::Temp(id) => context
                .temp_tys
                .get(&id)
                .copied()
                .ok_or_else(|| MirLlvmTextProbeError::unsupported(format!("undefined temp type t{}", id.0))),
        }
    }

    fn constant(&self, constant: &MirConstant) -> Result<String, MirLlvmTextProbeError> {
        match constant {
            MirConstant::Int(value) => Ok(value.to_string()),
            MirConstant::Bool(value) => Ok(if *value { "1" } else { "0" }.to_owned()),
            MirConstant::Unit => Ok("0".to_owned()),
            MirConstant::Float(value) => Ok(format_float(*value)),
            MirConstant::String(symbol) => Ok(format!("inttoptr (i64 {} to ptr)", symbol.0)),
            MirConstant::Nil => Ok("null".to_owned()),
        }
    }

    fn constant_ty(&self, constant: &MirConstant) -> Result<MirType, MirLlvmTextProbeError> {
        let primitive = match constant {
            MirConstant::Int(_) => Primitive::Numerus,
            MirConstant::Float(_) => Primitive::Fractus,
            MirConstant::Bool(_) => Primitive::Bivalens,
            MirConstant::Unit => Primitive::Vacuum,
            MirConstant::String(_) => Primitive::Textus,
            MirConstant::Nil => Primitive::Nihil,
        };
        Ok(MirType::semantic(self.types.primitive(primitive)))
    }

    fn llvm_ty(&self, ty: MirType) -> Result<&'static str, MirLlvmTextProbeError> {
        Ok(self.llvm_scalar(ty)?.ty())
    }

    fn llvm_function_return_ty(&self, ty: MirType) -> Result<&'static str, MirLlvmTextProbeError> {
        self.llvm_ty(ty)
    }

    fn llvm_scalar(&self, ty: MirType) -> Result<LlvmScalar, MirLlvmTextProbeError> {
        match self.types.get(ty.semantic_id()) {
            Type::Primitive(Primitive::Numerus) => Ok(LlvmScalar::I64),
            Type::Primitive(Primitive::Fractus) => Ok(LlvmScalar::F64),
            Type::Primitive(Primitive::Bivalens) => Ok(LlvmScalar::I1),
            Type::Primitive(Primitive::Vacuum) => Ok(LlvmScalar::Void),
            Type::Primitive(
                Primitive::Textus
                | Primitive::Nihil
                | Primitive::Numquam
                | Primitive::Ignotum
                | Primitive::Octeti
                | Primitive::Regex
                | Primitive::Valor,
            ) => Ok(LlvmScalar::Ptr),
            Type::Alias(_, target) => self.llvm_scalar(MirType::semantic(*target)),
            Type::Array(_)
            | Type::Map(_, _)
            | Type::Record(_)
            | Type::Set(_)
            | Type::Option(_)
            | Type::Ref(_, _)
            | Type::Struct(_)
            | Type::Enum(_)
            | Type::Interface(_)
            | Type::Applied(_, _)
            | Type::Union(_) => Ok(LlvmScalar::Ptr),
            Type::Func(_) => Err(MirLlvmTextProbeError::unsupported("function handle ABI")),
            Type::Param(_) | Type::Infer(_) | Type::Error => Err(MirLlvmTextProbeError::unsupported("unresolved type")),
        }
    }

    fn llvm_bin_op(&self, op: MirBinOp, lhs_ty: MirType) -> Result<&'static str, MirLlvmTextProbeError> {
        match (op, self.llvm_scalar(lhs_ty)?) {
            (MirBinOp::Add, LlvmScalar::I64) => Ok("add"),
            (MirBinOp::Sub, LlvmScalar::I64) => Ok("sub"),
            (MirBinOp::Mul, LlvmScalar::I64) => Ok("mul"),
            (MirBinOp::Div, LlvmScalar::I64) => Ok("sdiv"),
            (MirBinOp::Mod, LlvmScalar::I64) => Ok("srem"),
            (MirBinOp::Add, LlvmScalar::F64) => Ok("fadd"),
            (MirBinOp::Sub, LlvmScalar::F64) => Ok("fsub"),
            (MirBinOp::Mul, LlvmScalar::F64) => Ok("fmul"),
            (MirBinOp::Div, LlvmScalar::F64) => Ok("fdiv"),
            (MirBinOp::Mod, LlvmScalar::F64) => Ok("frem"),
            (MirBinOp::Eq, LlvmScalar::I64 | LlvmScalar::I1) => Ok("icmp eq"),
            (MirBinOp::NotEq, LlvmScalar::I64 | LlvmScalar::I1) => Ok("icmp ne"),
            (MirBinOp::Lt, LlvmScalar::I64) => Ok("icmp slt"),
            (MirBinOp::Gt, LlvmScalar::I64) => Ok("icmp sgt"),
            (MirBinOp::LtEq, LlvmScalar::I64) => Ok("icmp sle"),
            (MirBinOp::GtEq, LlvmScalar::I64) => Ok("icmp sge"),
            (MirBinOp::Eq, LlvmScalar::F64) => Ok("fcmp oeq"),
            (MirBinOp::NotEq, LlvmScalar::F64) => Ok("fcmp one"),
            (MirBinOp::Lt, LlvmScalar::F64) => Ok("fcmp olt"),
            (MirBinOp::Gt, LlvmScalar::F64) => Ok("fcmp ogt"),
            (MirBinOp::LtEq, LlvmScalar::F64) => Ok("fcmp ole"),
            (MirBinOp::GtEq, LlvmScalar::F64) => Ok("fcmp oge"),
            (MirBinOp::And, LlvmScalar::I1) => Ok("and"),
            (MirBinOp::Or, LlvmScalar::I1) => Ok("or"),
            _ => Err(MirLlvmTextProbeError::unsupported(format!("binary op {op:?}"))),
        }
    }

    fn llvm_unary_expr(
        &self,
        op: MirUnOp,
        operand_ty: MirType,
        operand: &str,
    ) -> Result<String, MirLlvmTextProbeError> {
        match (op, self.llvm_scalar(operand_ty)?) {
            (MirUnOp::Neg, LlvmScalar::I64) => Ok(format!("sub i64 0, {operand}")),
            (MirUnOp::Neg, LlvmScalar::F64) => Ok(format!("fneg double {operand}")),
            (MirUnOp::Not, LlvmScalar::I1) => Ok(format!("xor i1 {operand}, true")),
            _ => Err(MirLlvmTextProbeError::unsupported(format!("unary op {op:?}"))),
        }
    }

    fn function_name(&self, function: &MirFunction) -> String {
        function
            .name
            .map(|symbol| sanitize_name(self.interner.resolve(symbol)))
            .unwrap_or_else(|| format!("f{}", function.id.0))
    }

    fn callee_function(&self, callee: &MirCallee) -> Result<&MirFunction, MirLlvmTextProbeError> {
        match callee {
            MirCallee::Function(id) => self
                .program
                .functions
                .iter()
                .find(|function| function.id == *id)
                .ok_or_else(|| MirLlvmTextProbeError::unsupported(format!("unknown function f{}", id.0))),
            MirCallee::Definition(def_id) => self
                .program
                .functions
                .iter()
                .find(|function| function.source == Some(*def_id))
                .ok_or_else(|| MirLlvmTextProbeError::unsupported("external definition call")),
            MirCallee::Value(_) => Err(MirLlvmTextProbeError::unsupported("value callee")),
        }
    }

    fn external_declarations(&self) -> Result<Vec<ExternalDecl>, MirLlvmTextProbeError> {
        let mut declarations = BTreeMap::new();
        for function in &self.program.functions {
            let mut context = FunctionContext {
                values: FxHashMap::default(),
                value_tys: FxHashMap::default(),
                local_tys: function
                    .locals
                    .iter()
                    .map(|local| (local.id, local.ty))
                    .chain(function.params.iter().map(|param| (param.local, param.ty)))
                    .collect(),
                temp_tys: function
                    .temps
                    .iter()
                    .map(|temp| (temp.id, temp.ty))
                    .collect(),
                load_counter: 0,
            };
            for block in &function.blocks {
                for stmt in &block.statements {
                    match &stmt.kind {
                        MirStmtKind::Assign { place, value } => {
                            self.collect_value_projection_declarations(value, &context, &mut declarations)?;
                            self.collect_value_option_declarations(value, &context, &mut declarations)?;
                            self.collect_place_projection_set_declaration(place, &context, &mut declarations)?;
                            context.value_tys.insert(value.id, value.ty);
                        }
                        MirStmtKind::RuntimeCall { call, .. } => {
                            for arg in &call.args {
                                self.collect_operand_projection_declarations(arg, &context, &mut declarations)?;
                            }
                            let declaration = self.runtime_declaration(call, &context)?;
                            declarations.insert(declaration.symbol.clone(), declaration);
                        }
                        MirStmtKind::Construct { aggregate, .. } => {
                            for operand in aggregate_operands(&aggregate.fields)? {
                                self.collect_operand_projection_declarations(operand, &context, &mut declarations)?;
                            }
                            let declaration = self.aggregate_declaration(aggregate, &context)?;
                            declarations.insert(declaration.symbol.clone(), declaration);
                        }
                        MirStmtKind::Call { args, .. } => {
                            for arg in args {
                                self.collect_operand_projection_declarations(arg, &context, &mut declarations)?;
                            }
                        }
                    }
                }
                self.collect_terminator_projection_declarations(&block.terminator, &context, &mut declarations)?;
            }
        }
        Ok(declarations.into_values().collect())
    }

    fn collect_terminator_projection_declarations(
        &self,
        terminator: &MirTerminator,
        context: &FunctionContext,
        declarations: &mut BTreeMap<String, ExternalDecl>,
    ) -> Result<(), MirLlvmTextProbeError> {
        match &terminator.kind {
            MirTerminatorKind::Return(Some(operand)) | MirTerminatorKind::ReturnError(operand) => {
                self.collect_operand_projection_declarations(operand, context, declarations)
            }
            MirTerminatorKind::Branch { condition, .. } => {
                self.collect_operand_projection_declarations(condition, context, declarations)
            }
            MirTerminatorKind::TryCall { args, .. } => {
                for arg in args {
                    self.collect_operand_projection_declarations(arg, context, declarations)?;
                }
                Ok(())
            }
            MirTerminatorKind::Switch { value, .. } => {
                self.collect_operand_projection_declarations(value, context, declarations)
            }
            MirTerminatorKind::Return(None) | MirTerminatorKind::Goto(_) | MirTerminatorKind::Unreachable => Ok(()),
        }
    }

    fn collect_value_projection_declarations(
        &self,
        value: &MirValue,
        context: &FunctionContext,
        declarations: &mut BTreeMap<String, ExternalDecl>,
    ) -> Result<(), MirLlvmTextProbeError> {
        match &value.kind {
            MirValueKind::Operand(operand) => {
                self.collect_operand_projection_declarations(operand, context, declarations)
            }
            MirValueKind::Unary { operand, .. } => {
                self.collect_operand_projection_declarations(operand, context, declarations)
            }
            MirValueKind::Binary { lhs, rhs, .. } => {
                self.collect_operand_projection_declarations(lhs, context, declarations)?;
                self.collect_operand_projection_declarations(rhs, context, declarations)
            }
            MirValueKind::Option(_) => Ok(()),
        }
    }

    fn collect_value_option_declarations(
        &self,
        value: &MirValue,
        context: &FunctionContext,
        declarations: &mut BTreeMap<String, ExternalDecl>,
    ) -> Result<(), MirLlvmTextProbeError> {
        if let MirValueKind::Option(op) = &value.kind {
            let declaration = self.option_declaration(op, value.ty, context)?;
            declarations.insert(declaration.symbol.clone(), declaration);
        }
        Ok(())
    }

    fn collect_operand_projection_declarations(
        &self,
        operand: &MirOperand,
        context: &FunctionContext,
        declarations: &mut BTreeMap<String, ExternalDecl>,
    ) -> Result<(), MirLlvmTextProbeError> {
        match operand {
            MirOperand::Place(place) => self.collect_place_projection_declarations(place, context, declarations),
            MirOperand::Temp(_) | MirOperand::Value(_) | MirOperand::Constant(_) => Ok(()),
        }
    }

    fn collect_place_projection_declarations(
        &self,
        place: &MirPlace,
        context: &FunctionContext,
        declarations: &mut BTreeMap<String, ExternalDecl>,
    ) -> Result<(), MirLlvmTextProbeError> {
        let mut ty = self.place_base_ty(place, context)?;
        for projection in &place.projections {
            let (declaration, _, result_ty) = self.projection_declaration_for_context(projection, ty, context)?;
            declarations.insert(declaration.symbol.clone(), declaration);
            ty = result_ty;
        }
        Ok(())
    }

    fn collect_place_projection_set_declaration(
        &self,
        place: &MirPlace,
        context: &FunctionContext,
        declarations: &mut BTreeMap<String, ExternalDecl>,
    ) -> Result<(), MirLlvmTextProbeError> {
        let Some((last, parent)) = place.projections.split_last() else {
            return Ok(());
        };
        if !parent.is_empty() {
            return Err(MirLlvmTextProbeError::unsupported("nested place projection set"));
        }
        let base_ty = self.place_base_ty(place, context)?;
        let value_ty = self.place_ty(place, context)?;
        let (declaration, _) = self.projection_set_declaration(last, base_ty, value_ty, context)?;
        declarations.insert(declaration.symbol.clone(), declaration);
        Ok(())
    }

    fn runtime_declaration(
        &self,
        call: &MirRuntimeCall,
        context: &FunctionContext,
    ) -> Result<ExternalDecl, MirLlvmTextProbeError> {
        if matches!(call.intrinsic, MirIntrinsic::Provider(_)) {
            return Err(MirLlvmTextProbeError::unsupported("provider runtime call"));
        }
        let params = call
            .args
            .iter()
            .map(|arg| self.llvm_ty(self.operand_ty(arg, context)?))
            .collect::<Result<Vec<_>, _>>()?;
        let return_ty = match call.intrinsic {
            MirIntrinsic::Diagnostic(_) | MirIntrinsic::Assert | MirIntrinsic::Panic => "void",
            _ => self.llvm_ty(call.return_ty)?,
        };
        let symbol = runtime_symbol(&call.intrinsic, &params, return_ty)?;
        Ok(ExternalDecl { symbol, return_ty, params })
    }

    fn option_declaration(
        &self,
        op: &MirOptionOp,
        result_ty: MirType,
        context: &FunctionContext,
    ) -> Result<ExternalDecl, MirLlvmTextProbeError> {
        match op {
            MirOptionOp::None => {
                let payload = self.option_payload_ty(result_ty)?;
                let payload_ty = self.llvm_ty(payload)?;
                Ok(ExternalDecl { symbol: option_symbol("none", payload_ty), return_ty: "ptr", params: Vec::new() })
            }
            MirOptionOp::Some(value) => {
                let payload = self.option_payload_ty(result_ty)?;
                let payload_ty = self.llvm_ty(payload)?;
                let value_ty = self.llvm_ty(self.operand_ty(value, context)?)?;
                if payload_ty != value_ty {
                    return Err(MirLlvmTextProbeError::unsupported("option some payload type"));
                }
                Ok(ExternalDecl {
                    symbol: option_symbol("some", payload_ty),
                    return_ty: "ptr",
                    params: vec![payload_ty],
                })
            }
            MirOptionOp::IsNil(_) => {
                Ok(ExternalDecl { symbol: "__faber_option_is_nil".to_owned(), return_ty: "i1", params: vec!["ptr"] })
            }
            MirOptionOp::IsNonNil(_) => Ok(ExternalDecl {
                symbol: "__faber_option_is_non_nil".to_owned(),
                return_ty: "i1",
                params: vec!["ptr"],
            }),
            MirOptionOp::Unwrap { value, .. } => {
                let payload = self.option_operand_payload_ty(value, context)?;
                let payload_ty = self.llvm_ty(payload)?;
                Ok(ExternalDecl {
                    symbol: option_symbol("unwrap", payload_ty),
                    return_ty: payload_ty,
                    params: vec!["ptr"],
                })
            }
            MirOptionOp::Coalesce { value, fallback } => {
                let payload = self.option_operand_payload_ty(value, context)?;
                let payload_ty = self.llvm_ty(payload)?;
                let fallback_ty = self.llvm_ty(self.operand_ty(fallback, context)?)?;
                let result_ty = self.llvm_ty(result_ty)?;
                if payload_ty != fallback_ty || payload_ty != result_ty {
                    return Err(MirLlvmTextProbeError::unsupported("option coalesce payload type"));
                }
                Ok(ExternalDecl {
                    symbol: option_symbol("coalesce", payload_ty),
                    return_ty: payload_ty,
                    params: vec!["ptr", payload_ty],
                })
            }
            MirOptionOp::Chain { .. } => Err(MirLlvmTextProbeError::unsupported("option chain value")),
        }
    }

    fn option_operand_payload_ty(
        &self,
        operand: &MirOperand,
        context: &FunctionContext,
    ) -> Result<MirType, MirLlvmTextProbeError> {
        self.option_payload_ty(self.operand_ty(operand, context)?)
    }

    fn option_payload_ty(&self, ty: MirType) -> Result<MirType, MirLlvmTextProbeError> {
        match self.types.get(ty.semantic_id()) {
            Type::Option(inner) => Ok(MirType::semantic(*inner)),
            Type::Alias(_, target) => self.option_payload_ty(MirType::semantic(*target)),
            other => Err(MirLlvmTextProbeError::unsupported(format!("option type {other:?}"))),
        }
    }

    fn aggregate_declaration(
        &self,
        aggregate: &MirAggregate,
        context: &FunctionContext,
    ) -> Result<ExternalDecl, MirLlvmTextProbeError> {
        if self.llvm_scalar(aggregate.ty)? != LlvmScalar::Ptr {
            return Err(MirLlvmTextProbeError::unsupported("non-handle aggregate construct"));
        }
        let operand_tys = aggregate_operands(&aggregate.fields)?
            .iter()
            .map(|operand| self.llvm_ty(self.operand_ty(operand, context)?))
            .collect::<Result<Vec<_>, _>>()?;
        let mut params = Vec::new();
        if aggregate_definition_id(&aggregate.kind).is_some() {
            params.push("i64");
        }
        params.extend(operand_tys.iter().copied());
        Ok(ExternalDecl { symbol: aggregate_symbol(&aggregate.kind, &operand_tys), return_ty: "ptr", params })
    }

    fn projection_declaration(
        &self,
        projection: &MirProjection,
        base_ty: MirType,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(ExternalDecl, String, MirType), MirLlvmTextProbeError> {
        let (declaration, key_ty, result_ty) = self.projection_declaration_for_context(projection, base_ty, context)?;
        let key = match projection {
            MirProjection::Field(field) | MirProjection::VariantField { field, .. } => {
                format!("{key_ty} {}", field.0)
            }
            MirProjection::Index(index) => {
                let value = self.operand(index, context, writer)?;
                format!("{key_ty} {value}")
            }
        };
        Ok((declaration, key, result_ty))
    }

    fn projection_declaration_for_context(
        &self,
        projection: &MirProjection,
        base_ty: MirType,
        context: &FunctionContext,
    ) -> Result<(ExternalDecl, &'static str, MirType), MirLlvmTextProbeError> {
        let (kind, key_ty, result_ty) = match projection {
            MirProjection::Field(field) => ("field", "i64", self.project_field_ty(base_ty, *field)?),
            MirProjection::VariantField { variant, field } => {
                ("variant_field", "i64", self.project_variant_field_ty(*variant, *field)?)
            }
            MirProjection::Index(index) => (
                "index",
                self.llvm_ty(self.operand_ty(index, context)?)?,
                self.project_index_ty(base_ty)?,
            ),
        };
        let result_ty_llvm = self.llvm_ty(result_ty)?;
        Ok((
            ExternalDecl {
                symbol: projection_symbol(kind, key_ty, result_ty_llvm),
                return_ty: result_ty_llvm,
                params: vec!["ptr", key_ty],
            },
            key_ty,
            result_ty,
        ))
    }

    fn projection_set_call_parts(
        &self,
        place: &MirPlace,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(String, ExternalDecl, String), MirLlvmTextProbeError> {
        let Some((last, parent)) = place.projections.split_last() else {
            return Err(MirLlvmTextProbeError::unsupported("empty projection set"));
        };
        if !parent.is_empty() {
            return Err(MirLlvmTextProbeError::unsupported("nested place projection set"));
        }
        let base_ty = self.place_base_ty(place, context)?;
        let base = self.load_slot(place_base_slot(place)?, base_ty, context, writer)?;
        let value_ty = self.place_ty(place, context)?;
        let (declaration, key_ty) = self.projection_set_declaration(last, base_ty, value_ty, context)?;
        let key = match last {
            MirProjection::Field(field) | MirProjection::VariantField { field, .. } => {
                format!("{key_ty} {}", field.0)
            }
            MirProjection::Index(index) => {
                let value = self.operand(index, context, writer)?;
                format!("{key_ty} {value}")
            }
        };
        Ok((format!("ptr {base}"), declaration, key))
    }

    fn projection_set_declaration(
        &self,
        projection: &MirProjection,
        base_ty: MirType,
        value_ty: MirType,
        context: &FunctionContext,
    ) -> Result<(ExternalDecl, &'static str), MirLlvmTextProbeError> {
        let (kind, key_ty, expected_value_ty) = match projection {
            MirProjection::Field(field) => ("set_field", "i64", self.project_field_ty(base_ty, *field)?),
            MirProjection::VariantField { variant, field } => {
                ("set_variant_field", "i64", self.project_variant_field_ty(*variant, *field)?)
            }
            MirProjection::Index(index) => (
                "set_index",
                self.llvm_ty(self.operand_ty(index, context)?)?,
                self.project_index_ty(base_ty)?,
            ),
        };
        if self.llvm_ty(value_ty)? != self.llvm_ty(expected_value_ty)? {
            return Err(MirLlvmTextProbeError::unsupported("projection set value type"));
        }
        let value_ty = self.llvm_ty(value_ty)?;
        Ok((
            ExternalDecl {
                symbol: projection_set_symbol(kind, key_ty, value_ty),
                return_ty: "void",
                params: vec!["ptr", key_ty, value_ty],
            },
            key_ty,
        ))
    }

    fn project_field_ty(
        &self,
        base_ty: MirType,
        field: crate::lexer::Symbol,
    ) -> Result<MirType, MirLlvmTextProbeError> {
        match self.types.get(base_ty.semantic_id()) {
            Type::Struct(def_id) => self
                .validation
                .struct_fields
                .get(def_id)
                .and_then(|fields| fields.get(&field))
                .copied()
                .ok_or_else(|| MirLlvmTextProbeError::unsupported("struct field projection metadata")),
            Type::Record(fields) => fields
                .get(&field)
                .copied()
                .map(MirType::semantic)
                .ok_or_else(|| MirLlvmTextProbeError::unsupported("record field projection metadata")),
            Type::Alias(_, target) => self.project_field_ty(MirType::semantic(*target), field),
            _ => Err(MirLlvmTextProbeError::unsupported("field projection base")),
        }
    }

    fn project_variant_field_ty(
        &self,
        variant: DefId,
        field: crate::lexer::Symbol,
    ) -> Result<MirType, MirLlvmTextProbeError> {
        self.validation
            .variant_fields
            .get(&variant)
            .and_then(|fields| fields.get(&field))
            .copied()
            .ok_or_else(|| MirLlvmTextProbeError::unsupported("variant field projection metadata"))
    }

    fn project_index_ty(&self, base_ty: MirType) -> Result<MirType, MirLlvmTextProbeError> {
        match self.types.get(base_ty.semantic_id()) {
            Type::Array(inner) => Ok(MirType::semantic(*inner)),
            Type::Map(_, value) => Ok(MirType::semantic(*value)),
            Type::Primitive(Primitive::Textus) => Ok(MirType::semantic(self.types.primitive(Primitive::Textus))),
            Type::Alias(_, target) => self.project_index_ty(MirType::semantic(*target)),
            _ => Err(MirLlvmTextProbeError::unsupported("index projection base")),
        }
    }
}

impl LlvmScalar {
    fn ty(self) -> &'static str {
        match self {
            LlvmScalar::I1 => "i1",
            LlvmScalar::I64 => "i64",
            LlvmScalar::F64 => "double",
            LlvmScalar::Ptr => "ptr",
            LlvmScalar::Void => "void",
        }
    }
}

fn runtime_symbol(
    intrinsic: &MirIntrinsic,
    params: &[&'static str],
    return_ty: &'static str,
) -> Result<String, MirLlvmTextProbeError> {
    let name = match intrinsic {
        MirIntrinsic::Diagnostic(kind) => format!("diagnostic_{}", diagnostic_name(*kind)),
        MirIntrinsic::Assert => "assert".to_owned(),
        MirIntrinsic::FormatString { .. } => "format".to_owned(),
        MirIntrinsic::Convert(conversion) => format!("convert_{}", conversion_flavor_name(conversion.flavor)),
        MirIntrinsic::Collection(op) => collection_name(*op).to_owned(),
        MirIntrinsic::Panic => "panic".to_owned(),
        MirIntrinsic::Provider(_) => return Err(MirLlvmTextProbeError::unsupported("provider runtime call")),
    };
    let mut symbol = format!("__faber_runtime_{}_{}", name, params.len());
    for param in params {
        symbol.push('_');
        symbol.push_str(abi_name(param));
    }
    if return_ty != "void" {
        symbol.push_str("_to_");
        symbol.push_str(abi_name(return_ty));
    }
    Ok(symbol)
}

fn diagnostic_name(kind: MirDiagnosticKind) -> &'static str {
    match kind {
        MirDiagnosticKind::Nota => "nota",
        MirDiagnosticKind::Vide => "vide",
        MirDiagnosticKind::Mone => "mone",
        MirDiagnosticKind::Scribe => "scribe",
    }
}

fn conversion_flavor_name(flavor: MirConversionFlavor) -> &'static str {
    match flavor {
        MirConversionFlavor::Cast => "cast",
        MirConversionFlavor::Runtime => "runtime",
    }
}

fn collection_name(op: MirCollectionOp) -> &'static str {
    match op {
        MirCollectionOp::Append => "append",
        MirCollectionOp::AppendImmutable => "append_immutable",
        MirCollectionOp::Index => "index",
        MirCollectionOp::Length => "length",
        MirCollectionOp::Contains => "contains",
        MirCollectionOp::First => "first",
        MirCollectionOp::Last => "last",
        MirCollectionOp::Reverse => "reverse",
        MirCollectionOp::ReverseInPlace => "reverse_in_place",
        MirCollectionOp::Sort => "sort",
    }
}

fn abi_name(ty: &str) -> &'static str {
    match ty {
        "i1" => "i1",
        "i64" => "i64",
        "double" => "f64",
        "ptr" => "ptr",
        "void" => "void",
        _ => "unknown",
    }
}

fn aggregate_symbol(kind: &MirAggregateKind, params: &[&'static str]) -> String {
    let kind = match kind {
        MirAggregateKind::Tuple => "tuple",
        MirAggregateKind::Array => "array",
        MirAggregateKind::Map => "map",
        MirAggregateKind::Set => "set",
        MirAggregateKind::Struct(_) => "struct",
        MirAggregateKind::EnumVariant(_) => "variant",
    };
    let suffix = if params.is_empty() {
        "0".to_owned()
    } else {
        let args = params
            .iter()
            .map(|param| abi_name(param))
            .collect::<Vec<_>>()
            .join("_");
        format!("{}_{}", params.len(), args)
    };
    format!("__faber_aggregate_{kind}_{suffix}")
}

fn projection_symbol(kind: &str, key_ty: &str, result_ty: &str) -> String {
    format!("__faber_aggregate_{kind}_{}_to_{}", abi_name(key_ty), abi_name(result_ty))
}

fn projection_set_symbol(kind: &str, key_ty: &str, value_ty: &str) -> String {
    format!("__faber_aggregate_{kind}_{}_{}", abi_name(key_ty), abi_name(value_ty))
}

fn option_symbol(kind: &str, payload_ty: &str) -> String {
    format!("__faber_option_{kind}_{}", abi_name(payload_ty))
}

fn aggregate_definition_id(kind: &MirAggregateKind) -> Option<DefId> {
    match kind {
        MirAggregateKind::Struct(def_id) | MirAggregateKind::EnumVariant(def_id) => Some(*def_id),
        _ => None,
    }
}

fn aggregate_operands(fields: &MirAggregateFields) -> Result<Vec<&MirOperand>, MirLlvmTextProbeError> {
    match fields {
        MirAggregateFields::Ordered(items) => items
            .iter()
            .map(|item| match item {
                MirAggregateItem::Operand(operand) => Ok(operand),
                MirAggregateItem::Spread(_) => Err(MirLlvmTextProbeError::unsupported("aggregate spread")),
            })
            .collect(),
        MirAggregateFields::Named(items) => Ok(items.iter().map(|item| &item.value).collect()),
        MirAggregateFields::Keyed(items) => Ok(items
            .iter()
            .flat_map(|item| [&item.key, &item.value])
            .collect()),
    }
}

fn local_name(id: MirLocalId) -> String {
    format!("l{}", id.0)
}

fn local_slot(id: MirLocalId) -> String {
    format!("%l{}.addr", id.0)
}

fn temp_slot(id: MirTempId) -> String {
    format!("%t{}.addr", id.0)
}

fn place_base_slot(place: &MirPlace) -> Result<String, MirLlvmTextProbeError> {
    match place.base {
        MirPlaceBase::Local(id) => Ok(local_slot(id)),
        MirPlaceBase::Temp(id) => Ok(temp_slot(id)),
    }
}

fn place_slot(place: &MirPlace) -> Result<String, MirLlvmTextProbeError> {
    if !place.projections.is_empty() {
        return Err(MirLlvmTextProbeError::unsupported("place projection"));
    }
    match place.base {
        MirPlaceBase::Local(id) => Ok(local_slot(id)),
        MirPlaceBase::Temp(id) => Ok(temp_slot(id)),
    }
}

fn block_label(id: MirBlockId) -> String {
    format!("bb{}", id.0)
}

fn sanitize_name(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn format_float(value: f64) -> String {
    if value.is_finite() && value.fract() == 0.0 {
        format!("{value:.1}")
    } else {
        value.to_string()
    }
}

fn terminator_kind_name(kind: &MirTerminatorKind) -> &'static str {
    match kind {
        MirTerminatorKind::Return(_) => "return",
        MirTerminatorKind::ReturnError(_) => "return_error",
        MirTerminatorKind::TryCall { .. } => "try_call",
        MirTerminatorKind::Goto(_) => "goto",
        MirTerminatorKind::Branch { .. } => "branch",
        MirTerminatorKind::Switch { .. } => "switch",
        MirTerminatorKind::Unreachable => "unreachable",
    }
}

#[cfg(test)]
#[path = "llvm_text_test.rs"]
mod tests;
