use crate::codegen::CodeWriter;
use crate::lexer::Interner;
use crate::mir::*;
use crate::semantic::{Primitive, Type, TypeTable};
use rustc_hash::{FxHashMap, FxHashSet};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MirRustProbeError {
    pub message: String,
}

impl MirRustProbeError {
    fn unsupported(shape: impl Into<String>) -> Self {
        Self { message: format!("MIR-to-Rust unsupported: {}", shape.into()) }
    }
}

impl std::fmt::Display for MirRustProbeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for MirRustProbeError {}

/// Emit deliberately temporary Rust from already-validated MIR.
///
/// TARGET: Phase 9 MIR Rust probe. This is not the permanent Rust backend surface.
pub fn emit_rust_probe(
    program: &MirProgram,
    types: &TypeTable,
    interner: &Interner,
) -> Result<String, MirRustProbeError> {
    RustProbe::new(program, types, interner).emit_program()
}

struct RustProbe<'a> {
    program: &'a MirProgram,
    types: &'a TypeTable,
    interner: &'a Interner,
    functions_by_id: FxHashMap<MirFunctionId, &'a MirFunction>,
    functions_by_def: FxHashMap<crate::hir::DefId, &'a MirFunction>,
}

struct FunctionProbe<'a, 'p> {
    probe: &'p RustProbe<'a>,
    function: &'a MirFunction,
    param_locals: FxHashSet<MirLocalId>,
    value_exprs: FxHashMap<MirValueId, String>,
}

impl<'a> RustProbe<'a> {
    fn new(program: &'a MirProgram, types: &'a TypeTable, interner: &'a Interner) -> Self {
        let mut functions_by_id = FxHashMap::default();
        let mut functions_by_def = FxHashMap::default();
        for function in &program.functions {
            functions_by_id.insert(function.id, function);
            if let Some(def_id) = function.source {
                functions_by_def.insert(def_id, function);
            }
        }
        Self { program, types, interner, functions_by_id, functions_by_def }
    }

    fn emit_program(&self) -> Result<String, MirRustProbeError> {
        let mut w = CodeWriter::new();
        w.writeln("// Generated by radix MIR Rust probe - temporary Phase 9 artifact.");
        w.writeln("#![allow(dead_code)]");
        w.writeln("#![allow(unused_variables)]");
        w.writeln("#![allow(unused_mut)]");
        w.newline();

        for function in &self.program.functions {
            self.emit_function(function, &mut w)?;
            w.newline();
        }

        Ok(w.finish())
    }

    fn emit_function(&self, function: &'a MirFunction, w: &mut CodeWriter) -> Result<(), MirRustProbeError> {
        let mut probe = FunctionProbe {
            probe: self,
            function,
            param_locals: function.params.iter().map(|param| param.local).collect(),
            value_exprs: FxHashMap::default(),
        };

        w.write("pub fn ");
        w.write(&function_name(function.id));
        w.write("(");
        for (index, param) in function.params.iter().enumerate() {
            if index > 0 {
                w.write(", ");
            }
            w.write("mut ");
            w.write(&local_name(param.local));
            w.write(": ");
            w.write(&self.rust_type(param.ty)?);
        }
        w.write(") -> ");
        w.write(&self.rust_type(function.return_ty)?);
        w.writeln(" {");
        w.indent();
        w.writeln("#[derive(Clone, Copy)]");
        w.writeln("enum __FaberBlock {");
        w.indent();
        for block in &function.blocks {
            w.writeln(&format!("{},", block_variant(block.id)));
        }
        w.dedent();
        w.writeln("}");
        w.write("let mut __faber_block = __FaberBlock::");
        let entry = function
            .blocks
            .first()
            .map(|block| block.id)
            .unwrap_or(MirBlockId(0));
        w.write(&block_variant(entry));
        w.writeln(";");
        for local in &function.locals {
            if probe.param_locals.contains(&local.id) {
                continue;
            }
            w.writeln(&format!(
                "let mut {}: {} = {};",
                local_name(local.id),
                self.rust_type(local.ty)?,
                self.default_value(local.ty)?
            ));
        }
        for temp in &function.temps {
            w.writeln(&format!(
                "let mut {}: {} = {};",
                temp_name(temp.id),
                self.rust_type(temp.ty)?,
                self.default_value(temp.ty)?
            ));
        }
        w.writeln("loop {");
        w.indent();
        w.writeln("match __faber_block {");
        w.indent();
        for block in &function.blocks {
            w.write("__FaberBlock::");
            w.write(&block_variant(block.id));
            w.writeln(" => {");
            w.indent();
            probe.emit_block(block, w)?;
            w.dedent();
            w.writeln("}");
        }
        w.dedent();
        w.writeln("}");
        w.dedent();
        w.writeln("}");
        w.dedent();
        w.writeln("}");
        Ok(())
    }

    fn rust_type(&self, ty: MirType) -> Result<String, MirRustProbeError> {
        match self.types.get(ty.semantic_id()) {
            Type::Primitive(Primitive::Textus) => Ok("String".to_owned()),
            Type::Primitive(Primitive::Numerus) => Ok("i64".to_owned()),
            Type::Primitive(Primitive::Fractus) => Ok("f64".to_owned()),
            Type::Primitive(Primitive::Bivalens) => Ok("bool".to_owned()),
            Type::Primitive(Primitive::Vacuum | Primitive::Nihil) => Ok("()".to_owned()),
            Type::Alias(_, inner) => self.rust_type(MirType::semantic(*inner)),
            other => Err(MirRustProbeError::unsupported(format!("type {other:?}"))),
        }
    }

    fn default_value(&self, ty: MirType) -> Result<String, MirRustProbeError> {
        match self.types.get(ty.semantic_id()) {
            Type::Primitive(Primitive::Textus) => Ok("String::new()".to_owned()),
            Type::Primitive(Primitive::Numerus) => Ok("0".to_owned()),
            Type::Primitive(Primitive::Fractus) => Ok("0.0".to_owned()),
            Type::Primitive(Primitive::Bivalens) => Ok("false".to_owned()),
            Type::Primitive(Primitive::Vacuum | Primitive::Nihil) => Ok("()".to_owned()),
            Type::Alias(_, inner) => self.default_value(MirType::semantic(*inner)),
            other => Err(MirRustProbeError::unsupported(format!("default value for type {other:?}"))),
        }
    }
}

impl FunctionProbe<'_, '_> {
    fn emit_block(&mut self, block: &MirBlock, w: &mut CodeWriter) -> Result<(), MirRustProbeError> {
        for stmt in &block.statements {
            self.emit_stmt(stmt, w)?;
        }
        self.emit_terminator(&block.terminator, w)
    }

    fn emit_stmt(&mut self, stmt: &MirStmt, w: &mut CodeWriter) -> Result<(), MirRustProbeError> {
        match &stmt.kind {
            MirStmtKind::Assign { place, value } => {
                let expr = self.value_expr(value)?;
                self.value_exprs.insert(value.id, expr.clone());
                w.writeln(&format!("{} = {};", self.place_expr(place)?, expr));
                Ok(())
            }
            MirStmtKind::Call { destination, callee, args } => {
                let expr = self.call_expr(callee, args)?;
                if let Some(destination) = destination {
                    w.writeln(&format!("{} = {};", self.place_expr(destination)?, expr));
                } else {
                    w.writeln(&format!("{expr};"));
                }
                Ok(())
            }
            MirStmtKind::RuntimeCall { call, .. } => {
                Err(MirRustProbeError::unsupported(format!("runtime_call {:?}", call.intrinsic)))
            }
            MirStmtKind::Construct { aggregate, .. } => {
                Err(MirRustProbeError::unsupported(format!("construct {:?}", aggregate.kind)))
            }
        }
    }

    fn emit_terminator(&mut self, terminator: &MirTerminator, w: &mut CodeWriter) -> Result<(), MirRustProbeError> {
        match &terminator.kind {
            MirTerminatorKind::Return(None) => {
                w.writeln("return;");
                Ok(())
            }
            MirTerminatorKind::Return(Some(value)) => {
                w.writeln(&format!("return {};", self.operand_expr(value, Some(self.function.return_ty))?));
                Ok(())
            }
            MirTerminatorKind::Goto(target) => {
                w.writeln(&format!("__faber_block = __FaberBlock::{};", block_variant(*target)));
                w.writeln("continue;");
                Ok(())
            }
            MirTerminatorKind::Branch { condition, then_block, else_block } => {
                let condition = self.operand_expr(condition, None)?;
                w.writeln(&format!("if {condition} {{"));
                w.indented(|w| {
                    w.writeln(&format!("__faber_block = __FaberBlock::{};", block_variant(*then_block)));
                });
                w.writeln("} else {");
                w.indented(|w| {
                    w.writeln(&format!("__faber_block = __FaberBlock::{};", block_variant(*else_block)));
                });
                w.writeln("}");
                w.writeln("continue;");
                Ok(())
            }
            MirTerminatorKind::Unreachable => {
                w.writeln("unreachable!();");
                Ok(())
            }
            MirTerminatorKind::ReturnError(_) => Err(MirRustProbeError::unsupported("return_error")),
            MirTerminatorKind::TryCall { .. } => Err(MirRustProbeError::unsupported("try_call")),
            MirTerminatorKind::Switch { .. } => Err(MirRustProbeError::unsupported("switch")),
        }
    }

    fn value_expr(&mut self, value: &MirValue) -> Result<String, MirRustProbeError> {
        match &value.kind {
            MirValueKind::Operand(operand) => self.operand_expr(operand, Some(value.ty)),
            MirValueKind::Unary { op, operand } => {
                let operand = self.operand_expr(operand, Some(value.ty))?;
                let expr = match op {
                    MirUnOp::Neg => format!("(-{operand})"),
                    MirUnOp::Not => format!("(!{operand})"),
                    MirUnOp::BitNot => format!("(!{operand})"),
                    MirUnOp::IsNil | MirUnOp::IsNonNil => {
                        return Err(MirRustProbeError::unsupported(format!("unary {op:?}")));
                    }
                };
                Ok(expr)
            }
            MirValueKind::Binary { op, lhs, rhs } => self.binary_expr(*op, lhs, rhs, value.ty),
            MirValueKind::Option(op) => Err(MirRustProbeError::unsupported(format!("option {op:?}"))),
        }
    }

    fn binary_expr(
        &mut self,
        op: MirBinOp,
        lhs: &MirOperand,
        rhs: &MirOperand,
        result_ty: MirType,
    ) -> Result<String, MirRustProbeError> {
        if matches!(op, MirBinOp::Coalesce) {
            return Err(MirRustProbeError::unsupported("binary coalesce"));
        }

        let textus = self.probe.types.primitive(Primitive::Textus);
        if matches!(op, MirBinOp::Add) && result_ty.semantic_id() == textus {
            let lhs = self.operand_expr(lhs, Some(result_ty))?;
            let rhs = self.operand_expr(rhs, Some(result_ty))?;
            return Ok(format!("format!(\"{{}}{{}}\", {lhs}, {rhs})"));
        }

        let expected = if result_ty.semantic_id() == self.probe.types.primitive(Primitive::Fractus) {
            Some(result_ty)
        } else {
            None
        };
        let lhs = self.operand_expr(lhs, expected)?;
        let rhs = self.operand_expr(rhs, expected)?;
        let op = match op {
            MirBinOp::Add => "+",
            MirBinOp::Sub => "-",
            MirBinOp::Mul => "*",
            MirBinOp::Div => "/",
            MirBinOp::Mod => "%",
            MirBinOp::Eq => "==",
            MirBinOp::NotEq => "!=",
            MirBinOp::Lt => "<",
            MirBinOp::Gt => ">",
            MirBinOp::LtEq => "<=",
            MirBinOp::GtEq => ">=",
            MirBinOp::And => "&&",
            MirBinOp::Or => "||",
            MirBinOp::BitAnd => "&",
            MirBinOp::BitOr => "|",
            MirBinOp::BitXor => "^",
            MirBinOp::Shl => "<<",
            MirBinOp::Shr => ">>",
            MirBinOp::Coalesce => unreachable!(),
        };
        Ok(format!("({lhs} {op} {rhs})"))
    }

    fn operand_expr(&mut self, operand: &MirOperand, expected: Option<MirType>) -> Result<String, MirRustProbeError> {
        match operand {
            MirOperand::Place(place) => Ok(self.place_expr(place)?),
            MirOperand::Temp(id) => Ok(temp_name(*id)),
            MirOperand::Value(id) => self
                .value_exprs
                .get(id)
                .cloned()
                .ok_or_else(|| MirRustProbeError::unsupported(format!("value operand v{}", id.0))),
            MirOperand::Constant(constant) => self.constant_expr(constant, expected),
        }
    }

    fn constant_expr(&self, constant: &MirConstant, expected: Option<MirType>) -> Result<String, MirRustProbeError> {
        let fractus = self.probe.types.primitive(Primitive::Fractus);
        match constant {
            MirConstant::Int(value) if expected.is_some_and(|ty| ty.semantic_id() == fractus) => {
                Ok(format!("{value} as f64"))
            }
            MirConstant::Int(value) => Ok(value.to_string()),
            MirConstant::Float(value) => Ok(float_literal(*value)),
            MirConstant::String(symbol) => {
                Ok(format!("String::from({})", quoted(self.probe.interner.resolve(*symbol))))
            }
            MirConstant::Bool(value) => Ok(value.to_string()),
            MirConstant::Nil | MirConstant::Unit => Ok("()".to_owned()),
        }
    }

    fn place_expr(&self, place: &MirPlace) -> Result<String, MirRustProbeError> {
        if !place.projections.is_empty() {
            return Err(MirRustProbeError::unsupported(format!(
                "place projection {:?}",
                place.projections
            )));
        }
        match place.base {
            MirPlaceBase::Local(id) => Ok(local_name(id)),
            MirPlaceBase::Temp(id) => Ok(temp_name(id)),
        }
    }

    fn call_expr(&mut self, callee: &MirCallee, args: &[MirOperand]) -> Result<String, MirRustProbeError> {
        let function = match callee {
            MirCallee::Function(id) => self.probe.functions_by_id.get(id).copied(),
            MirCallee::Definition(def_id) => self.probe.functions_by_def.get(def_id).copied(),
            MirCallee::Value(value) => return Err(MirRustProbeError::unsupported(format!("indirect call {value:?}"))),
        }
        .ok_or_else(|| MirRustProbeError::unsupported(format!("unknown callee {callee:?}")))?;

        let mut rendered_args = Vec::with_capacity(args.len());
        for (index, arg) in args.iter().enumerate() {
            let expected = function.params.get(index).map(|param| param.ty);
            rendered_args.push(self.operand_expr(arg, expected)?);
        }

        Ok(format!("{}({})", function_name(function.id), rendered_args.join(", ")))
    }
}

fn function_name(id: MirFunctionId) -> String {
    format!("__faber_fn_{}", id.0)
}

fn local_name(id: MirLocalId) -> String {
    format!("__faber_local_{}", id.0)
}

fn temp_name(id: MirTempId) -> String {
    format!("__faber_tmp_{}", id.0)
}

fn block_variant(id: MirBlockId) -> String {
    format!("Bb{}", id.0)
}

fn quoted(value: &str) -> String {
    let mut out = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

fn float_literal(value: f64) -> String {
    if value.is_finite() {
        let rendered = value.to_string();
        if rendered.contains('.') {
            rendered
        } else {
            format!("{rendered}.0")
        }
    } else if value.is_nan() {
        "f64::NAN".to_owned()
    } else if value.is_sign_positive() {
        "f64::INFINITY".to_owned()
    } else {
        "f64::NEG_INFINITY".to_owned()
    }
}

#[cfg(test)]
#[path = "rust_probe_test.rs"]
mod tests;
