//! Experimental WebAssembly text emitter for validated MIR.
//!
//! TARGET: WASM backend lane proof. This emits a deliberately small `.wat`
//! subset from MIR so the target surface can grow in the right architectural
//! place before Faber commits to a full binary module, ABI, or Component Model
//! lowering pass.

use crate::codegen::CodeWriter;
use crate::hir::DefId;
use crate::lexer::Interner;
use crate::mir::*;
use crate::semantic::{Primitive, Type, TypeTable};
use rustc_hash::{FxHashMap, FxHashSet};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MirWasmTextProbeError {
    pub message: String,
}

impl MirWasmTextProbeError {
    fn unsupported(shape: impl Into<String>) -> Self {
        Self { message: format!("MIR-to-WASM unsupported: {}", shape.into()) }
    }
}

impl std::fmt::Display for MirWasmTextProbeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for MirWasmTextProbeError {}

pub fn emit_wasm_text_probe(
    program: &MirProgram,
    types: &TypeTable,
    interner: &Interner,
) -> Result<String, MirWasmTextProbeError> {
    let validation = MirValidationContext::new(types);
    emit_wasm_text_probe_with_context(program, &validation, interner)
}

pub fn emit_wasm_text_probe_with_context(
    program: &MirProgram,
    validation: &MirValidationContext<'_>,
    interner: &Interner,
) -> Result<String, MirWasmTextProbeError> {
    WasmTextProbe { program, types: validation.types, validation, interner }.emit_program()
}

struct WasmTextProbe<'a> {
    program: &'a MirProgram,
    types: &'a TypeTable,
    validation: &'a MirValidationContext<'a>,
    interner: &'a Interner,
}

struct FunctionContext {
    values: FxHashMap<MirValueId, String>,
    value_tys: FxHashMap<MirValueId, WasmValue>,
    locals: FxHashMap<MirLocalId, WasmValue>,
    temps: FxHashMap<MirTempId, WasmValue>,
    local_mir_tys: FxHashMap<MirLocalId, MirType>,
    temp_mir_tys: FxHashMap<MirTempId, MirType>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
enum WasmValue {
    I32,
    I64,
    F64,
    TextHandle,
    AggregateHandle,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
struct DiagnosticImport {
    kind: MirDiagnosticKind,
    value: WasmValue,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct TextFormatImport {
    args: Vec<WasmValue>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct AggregateImport {
    kind: AggregateImportKind,
    args: Vec<WasmValue>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct ProjectionImport {
    kind: ProjectionImportKind,
    key: WasmValue,
    result: WasmValue,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct RuntimeValueImport {
    kind: RuntimeValueImportKind,
    args: Vec<WasmValue>,
    result: WasmValue,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct PanicImport {
    arg: WasmValue,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
enum RuntimeValueImportKind {
    Convert,
    CollectionLength,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
enum ProjectionImportKind {
    Field,
    VariantField,
    Index,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
enum AggregateImportKind {
    Tuple,
    Array,
    Map,
    Set,
    Struct,
    Variant,
}

enum TerminatorMode {
    SingleBlock,
    Dispatch,
}

impl WasmTextProbe<'_> {
    fn emit_program(&self) -> Result<String, MirWasmTextProbeError> {
        let mut writer = CodeWriter::new();
        writer.writeln(";; Generated by radix MIR WASM text probe - experimental artifact.");
        writer.writeln("(module");
        writer.indent();
        if self.requires_text_concat_import()? {
            writer
                .writeln("(import \"faber_text\" \"concat\" (func $__faber_text_concat (param i32 i32) (result i32)))");
        }
        for import in self.required_aggregate_imports()? {
            let params = import
                .params()
                .iter()
                .map(|arg| arg.wat())
                .collect::<Vec<_>>()
                .join(" ");
            let params = if params.is_empty() {
                String::new()
            } else {
                format!(" (param {params})")
            };
            writer.writeln(&format!(
                "(import \"faber_aggregate\" \"{}\" (func ${}{params} (result i32)))",
                aggregate_import_name(&import),
                aggregate_import_symbol(&import),
            ));
        }
        for import in self.required_projection_imports()? {
            writer.writeln(&format!(
                "(import \"faber_aggregate\" \"{}\" (func ${} (param i32 {}) (result {})))",
                projection_import_name(&import),
                projection_import_symbol(&import),
                import.key.wat(),
                import.result.wat(),
            ));
        }
        for import in self.required_runtime_value_imports()? {
            let params = import
                .args
                .iter()
                .map(|arg| arg.wat())
                .collect::<Vec<_>>()
                .join(" ");
            writer.writeln(&format!(
                "(import \"faber_runtime\" \"{}\" (func ${} (param {params}) (result {})))",
                runtime_value_import_name(&import),
                runtime_value_import_symbol(&import),
                import.result.wat(),
            ));
        }
        for import in self.required_panic_imports()? {
            writer.writeln(&format!(
                "(import \"faber_runtime\" \"{}\" (func ${} (param {})))",
                panic_import_name(&import),
                panic_import_symbol(&import),
                import.arg.wat(),
            ));
        }
        for import in self.required_text_format_imports()? {
            let params = std::iter::once("i32")
                .chain(import.args.iter().map(|arg| arg.wat()))
                .collect::<Vec<_>>()
                .join(" ");
            writer.writeln(&format!(
                "(import \"faber_text\" \"{}\" (func ${} (param {params}) (result i32)))",
                text_format_import_name(&import),
                text_format_import_symbol(&import),
            ));
        }
        for import in self.required_diagnostic_imports()? {
            writer.writeln(&format!(
                "(import \"faber_diag\" \"{}\" (func ${} (param {})))",
                diagnostic_import_name(import),
                diagnostic_import_symbol(import),
                import.value.wat()
            ));
        }
        for function in &self.program.functions {
            self.emit_function(function, &mut writer)?;
        }
        writer.dedent();
        writer.writeln(")");
        Ok(writer.finish())
    }

    fn emit_function(&self, function: &MirFunction, writer: &mut CodeWriter) -> Result<(), MirWasmTextProbeError> {
        let name = self.function_name(function);
        let mut signature = format!("(func ${name} (export \"{name}\")");
        for param in &function.params {
            signature.push_str(&format!(" (param ${} {})", local_name(param.local), self.wasm_ty(param.ty)?));
        }
        if let Some(result_ty) = self.wasm_result_ty(function.return_ty)? {
            signature.push_str(&format!(" (result {result_ty})"));
        }
        writer.writeln(&signature);
        writer.indent();
        let mut context = self.function_context(function)?;
        let param_locals = function
            .params
            .iter()
            .map(|param| param.local)
            .collect::<FxHashSet<_>>();
        for local in &function.locals {
            if !param_locals.contains(&local.id) {
                writer.writeln(&format!("  (local ${} {})", local_name(local.id), self.wasm_ty(local.ty)?));
            }
        }
        for temp in &function.temps {
            writer.writeln(&format!("  (local ${} {})", temp_name(temp.id), self.wasm_ty(temp.ty)?));
        }
        if function.blocks.len() == 1 && function.blocks[0].id == MirBlockId(0) {
            self.emit_single_block_function(function, &mut context, writer)?;
        } else {
            writer.writeln("  (local $__block i32)");
            self.emit_dispatch_function(function, &mut context, writer)?;
        }
        writer.dedent();
        writer.writeln(")");
        Ok(())
    }

    fn emit_single_block_function(
        &self,
        function: &MirFunction,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirWasmTextProbeError> {
        let block = &function.blocks[0];
        for stmt in &block.statements {
            self.emit_stmt(stmt, context, writer)?;
        }
        self.emit_terminator(&block.terminator, context, writer, TerminatorMode::SingleBlock)
    }

    fn emit_dispatch_function(
        &self,
        function: &MirFunction,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirWasmTextProbeError> {
        writer.writeln("  (local.set $__block (i32.const 0))");
        writer.writeln("  (loop $__dispatch");
        writer.indent();
        for block in &function.blocks {
            writer.writeln(&format!("  (if (i32.eq (local.get $__block) (i32.const {}))", block.id.0));
            writer.indent();
            writer.writeln("  (then");
            writer.indent();
            for stmt in &block.statements {
                self.emit_stmt(stmt, context, writer)?;
            }
            self.emit_terminator(&block.terminator, context, writer, TerminatorMode::Dispatch)?;
            writer.dedent();
            writer.writeln("  )");
            writer.dedent();
            writer.writeln("  )");
        }
        writer.writeln("  (unreachable)");
        writer.dedent();
        writer.writeln("  )");
        writer.writeln("  (unreachable)");
        Ok(())
    }

    fn emit_stmt(
        &self,
        stmt: &MirStmt,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirWasmTextProbeError> {
        match &stmt.kind {
            MirStmtKind::Assign { place, value } => {
                let expr = self.value_expr(value, context, writer)?;
                context.values.insert(value.id, expr.clone());
                context
                    .value_tys
                    .insert(value.id, self.scalar_ty(value.ty)?);
                self.emit_place_set(place, &expr, context, writer)
            }
            MirStmtKind::Call { destination, callee, args } => {
                let call = self.call_expr(callee, args, context)?;
                if let Some(destination) = destination {
                    self.emit_place_set(destination, &call, context, writer)
                } else {
                    writer.writeln(&format!("  {call}"));
                    Ok(())
                }
            }
            MirStmtKind::RuntimeCall { destination, call } => match (destination, &call.intrinsic) {
                (None, MirIntrinsic::Diagnostic(kind)) => {
                    let [arg] = call.args.as_slice() else {
                        return Err(MirWasmTextProbeError::unsupported("diagnostic runtime arity"));
                    };
                    let value = self.operand_ty(arg, context)?;
                    let import = DiagnosticImport { kind: *kind, value };
                    let arg = self.operand_expr(arg, context)?;
                    writer.writeln(&format!("  (call ${} {arg})", diagnostic_import_symbol(import)));
                    Ok(())
                }
                (Some(destination), MirIntrinsic::FormatString { template }) => {
                    let expr = self.format_string_call_expr(*template, &call.args, call.return_ty, context)?;
                    self.emit_place_set(destination, &expr, context, writer)
                }
                (Some(destination), MirIntrinsic::Convert(conversion)) => {
                    let expr = self.conversion_call_expr(conversion, &call.args, call.return_ty, context)?;
                    self.emit_place_set(destination, &expr, context, writer)
                }
                (Some(destination), MirIntrinsic::Collection(MirCollectionOp::Length)) => {
                    let args = call.args.iter().collect::<Vec<_>>();
                    let expr = self.runtime_value_call_expr(
                        RuntimeValueImportKind::CollectionLength,
                        &args,
                        call.return_ty,
                        context,
                    )?;
                    self.emit_place_set(destination, &expr, context, writer)
                }
                (None, MirIntrinsic::Panic) => {
                    let [arg] = call.args.as_slice() else {
                        return Err(MirWasmTextProbeError::unsupported("panic runtime arity"));
                    };
                    let import = PanicImport { arg: self.operand_ty(arg, context)? };
                    let arg = self.operand_expr(arg, context)?;
                    writer.writeln(&format!("  (call ${} {arg})", panic_import_symbol(&import)));
                    Ok(())
                }
                (Some(_), _) => Err(MirWasmTextProbeError::unsupported("value-returning runtime call")),
                (None, _) => Err(MirWasmTextProbeError::unsupported("runtime call")),
            },
            MirStmtKind::Construct { destination, aggregate } => {
                let expr = self.construct_expr(aggregate, context)?;
                self.emit_place_set(destination, &expr, context, writer)
            }
        }
    }

    fn value_expr(
        &self,
        value: &MirValue,
        context: &FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<String, MirWasmTextProbeError> {
        match &value.kind {
            MirValueKind::Operand(operand) => self.operand_expr(operand, context),
            MirValueKind::Binary { op, lhs, rhs } => {
                let lhs_expr = self.operand_expr(lhs, context)?;
                let rhs_expr = self.operand_expr(rhs, context)?;
                let lhs_ty = self.operand_ty(lhs, context)?;
                let expr = if *op == MirBinOp::Add && lhs_ty == WasmValue::TextHandle {
                    format!("(call $__faber_text_concat {lhs_expr} {rhs_expr})")
                } else {
                    let op = wasm_bin_op(*op, lhs_ty)?;
                    format!("({op} {lhs_expr} {rhs_expr})")
                };
                writer.writeln(&format!("  ;; v{} = {expr}", value.id.0));
                Ok(expr)
            }
            MirValueKind::Unary { op, operand } => {
                let operand_expr = self.operand_expr(operand, context)?;
                let operand_ty = self.operand_ty(operand, context)?;
                let expr = wasm_un_op(*op, operand_ty, &operand_expr)?;
                writer.writeln(&format!("  ;; v{} = {expr}", value.id.0));
                Ok(expr)
            }
            MirValueKind::Option(_) => Err(MirWasmTextProbeError::unsupported("option value")),
        }
    }

    fn emit_place_set(
        &self,
        place: &MirPlace,
        expr: &str,
        _context: &FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirWasmTextProbeError> {
        if !place.projections.is_empty() {
            return Err(MirWasmTextProbeError::unsupported("place projection"));
        }
        match place.base {
            MirPlaceBase::Local(id) => {
                writer.writeln(&format!("  (local.set ${} {expr})", local_name(id)));
            }
            MirPlaceBase::Temp(id) => {
                writer.writeln(&format!("  (local.set ${} {expr})", temp_name(id)));
            }
        }
        Ok(())
    }

    fn emit_terminator(
        &self,
        terminator: &MirTerminator,
        context: &FunctionContext,
        writer: &mut CodeWriter,
        mode: TerminatorMode,
    ) -> Result<(), MirWasmTextProbeError> {
        match &terminator.kind {
            MirTerminatorKind::Return(Some(operand)) => {
                writer.writeln(&format!("  (return {})", self.operand_expr(operand, context)?));
                Ok(())
            }
            MirTerminatorKind::Return(None) => {
                writer.writeln("  (return)");
                Ok(())
            }
            MirTerminatorKind::Goto(target) if matches!(mode, TerminatorMode::Dispatch) => {
                self.emit_dispatch_jump(*target, writer);
                Ok(())
            }
            MirTerminatorKind::Branch { condition, then_block, else_block }
                if matches!(mode, TerminatorMode::Dispatch) =>
            {
                let condition = self.operand_expr(condition, context)?;
                writer.writeln(&format!("  (if {condition}"));
                writer.indent();
                writer.writeln("  (then");
                writer.indent();
                self.emit_dispatch_jump(*then_block, writer);
                writer.dedent();
                writer.writeln("  )");
                writer.writeln("  (else");
                writer.indent();
                self.emit_dispatch_jump(*else_block, writer);
                writer.dedent();
                writer.writeln("  )");
                writer.dedent();
                writer.writeln("  )");
                Ok(())
            }
            MirTerminatorKind::Unreachable => {
                writer.writeln("  (unreachable)");
                Ok(())
            }
            other => Err(MirWasmTextProbeError::unsupported(terminator_kind_name(other))),
        }
    }

    fn emit_dispatch_jump(&self, target: MirBlockId, writer: &mut CodeWriter) {
        writer.writeln(&format!("  (local.set $__block (i32.const {}))", target.0));
        writer.writeln("  (br $__dispatch)");
    }

    fn operand_expr(&self, operand: &MirOperand, context: &FunctionContext) -> Result<String, MirWasmTextProbeError> {
        match operand {
            MirOperand::Place(place) => self.place_expr(place, context),
            MirOperand::Value(id) => context
                .values
                .get(id)
                .cloned()
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined value v{}", id.0))),
            MirOperand::Constant(constant) => self.constant_expr(constant),
            MirOperand::Temp(id) => context
                .temps
                .get(id)
                .map(|_| format!("(local.get ${})", temp_name(*id)))
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined temp t{}", id.0))),
        }
    }

    fn place_expr(&self, place: &MirPlace, context: &FunctionContext) -> Result<String, MirWasmTextProbeError> {
        let mut expr = match place.base {
            MirPlaceBase::Local(id) => context
                .locals
                .get(&id)
                .map(|_| format!("(local.get ${})", local_name(id)))
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined local l{}", id.0))),
            MirPlaceBase::Temp(id) => context
                .temps
                .get(&id)
                .map(|_| format!("(local.get ${})", temp_name(id)))
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined temp t{}", id.0))),
        }?;

        let mut ty = self.place_base_mir_ty(place, context)?;
        for projection in &place.projections {
            let (import, key_expr, result_ty) = self.projection_import(projection, ty, context)?;
            expr = format!("(call ${} {expr} {key_expr})", projection_import_symbol(&import));
            ty = result_ty;
        }

        Ok(expr)
    }

    fn operand_ty(&self, operand: &MirOperand, context: &FunctionContext) -> Result<WasmValue, MirWasmTextProbeError> {
        match operand {
            MirOperand::Place(place) => self.place_ty(place, context),
            MirOperand::Value(id) => context
                .value_tys
                .get(id)
                .copied()
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined value v{}", id.0))),
            MirOperand::Constant(MirConstant::Int(_)) => Ok(WasmValue::I64),
            MirOperand::Constant(MirConstant::Float(_)) => Ok(WasmValue::F64),
            MirOperand::Constant(MirConstant::Bool(_)) => Ok(WasmValue::I32),
            MirOperand::Constant(MirConstant::String(_)) => Ok(WasmValue::TextHandle),
            MirOperand::Constant(other) => Err(MirWasmTextProbeError::unsupported(format!("constant {other:?}"))),
            MirOperand::Temp(id) => context
                .temps
                .get(id)
                .copied()
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined temp t{}", id.0))),
        }
    }

    fn place_ty(&self, place: &MirPlace, context: &FunctionContext) -> Result<WasmValue, MirWasmTextProbeError> {
        self.scalar_ty(self.place_mir_ty(place, context)?)
    }

    fn place_mir_ty(&self, place: &MirPlace, context: &FunctionContext) -> Result<MirType, MirWasmTextProbeError> {
        let mut ty = self.place_base_mir_ty(place, context)?;
        for projection in &place.projections {
            let (_, _, result_ty) = self.projection_import(projection, ty, context)?;
            ty = result_ty;
        }
        Ok(ty)
    }

    fn place_base_mir_ty(&self, place: &MirPlace, context: &FunctionContext) -> Result<MirType, MirWasmTextProbeError> {
        match place.base {
            MirPlaceBase::Local(id) => context
                .local_mir_tys
                .get(&id)
                .copied()
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined local l{}", id.0))),
            MirPlaceBase::Temp(id) => context
                .temp_mir_tys
                .get(&id)
                .copied()
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined temp t{}", id.0))),
        }
    }

    fn projection_import(
        &self,
        projection: &MirProjection,
        base_ty: MirType,
        context: &FunctionContext,
    ) -> Result<(ProjectionImport, String, MirType), MirWasmTextProbeError> {
        match projection {
            MirProjection::Field(field) => {
                let result_ty = self.project_field_ty(base_ty, *field)?;
                let import = ProjectionImport {
                    kind: ProjectionImportKind::Field,
                    key: WasmValue::I32,
                    result: self.scalar_ty(result_ty)?,
                };
                Ok((import, format!("(i32.const {})", field.0), result_ty))
            }
            MirProjection::VariantField { variant, field } => {
                let result_ty = self.project_variant_field_ty(*variant, *field)?;
                let import = ProjectionImport {
                    kind: ProjectionImportKind::VariantField,
                    key: WasmValue::I32,
                    result: self.scalar_ty(result_ty)?,
                };
                Ok((import, format!("(i32.const {})", field.0), result_ty))
            }
            MirProjection::Index(index) => {
                let key = self.operand_ty(index, context)?;
                let result_ty = self.project_index_ty(base_ty)?;
                let import =
                    ProjectionImport { kind: ProjectionImportKind::Index, key, result: self.scalar_ty(result_ty)? };
                Ok((import, self.operand_expr(index, context)?, result_ty))
            }
        }
    }

    fn constant_expr(&self, constant: &MirConstant) -> Result<String, MirWasmTextProbeError> {
        match constant {
            MirConstant::Int(value) => Ok(format!("(i64.const {value})")),
            MirConstant::Float(value) => Ok(format!("(f64.const {value:?})")),
            MirConstant::Bool(value) => Ok(format!("(i32.const {})", if *value { 1 } else { 0 })),
            MirConstant::String(symbol) => Ok(format!("(i32.const {})", symbol.0)),
            MirConstant::Unit => Ok("(i32.const 0)".to_owned()),
            MirConstant::Nil => Err(MirWasmTextProbeError::unsupported("nil constant")),
        }
    }

    fn wasm_ty(&self, ty: MirType) -> Result<&'static str, MirWasmTextProbeError> {
        self.scalar_ty(ty).map(WasmValue::wat)
    }

    fn wasm_result_ty(&self, ty: MirType) -> Result<Option<&'static str>, MirWasmTextProbeError> {
        match self.types.get(ty.semantic_id()) {
            Type::Primitive(Primitive::Vacuum) => Ok(None),
            _ => self.wasm_ty(ty).map(Some),
        }
    }

    fn function_name(&self, function: &MirFunction) -> String {
        function
            .name
            .map(|symbol| sanitize_name(self.interner.resolve(symbol)))
            .unwrap_or_else(|| format!("f{}", function.id.0))
    }

    fn function_context(&self, function: &MirFunction) -> Result<FunctionContext, MirWasmTextProbeError> {
        let mut locals = FxHashMap::default();
        let mut local_mir_tys = FxHashMap::default();
        for local in &function.locals {
            locals.insert(local.id, self.scalar_ty(local.ty)?);
            local_mir_tys.insert(local.id, local.ty);
        }
        let mut temps = FxHashMap::default();
        let mut temp_mir_tys = FxHashMap::default();
        for temp in &function.temps {
            temps.insert(temp.id, self.scalar_ty(temp.ty)?);
            temp_mir_tys.insert(temp.id, temp.ty);
        }
        let mut value_tys = FxHashMap::default();
        for block in &function.blocks {
            for stmt in &block.statements {
                if let MirStmtKind::Assign { value, .. } = &stmt.kind {
                    value_tys.insert(value.id, self.scalar_ty(value.ty)?);
                }
            }
        }
        Ok(FunctionContext { values: FxHashMap::default(), value_tys, locals, temps, local_mir_tys, temp_mir_tys })
    }

    fn scalar_ty(&self, ty: MirType) -> Result<WasmValue, MirWasmTextProbeError> {
        match self.types.get(ty.semantic_id()) {
            Type::Primitive(Primitive::Numerus) => Ok(WasmValue::I64),
            Type::Primitive(Primitive::Fractus) => Ok(WasmValue::F64),
            Type::Primitive(Primitive::Bivalens) => Ok(WasmValue::I32),
            Type::Primitive(Primitive::Textus) => Ok(WasmValue::TextHandle),
            Type::Array(_) | Type::Map(_, _) | Type::Record(_) | Type::Set(_) | Type::Struct(_) | Type::Enum(_) => {
                Ok(WasmValue::AggregateHandle)
            }
            Type::Alias(_, target) => self.scalar_ty(MirType::semantic(*target)),
            other => Err(MirWasmTextProbeError::unsupported(format!("type {other:?}"))),
        }
    }

    fn project_field_ty(
        &self,
        base_ty: MirType,
        field: crate::lexer::Symbol,
    ) -> Result<MirType, MirWasmTextProbeError> {
        match self.types.get(base_ty.semantic_id()) {
            Type::Struct(def_id) => self
                .validation
                .struct_fields
                .get(def_id)
                .and_then(|fields| fields.get(&field))
                .copied()
                .ok_or_else(|| MirWasmTextProbeError::unsupported("struct field projection metadata")),
            Type::Record(fields) => fields
                .get(&field)
                .copied()
                .map(MirType::semantic)
                .ok_or_else(|| MirWasmTextProbeError::unsupported("record field projection metadata")),
            Type::Alias(_, target) => self.project_field_ty(MirType::semantic(*target), field),
            _ => Err(MirWasmTextProbeError::unsupported("field projection base")),
        }
    }

    fn project_variant_field_ty(
        &self,
        variant: DefId,
        field: crate::lexer::Symbol,
    ) -> Result<MirType, MirWasmTextProbeError> {
        self.validation
            .variant_fields
            .get(&variant)
            .and_then(|fields| fields.get(&field))
            .copied()
            .ok_or_else(|| MirWasmTextProbeError::unsupported("variant field projection metadata"))
    }

    fn project_index_ty(&self, base_ty: MirType) -> Result<MirType, MirWasmTextProbeError> {
        match self.types.get(base_ty.semantic_id()) {
            Type::Array(inner) => Ok(MirType::semantic(*inner)),
            Type::Map(_, value) => Ok(MirType::semantic(*value)),
            Type::Primitive(Primitive::Textus) => Ok(MirType::semantic(self.types.primitive(Primitive::Textus))),
            Type::Alias(_, target) => self.project_index_ty(MirType::semantic(*target)),
            _ => Err(MirWasmTextProbeError::unsupported("index projection base")),
        }
    }

    fn call_expr(
        &self,
        callee: &MirCallee,
        args: &[MirOperand],
        context: &FunctionContext,
    ) -> Result<String, MirWasmTextProbeError> {
        let callee = self.callee_name(callee)?;
        let mut call = format!("(call ${callee}");
        for arg in args {
            call.push(' ');
            call.push_str(&self.operand_expr(arg, context)?);
        }
        call.push(')');
        Ok(call)
    }

    fn construct_expr(
        &self,
        aggregate: &MirAggregate,
        context: &FunctionContext,
    ) -> Result<String, MirWasmTextProbeError> {
        if self.scalar_ty(aggregate.ty)? != WasmValue::AggregateHandle {
            return Err(MirWasmTextProbeError::unsupported("non-aggregate construct type"));
        }

        let operands = aggregate_operands(&aggregate.fields);
        let import = AggregateImport {
            kind: aggregate_import_kind(&aggregate.kind),
            args: operands
                .iter()
                .map(|operand| self.operand_ty(operand, context))
                .collect::<Result<Vec<_>, _>>()?,
        };
        let mut call = format!("(call ${}", aggregate_import_symbol(&import));
        if let Some(def_id) = aggregate_definition_id(&aggregate.kind) {
            call.push_str(&format!(" (i32.const {})", def_id.0));
        }
        for operand in operands {
            call.push(' ');
            call.push_str(&self.operand_expr(operand, context)?);
        }
        call.push(')');
        Ok(call)
    }

    fn format_string_call_expr(
        &self,
        template: crate::lexer::Symbol,
        args: &[MirOperand],
        return_ty: MirType,
        context: &FunctionContext,
    ) -> Result<String, MirWasmTextProbeError> {
        if self.scalar_ty(return_ty)? != WasmValue::TextHandle {
            return Err(MirWasmTextProbeError::unsupported("format string return type"));
        }
        let import = TextFormatImport {
            args: args
                .iter()
                .map(|arg| self.operand_ty(arg, context))
                .collect::<Result<Vec<_>, _>>()?,
        };
        let mut call = format!("(call ${} (i32.const {})", text_format_import_symbol(&import), template.0);
        for arg in args {
            call.push(' ');
            call.push_str(&self.operand_expr(arg, context)?);
        }
        call.push(')');
        Ok(call)
    }

    fn conversion_call_expr(
        &self,
        conversion: &MirConversion,
        args: &[MirOperand],
        return_ty: MirType,
        context: &FunctionContext,
    ) -> Result<String, MirWasmTextProbeError> {
        let [source] = args else {
            return Err(MirWasmTextProbeError::unsupported("conversion runtime arity"));
        };
        let mut operands = vec![source];
        if let Some(fallback) = &conversion.fallback {
            operands.push(fallback);
        }
        self.runtime_value_call_expr(RuntimeValueImportKind::Convert, &operands, return_ty, context)
    }

    fn runtime_value_call_expr(
        &self,
        kind: RuntimeValueImportKind,
        args: &[&MirOperand],
        return_ty: MirType,
        context: &FunctionContext,
    ) -> Result<String, MirWasmTextProbeError> {
        let import = RuntimeValueImport {
            kind,
            args: args
                .iter()
                .map(|arg| self.operand_ty(arg, context))
                .collect::<Result<Vec<_>, _>>()?,
            result: self.scalar_ty(return_ty)?,
        };
        let mut call = format!("(call ${}", runtime_value_import_symbol(&import));
        for arg in args {
            call.push(' ');
            call.push_str(&self.operand_expr(arg, context)?);
        }
        call.push(')');
        Ok(call)
    }

    fn callee_name(&self, callee: &MirCallee) -> Result<String, MirWasmTextProbeError> {
        match callee {
            MirCallee::Function(id) => self
                .program
                .functions
                .iter()
                .find(|function| function.id == *id)
                .map(|function| self.function_name(function))
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("unknown function f{}", id.0))),
            MirCallee::Definition(def_id) => self
                .program
                .functions
                .iter()
                .find(|function| function.source == Some(*def_id))
                .map(|function| self.function_name(function))
                .ok_or_else(|| MirWasmTextProbeError::unsupported("external definition call")),
            MirCallee::Value(_) => Err(MirWasmTextProbeError::unsupported("value callee")),
        }
    }

    fn required_diagnostic_imports(&self) -> Result<Vec<DiagnosticImport>, MirWasmTextProbeError> {
        let mut imports = FxHashSet::default();
        for function in &self.program.functions {
            let context = self.function_context(function)?;
            for block in &function.blocks {
                for stmt in &block.statements {
                    let MirStmtKind::RuntimeCall { destination, call } = &stmt.kind else {
                        continue;
                    };
                    if destination.is_some() {
                        continue;
                    }
                    let MirIntrinsic::Diagnostic(kind) = call.intrinsic else {
                        continue;
                    };
                    let [arg] = call.args.as_slice() else {
                        continue;
                    };
                    imports.insert(DiagnosticImport { kind, value: self.operand_ty(arg, &context)? });
                }
            }
        }
        let mut imports = imports.into_iter().collect::<Vec<_>>();
        imports.sort_by_key(|import| diagnostic_import_name(*import));
        Ok(imports)
    }

    fn requires_text_concat_import(&self) -> Result<bool, MirWasmTextProbeError> {
        for function in &self.program.functions {
            let context = self.function_context(function)?;
            for block in &function.blocks {
                for stmt in &block.statements {
                    let MirStmtKind::Assign { value, .. } = &stmt.kind else {
                        continue;
                    };
                    let MirValueKind::Binary { op: MirBinOp::Add, lhs, .. } = &value.kind else {
                        continue;
                    };
                    if self.operand_ty(lhs, &context)? == WasmValue::TextHandle {
                        return Ok(true);
                    }
                }
            }
        }
        Ok(false)
    }

    fn required_text_format_imports(&self) -> Result<Vec<TextFormatImport>, MirWasmTextProbeError> {
        let mut imports = FxHashSet::default();
        for function in &self.program.functions {
            let context = self.function_context(function)?;
            for block in &function.blocks {
                for stmt in &block.statements {
                    let MirStmtKind::RuntimeCall { destination: Some(_), call } = &stmt.kind else {
                        continue;
                    };
                    if !matches!(call.intrinsic, MirIntrinsic::FormatString { .. }) {
                        continue;
                    }
                    if self.scalar_ty(call.return_ty)? != WasmValue::TextHandle {
                        continue;
                    }
                    imports.insert(TextFormatImport {
                        args: call
                            .args
                            .iter()
                            .map(|arg| self.operand_ty(arg, &context))
                            .collect::<Result<Vec<_>, _>>()?,
                    });
                }
            }
        }
        let mut imports = imports.into_iter().collect::<Vec<_>>();
        imports.sort_by_key(text_format_import_name);
        Ok(imports)
    }

    fn required_runtime_value_imports(&self) -> Result<Vec<RuntimeValueImport>, MirWasmTextProbeError> {
        let mut imports = FxHashSet::default();
        for function in &self.program.functions {
            let context = self.function_context(function)?;
            for block in &function.blocks {
                for stmt in &block.statements {
                    let MirStmtKind::RuntimeCall { destination: Some(_), call } = &stmt.kind else {
                        continue;
                    };
                    match &call.intrinsic {
                        MirIntrinsic::Convert(conversion) => {
                            let [source] = call.args.as_slice() else {
                                continue;
                            };
                            let mut args = vec![self.operand_ty(source, &context)?];
                            if let Some(fallback) = &conversion.fallback {
                                args.push(self.operand_ty(fallback, &context)?);
                            }
                            imports.insert(RuntimeValueImport {
                                kind: RuntimeValueImportKind::Convert,
                                args,
                                result: self.scalar_ty(call.return_ty)?,
                            });
                        }
                        MirIntrinsic::Collection(MirCollectionOp::Length) => {
                            imports.insert(RuntimeValueImport {
                                kind: RuntimeValueImportKind::CollectionLength,
                                args: call
                                    .args
                                    .iter()
                                    .map(|arg| self.operand_ty(arg, &context))
                                    .collect::<Result<Vec<_>, _>>()?,
                                result: self.scalar_ty(call.return_ty)?,
                            });
                        }
                        _ => {}
                    }
                }
            }
        }
        let mut imports = imports.into_iter().collect::<Vec<_>>();
        imports.sort_by_key(runtime_value_import_name);
        Ok(imports)
    }

    fn required_panic_imports(&self) -> Result<Vec<PanicImport>, MirWasmTextProbeError> {
        let mut imports = FxHashSet::default();
        for function in &self.program.functions {
            let context = self.function_context(function)?;
            for block in &function.blocks {
                for stmt in &block.statements {
                    let MirStmtKind::RuntimeCall { destination: None, call } = &stmt.kind else {
                        continue;
                    };
                    if !matches!(call.intrinsic, MirIntrinsic::Panic) {
                        continue;
                    }
                    let [arg] = call.args.as_slice() else {
                        continue;
                    };
                    imports.insert(PanicImport { arg: self.operand_ty(arg, &context)? });
                }
            }
        }
        let mut imports = imports.into_iter().collect::<Vec<_>>();
        imports.sort_by_key(panic_import_name);
        Ok(imports)
    }

    fn required_aggregate_imports(&self) -> Result<Vec<AggregateImport>, MirWasmTextProbeError> {
        let mut imports = FxHashSet::default();
        for function in &self.program.functions {
            let context = self.function_context(function)?;
            for block in &function.blocks {
                for stmt in &block.statements {
                    let MirStmtKind::Construct { aggregate, .. } = &stmt.kind else {
                        continue;
                    };
                    if self.scalar_ty(aggregate.ty)? != WasmValue::AggregateHandle {
                        continue;
                    }
                    imports.insert(AggregateImport {
                        kind: aggregate_import_kind(&aggregate.kind),
                        args: aggregate_operands(&aggregate.fields)
                            .into_iter()
                            .map(|operand| self.operand_ty(operand, &context))
                            .collect::<Result<Vec<_>, _>>()?,
                    });
                }
            }
        }
        let mut imports = imports.into_iter().collect::<Vec<_>>();
        imports.sort_by_key(aggregate_import_name);
        Ok(imports)
    }

    fn required_projection_imports(&self) -> Result<Vec<ProjectionImport>, MirWasmTextProbeError> {
        let mut imports = FxHashSet::default();
        for function in &self.program.functions {
            let context = self.function_context(function)?;
            for block in &function.blocks {
                for stmt in &block.statements {
                    self.collect_stmt_projection_imports(stmt, &context, &mut imports)?;
                }
                self.collect_terminator_projection_imports(&block.terminator, &context, &mut imports)?;
            }
        }
        let mut imports = imports.into_iter().collect::<Vec<_>>();
        imports.sort_by_key(projection_import_name);
        Ok(imports)
    }

    fn collect_stmt_projection_imports(
        &self,
        stmt: &MirStmt,
        context: &FunctionContext,
        imports: &mut FxHashSet<ProjectionImport>,
    ) -> Result<(), MirWasmTextProbeError> {
        match &stmt.kind {
            MirStmtKind::Assign { place, value } => {
                self.collect_place_projection_imports(place, context, imports)?;
                self.collect_value_projection_imports(value, context, imports)
            }
            MirStmtKind::Call { destination, args, .. } => {
                if let Some(destination) = destination {
                    self.collect_place_projection_imports(destination, context, imports)?;
                }
                for arg in args {
                    self.collect_operand_projection_imports(arg, context, imports)?;
                }
                Ok(())
            }
            MirStmtKind::RuntimeCall { destination, call } => {
                if let Some(destination) = destination {
                    self.collect_place_projection_imports(destination, context, imports)?;
                }
                for arg in &call.args {
                    self.collect_operand_projection_imports(arg, context, imports)?;
                }
                if let MirIntrinsic::Convert(conversion) = &call.intrinsic {
                    if let Some(fallback) = &conversion.fallback {
                        self.collect_operand_projection_imports(fallback, context, imports)?;
                    }
                }
                Ok(())
            }
            MirStmtKind::Construct { destination, aggregate } => {
                self.collect_place_projection_imports(destination, context, imports)?;
                for operand in aggregate_operands(&aggregate.fields) {
                    self.collect_operand_projection_imports(operand, context, imports)?;
                }
                Ok(())
            }
        }
    }

    fn collect_value_projection_imports(
        &self,
        value: &MirValue,
        context: &FunctionContext,
        imports: &mut FxHashSet<ProjectionImport>,
    ) -> Result<(), MirWasmTextProbeError> {
        match &value.kind {
            MirValueKind::Operand(operand) => self.collect_operand_projection_imports(operand, context, imports),
            MirValueKind::Binary { lhs, rhs, .. } => {
                self.collect_operand_projection_imports(lhs, context, imports)?;
                self.collect_operand_projection_imports(rhs, context, imports)
            }
            MirValueKind::Unary { operand, .. } => self.collect_operand_projection_imports(operand, context, imports),
            MirValueKind::Option(_) => Ok(()),
        }
    }

    fn collect_terminator_projection_imports(
        &self,
        terminator: &MirTerminator,
        context: &FunctionContext,
        imports: &mut FxHashSet<ProjectionImport>,
    ) -> Result<(), MirWasmTextProbeError> {
        match &terminator.kind {
            MirTerminatorKind::Return(Some(operand))
            | MirTerminatorKind::ReturnError(operand)
            | MirTerminatorKind::Branch { condition: operand, .. } => {
                self.collect_operand_projection_imports(operand, context, imports)
            }
            MirTerminatorKind::TryCall { args, .. } => {
                for arg in args {
                    self.collect_operand_projection_imports(arg, context, imports)?;
                }
                Ok(())
            }
            MirTerminatorKind::Switch { value, .. } => self.collect_operand_projection_imports(value, context, imports),
            MirTerminatorKind::Return(None) | MirTerminatorKind::Goto(_) | MirTerminatorKind::Unreachable => Ok(()),
        }
    }

    fn collect_operand_projection_imports(
        &self,
        operand: &MirOperand,
        context: &FunctionContext,
        imports: &mut FxHashSet<ProjectionImport>,
    ) -> Result<(), MirWasmTextProbeError> {
        if let MirOperand::Place(place) = operand {
            self.collect_place_projection_imports(place, context, imports)?;
        }
        Ok(())
    }

    fn collect_place_projection_imports(
        &self,
        place: &MirPlace,
        context: &FunctionContext,
        imports: &mut FxHashSet<ProjectionImport>,
    ) -> Result<(), MirWasmTextProbeError> {
        let mut ty = self.place_base_mir_ty(place, context)?;
        for projection in &place.projections {
            let (import, _, result_ty) = self.projection_import(projection, ty, context)?;
            imports.insert(import);
            ty = result_ty;
        }
        Ok(())
    }
}

fn local_name(id: MirLocalId) -> String {
    format!("l{}", id.0)
}

fn temp_name(id: MirTempId) -> String {
    format!("t{}", id.0)
}

fn sanitize_name(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn wasm_bin_op(op: MirBinOp, lhs_ty: WasmValue) -> Result<&'static str, MirWasmTextProbeError> {
    match op {
        MirBinOp::Add if lhs_ty == WasmValue::I64 => Ok("i64.add"),
        MirBinOp::Sub if lhs_ty == WasmValue::I64 => Ok("i64.sub"),
        MirBinOp::Mul if lhs_ty == WasmValue::I64 => Ok("i64.mul"),
        MirBinOp::Div if lhs_ty == WasmValue::I64 => Ok("i64.div_s"),
        MirBinOp::Mod if lhs_ty == WasmValue::I64 => Ok("i64.rem_s"),
        MirBinOp::Add if lhs_ty == WasmValue::F64 => Ok("f64.add"),
        MirBinOp::Sub if lhs_ty == WasmValue::F64 => Ok("f64.sub"),
        MirBinOp::Mul if lhs_ty == WasmValue::F64 => Ok("f64.mul"),
        MirBinOp::Div if lhs_ty == WasmValue::F64 => Ok("f64.div"),
        MirBinOp::Eq if lhs_ty == WasmValue::I64 => Ok("i64.eq"),
        MirBinOp::NotEq if lhs_ty == WasmValue::I64 => Ok("i64.ne"),
        MirBinOp::Lt if lhs_ty == WasmValue::I64 => Ok("i64.lt_s"),
        MirBinOp::Gt if lhs_ty == WasmValue::I64 => Ok("i64.gt_s"),
        MirBinOp::LtEq if lhs_ty == WasmValue::I64 => Ok("i64.le_s"),
        MirBinOp::GtEq if lhs_ty == WasmValue::I64 => Ok("i64.ge_s"),
        MirBinOp::Eq if lhs_ty == WasmValue::F64 => Ok("f64.eq"),
        MirBinOp::NotEq if lhs_ty == WasmValue::F64 => Ok("f64.ne"),
        MirBinOp::Lt if lhs_ty == WasmValue::F64 => Ok("f64.lt"),
        MirBinOp::Gt if lhs_ty == WasmValue::F64 => Ok("f64.gt"),
        MirBinOp::LtEq if lhs_ty == WasmValue::F64 => Ok("f64.le"),
        MirBinOp::GtEq if lhs_ty == WasmValue::F64 => Ok("f64.ge"),
        MirBinOp::Eq if lhs_ty == WasmValue::I32 => Ok("i32.eq"),
        MirBinOp::NotEq if lhs_ty == WasmValue::I32 => Ok("i32.ne"),
        MirBinOp::And => Ok("i32.and"),
        MirBinOp::Or => Ok("i32.or"),
        _ => Err(MirWasmTextProbeError::unsupported(format!("binary op {op:?}"))),
    }
}

fn wasm_un_op(op: MirUnOp, operand_ty: WasmValue, operand: &str) -> Result<String, MirWasmTextProbeError> {
    match (op, operand_ty) {
        (MirUnOp::Neg, WasmValue::I64) => Ok(format!("(i64.sub (i64.const 0) {operand})")),
        (MirUnOp::Neg, WasmValue::F64) => Ok(format!("(f64.neg {operand})")),
        (MirUnOp::Not, WasmValue::I32) => Ok(format!("(i32.eqz {operand})")),
        (MirUnOp::BitNot, WasmValue::I64) => Ok(format!("(i64.xor {operand} (i64.const -1))")),
        _ => Err(MirWasmTextProbeError::unsupported(format!("unary op {op:?}"))),
    }
}

impl WasmValue {
    fn wat(self) -> &'static str {
        match self {
            WasmValue::I32 | WasmValue::TextHandle | WasmValue::AggregateHandle => "i32",
            WasmValue::I64 => "i64",
            WasmValue::F64 => "f64",
        }
    }

    fn abi_name(self) -> &'static str {
        match self {
            WasmValue::I32 => "i32",
            WasmValue::I64 => "i64",
            WasmValue::F64 => "f64",
            WasmValue::TextHandle => "text",
            WasmValue::AggregateHandle => "aggregate",
        }
    }
}

impl AggregateImport {
    fn params(&self) -> Vec<WasmValue> {
        let mut params = Vec::with_capacity(self.args.len() + 1);
        if matches!(self.kind, AggregateImportKind::Struct | AggregateImportKind::Variant) {
            params.push(WasmValue::I32);
        }
        params.extend(self.args.iter().copied());
        params
    }
}

fn text_format_import_name(import: &TextFormatImport) -> String {
    let suffix = if import.args.is_empty() {
        "0".to_owned()
    } else {
        let args = import
            .args
            .iter()
            .map(|arg| arg.abi_name())
            .collect::<Vec<_>>()
            .join("_");
        format!("{}_{}", import.args.len(), args)
    };
    format!("format_{suffix}")
}

fn text_format_import_symbol(import: &TextFormatImport) -> String {
    format!("__faber_text_{}", text_format_import_name(import))
}

fn diagnostic_import_name(import: DiagnosticImport) -> &'static str {
    match (import.kind, import.value) {
        (MirDiagnosticKind::Nota, WasmValue::I32) => "nota_i32",
        (MirDiagnosticKind::Nota, WasmValue::I64) => "nota_i64",
        (MirDiagnosticKind::Nota, WasmValue::F64) => "nota_f64",
        (MirDiagnosticKind::Nota, WasmValue::TextHandle) => "nota_text",
        (MirDiagnosticKind::Nota, WasmValue::AggregateHandle) => "nota_aggregate",
        (MirDiagnosticKind::Vide, WasmValue::I32) => "vide_i32",
        (MirDiagnosticKind::Vide, WasmValue::I64) => "vide_i64",
        (MirDiagnosticKind::Vide, WasmValue::F64) => "vide_f64",
        (MirDiagnosticKind::Vide, WasmValue::TextHandle) => "vide_text",
        (MirDiagnosticKind::Vide, WasmValue::AggregateHandle) => "vide_aggregate",
        (MirDiagnosticKind::Mone, WasmValue::I32) => "mone_i32",
        (MirDiagnosticKind::Mone, WasmValue::I64) => "mone_i64",
        (MirDiagnosticKind::Mone, WasmValue::F64) => "mone_f64",
        (MirDiagnosticKind::Mone, WasmValue::TextHandle) => "mone_text",
        (MirDiagnosticKind::Mone, WasmValue::AggregateHandle) => "mone_aggregate",
        (MirDiagnosticKind::Scribe, WasmValue::I32) => "scribe_i32",
        (MirDiagnosticKind::Scribe, WasmValue::I64) => "scribe_i64",
        (MirDiagnosticKind::Scribe, WasmValue::F64) => "scribe_f64",
        (MirDiagnosticKind::Scribe, WasmValue::TextHandle) => "scribe_text",
        (MirDiagnosticKind::Scribe, WasmValue::AggregateHandle) => "scribe_aggregate",
    }
}

fn diagnostic_import_symbol(import: DiagnosticImport) -> String {
    format!("__faber_diag_{}", diagnostic_import_name(import))
}

fn terminator_kind_name(kind: &MirTerminatorKind) -> &'static str {
    match kind {
        MirTerminatorKind::Return(_) => "return",
        MirTerminatorKind::ReturnError(_) => "return_error",
        MirTerminatorKind::TryCall { .. } => "try_call",
        MirTerminatorKind::Goto(_) => "goto",
        MirTerminatorKind::Branch { .. } => "branch",
        MirTerminatorKind::Switch { .. } => "switch",
        MirTerminatorKind::Unreachable => "unreachable",
    }
}

fn aggregate_import_kind(kind: &MirAggregateKind) -> AggregateImportKind {
    match kind {
        MirAggregateKind::Tuple => AggregateImportKind::Tuple,
        MirAggregateKind::Array => AggregateImportKind::Array,
        MirAggregateKind::Map => AggregateImportKind::Map,
        MirAggregateKind::Set => AggregateImportKind::Set,
        MirAggregateKind::Struct(_) => AggregateImportKind::Struct,
        MirAggregateKind::EnumVariant(_) => AggregateImportKind::Variant,
    }
}

fn aggregate_definition_id(kind: &MirAggregateKind) -> Option<DefId> {
    match kind {
        MirAggregateKind::Struct(def_id) | MirAggregateKind::EnumVariant(def_id) => Some(*def_id),
        _ => None,
    }
}

fn aggregate_operands(fields: &MirAggregateFields) -> Vec<&MirOperand> {
    match fields {
        MirAggregateFields::Ordered(items) => items
            .iter()
            .map(|item| match item {
                MirAggregateItem::Operand(operand) | MirAggregateItem::Spread(operand) => operand,
            })
            .collect(),
        MirAggregateFields::Named(items) => items.iter().map(|item| &item.value).collect(),
        MirAggregateFields::Keyed(items) => items
            .iter()
            .flat_map(|item| [&item.key, &item.value])
            .collect(),
    }
}

fn aggregate_import_name(import: &AggregateImport) -> String {
    let kind = match import.kind {
        AggregateImportKind::Tuple => "tuple",
        AggregateImportKind::Array => "array",
        AggregateImportKind::Map => "map",
        AggregateImportKind::Set => "set",
        AggregateImportKind::Struct => "struct",
        AggregateImportKind::Variant => "variant",
    };
    let suffix = if import.args.is_empty() {
        "0".to_owned()
    } else {
        let args = import
            .args
            .iter()
            .map(|arg| arg.abi_name())
            .collect::<Vec<_>>()
            .join("_");
        format!("{}_{}", import.args.len(), args)
    };
    format!("{kind}_{suffix}")
}

fn aggregate_import_symbol(import: &AggregateImport) -> String {
    format!("__faber_aggregate_{}", aggregate_import_name(import))
}

fn projection_import_name(import: &ProjectionImport) -> String {
    let kind = match import.kind {
        ProjectionImportKind::Field => "field",
        ProjectionImportKind::VariantField => "variant_field",
        ProjectionImportKind::Index => "index",
    };
    format!("{kind}_{}_to_{}", import.key.abi_name(), import.result.abi_name())
}

fn projection_import_symbol(import: &ProjectionImport) -> String {
    format!("__faber_aggregate_{}", projection_import_name(import))
}

fn runtime_value_import_name(import: &RuntimeValueImport) -> String {
    let kind = match import.kind {
        RuntimeValueImportKind::Convert => "convert",
        RuntimeValueImportKind::CollectionLength => "length",
    };
    let args = import
        .args
        .iter()
        .map(|arg| arg.abi_name())
        .collect::<Vec<_>>()
        .join("_");
    format!("{kind}_{}_{}_to_{}", import.args.len(), args, import.result.abi_name())
}

fn runtime_value_import_symbol(import: &RuntimeValueImport) -> String {
    format!("__faber_runtime_{}", runtime_value_import_name(import))
}

fn panic_import_name(import: &PanicImport) -> String {
    format!("panic_{}", import.arg.abi_name())
}

fn panic_import_symbol(import: &PanicImport) -> String {
    format!("__faber_runtime_{}", panic_import_name(import))
}

#[cfg(test)]
#[path = "wasm_text_test.rs"]
mod tests;
