//! Experimental WebAssembly text emitter for validated MIR.
//!
//! TARGET: WASM backend lane proof. This emits a deliberately small `.wat`
//! subset from MIR so the target surface can grow in the right architectural
//! place before Faber commits to a full binary module, ABI, or Component Model
//! lowering pass.

use crate::codegen::CodeWriter;
use crate::lexer::Interner;
use crate::mir::*;
use crate::semantic::{Primitive, Type, TypeTable};
use rustc_hash::FxHashMap;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MirWasmTextProbeError {
    pub message: String,
}

impl MirWasmTextProbeError {
    fn unsupported(shape: impl Into<String>) -> Self {
        Self { message: format!("MIR-to-WASM unsupported: {}", shape.into()) }
    }
}

impl std::fmt::Display for MirWasmTextProbeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for MirWasmTextProbeError {}

pub fn emit_wasm_text_probe(
    program: &MirProgram,
    types: &TypeTable,
    interner: &Interner,
) -> Result<String, MirWasmTextProbeError> {
    WasmTextProbe { program, types, interner }.emit_program()
}

struct WasmTextProbe<'a> {
    program: &'a MirProgram,
    types: &'a TypeTable,
    interner: &'a Interner,
}

struct FunctionContext {
    values: FxHashMap<MirValueId, String>,
    locals: FxHashMap<MirLocalId, String>,
    temps: FxHashMap<MirTempId, String>,
}

impl WasmTextProbe<'_> {
    fn emit_program(&self) -> Result<String, MirWasmTextProbeError> {
        let mut writer = CodeWriter::new();
        writer.writeln(";; Generated by radix MIR WASM text probe - experimental artifact.");
        writer.writeln("(module");
        writer.indent();
        for function in &self.program.functions {
            self.emit_function(function, &mut writer)?;
        }
        writer.dedent();
        writer.writeln(")");
        Ok(writer.finish())
    }

    fn emit_function(&self, function: &MirFunction, writer: &mut CodeWriter) -> Result<(), MirWasmTextProbeError> {
        let name = self.function_name(function);
        let mut signature = format!("(func ${name} (export \"{name}\")");
        for param in &function.params {
            signature.push_str(&format!(" (param ${} {})", local_name(param.local), self.wasm_ty(param.ty)?));
        }
        if let Some(result_ty) = self.wasm_result_ty(function.return_ty)? {
            signature.push_str(&format!(" (result {result_ty})"));
        }
        writer.writeln(&signature);
        writer.indent();
        let mut context =
            FunctionContext { values: FxHashMap::default(), locals: FxHashMap::default(), temps: FxHashMap::default() };
        for block in &function.blocks {
            if block.id != MirBlockId(0) {
                return Err(MirWasmTextProbeError::unsupported("multiple basic blocks"));
            }
            for stmt in &block.statements {
                self.emit_stmt(stmt, &mut context, writer)?;
            }
            self.emit_terminator(&block.terminator, &context, writer)?;
        }
        writer.dedent();
        writer.writeln(")");
        Ok(())
    }

    fn emit_stmt(
        &self,
        stmt: &MirStmt,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirWasmTextProbeError> {
        let MirStmtKind::Assign { place, value } = &stmt.kind else {
            return Err(MirWasmTextProbeError::unsupported(stmt_kind_name(&stmt.kind)));
        };
        if !place.projections.is_empty() {
            return Err(MirWasmTextProbeError::unsupported("place projection"));
        }
        let expr = match &value.kind {
            MirValueKind::Operand(operand) => self.operand_expr(operand, context)?,
            MirValueKind::Binary { op, lhs, rhs } => {
                let lhs = self.operand_expr(lhs, context)?;
                let rhs = self.operand_expr(rhs, context)?;
                let op = wasm_bin_op(*op)?;
                let expr = format!("({op} {lhs} {rhs})");
                writer.writeln(&format!("  ;; v{} = {expr}", value.id.0));
                expr
            }
            MirValueKind::Unary { .. } => return Err(MirWasmTextProbeError::unsupported("unary value")),
            MirValueKind::Option(_) => return Err(MirWasmTextProbeError::unsupported("option value")),
        };
        context.values.insert(value.id, expr.clone());
        match place.base {
            MirPlaceBase::Local(id) => {
                context.locals.insert(id, expr);
            }
            MirPlaceBase::Temp(id) => {
                context.temps.insert(id, expr);
            }
        }
        Ok(())
    }

    fn emit_terminator(
        &self,
        terminator: &MirTerminator,
        context: &FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirWasmTextProbeError> {
        match &terminator.kind {
            MirTerminatorKind::Return(Some(operand)) => {
                writer.writeln(&format!("  (return {})", self.operand_expr(operand, context)?));
                Ok(())
            }
            MirTerminatorKind::Return(None) => {
                writer.writeln("  (return)");
                Ok(())
            }
            other => Err(MirWasmTextProbeError::unsupported(terminator_kind_name(other))),
        }
    }

    fn operand_expr(&self, operand: &MirOperand, context: &FunctionContext) -> Result<String, MirWasmTextProbeError> {
        match operand {
            MirOperand::Place(place) => self.place_expr(place, context),
            MirOperand::Value(id) => context
                .values
                .get(id)
                .cloned()
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined value v{}", id.0))),
            MirOperand::Constant(constant) => self.constant_expr(constant),
            MirOperand::Temp(id) => context
                .temps
                .get(id)
                .cloned()
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined temp t{}", id.0))),
        }
    }

    fn place_expr(&self, place: &MirPlace, context: &FunctionContext) -> Result<String, MirWasmTextProbeError> {
        if !place.projections.is_empty() {
            return Err(MirWasmTextProbeError::unsupported("place projection"));
        }
        match place.base {
            MirPlaceBase::Local(id) => Ok(context
                .locals
                .get(&id)
                .cloned()
                .unwrap_or_else(|| format!("(local.get ${})", local_name(id)))),
            MirPlaceBase::Temp(_) => Err(MirWasmTextProbeError::unsupported("temp place")),
        }
    }

    fn constant_expr(&self, constant: &MirConstant) -> Result<String, MirWasmTextProbeError> {
        match constant {
            MirConstant::Int(value) => Ok(format!("(i64.const {value})")),
            MirConstant::Bool(value) => Ok(format!("(i32.const {})", if *value { 1 } else { 0 })),
            MirConstant::Unit => Ok("(i32.const 0)".to_owned()),
            MirConstant::Float(_) => Err(MirWasmTextProbeError::unsupported("float constant")),
            MirConstant::String(_) => Err(MirWasmTextProbeError::unsupported("string constant")),
            MirConstant::Nil => Err(MirWasmTextProbeError::unsupported("nil constant")),
        }
    }

    fn wasm_ty(&self, ty: MirType) -> Result<&'static str, MirWasmTextProbeError> {
        match self.types.get(ty.semantic_id()) {
            Type::Primitive(Primitive::Numerus) => Ok("i64"),
            Type::Primitive(Primitive::Bivalens) => Ok("i32"),
            Type::Alias(_, target) => self.wasm_ty(MirType::semantic(*target)),
            other => Err(MirWasmTextProbeError::unsupported(format!("type {other:?}"))),
        }
    }

    fn wasm_result_ty(&self, ty: MirType) -> Result<Option<&'static str>, MirWasmTextProbeError> {
        match self.types.get(ty.semantic_id()) {
            Type::Primitive(Primitive::Vacuum) => Ok(None),
            _ => self.wasm_ty(ty).map(Some),
        }
    }

    fn function_name(&self, function: &MirFunction) -> String {
        function
            .name
            .map(|symbol| sanitize_name(self.interner.resolve(symbol)))
            .unwrap_or_else(|| format!("f{}", function.id.0))
    }
}

fn local_name(id: MirLocalId) -> String {
    format!("l{}", id.0)
}

fn sanitize_name(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn wasm_bin_op(op: MirBinOp) -> Result<&'static str, MirWasmTextProbeError> {
    match op {
        MirBinOp::Add => Ok("i64.add"),
        MirBinOp::Sub => Ok("i64.sub"),
        MirBinOp::Mul => Ok("i64.mul"),
        MirBinOp::Div => Ok("i64.div_s"),
        MirBinOp::Mod => Ok("i64.rem_s"),
        _ => Err(MirWasmTextProbeError::unsupported(format!("binary op {op:?}"))),
    }
}

fn stmt_kind_name(kind: &MirStmtKind) -> &'static str {
    match kind {
        MirStmtKind::Assign { .. } => "assign",
        MirStmtKind::Call { .. } => "call",
        MirStmtKind::RuntimeCall { .. } => "runtime call",
        MirStmtKind::Construct { .. } => "construct",
    }
}

fn terminator_kind_name(kind: &MirTerminatorKind) -> &'static str {
    match kind {
        MirTerminatorKind::Return(_) => "return",
        MirTerminatorKind::ReturnError(_) => "return_error",
        MirTerminatorKind::TryCall { .. } => "try_call",
        MirTerminatorKind::Goto(_) => "goto",
        MirTerminatorKind::Branch { .. } => "branch",
        MirTerminatorKind::Switch { .. } => "switch",
        MirTerminatorKind::Unreachable => "unreachable",
    }
}

#[cfg(test)]
#[path = "wasm_text_test.rs"]
mod tests;
