//! Experimental WebAssembly text emitter for validated MIR.
//!
//! TARGET: WASM backend lane proof. This emits a deliberately small `.wat`
//! subset from MIR so the target surface can grow in the right architectural
//! place before Faber commits to a full binary module, ABI, or Component Model
//! lowering pass.

use crate::codegen::CodeWriter;
use crate::lexer::Interner;
use crate::mir::*;
use crate::semantic::{Primitive, Type, TypeTable};
use rustc_hash::{FxHashMap, FxHashSet};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MirWasmTextProbeError {
    pub message: String,
}

impl MirWasmTextProbeError {
    fn unsupported(shape: impl Into<String>) -> Self {
        Self { message: format!("MIR-to-WASM unsupported: {}", shape.into()) }
    }
}

impl std::fmt::Display for MirWasmTextProbeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for MirWasmTextProbeError {}

pub fn emit_wasm_text_probe(
    program: &MirProgram,
    types: &TypeTable,
    interner: &Interner,
) -> Result<String, MirWasmTextProbeError> {
    WasmTextProbe { program, types, interner }.emit_program()
}

struct WasmTextProbe<'a> {
    program: &'a MirProgram,
    types: &'a TypeTable,
    interner: &'a Interner,
}

struct FunctionContext {
    values: FxHashMap<MirValueId, String>,
    value_tys: FxHashMap<MirValueId, WasmValue>,
    locals: FxHashMap<MirLocalId, WasmValue>,
    temps: FxHashMap<MirTempId, WasmValue>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
enum WasmValue {
    I32,
    I64,
    F64,
    TextHandle,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
struct DiagnosticImport {
    kind: MirDiagnosticKind,
    value: WasmValue,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct TextFormatImport {
    args: Vec<WasmValue>,
}

enum TerminatorMode {
    SingleBlock,
    Dispatch,
}

impl WasmTextProbe<'_> {
    fn emit_program(&self) -> Result<String, MirWasmTextProbeError> {
        let mut writer = CodeWriter::new();
        writer.writeln(";; Generated by radix MIR WASM text probe - experimental artifact.");
        writer.writeln("(module");
        writer.indent();
        if self.requires_text_concat_import()? {
            writer
                .writeln("(import \"faber_text\" \"concat\" (func $__faber_text_concat (param i32 i32) (result i32)))");
        }
        for import in self.required_text_format_imports()? {
            let params = std::iter::once("i32")
                .chain(import.args.iter().map(|arg| arg.wat()))
                .collect::<Vec<_>>()
                .join(" ");
            writer.writeln(&format!(
                "(import \"faber_text\" \"{}\" (func ${} (param {params}) (result i32)))",
                text_format_import_name(&import),
                text_format_import_symbol(&import),
            ));
        }
        for import in self.required_diagnostic_imports()? {
            writer.writeln(&format!(
                "(import \"faber_diag\" \"{}\" (func ${} (param {})))",
                diagnostic_import_name(import),
                diagnostic_import_symbol(import),
                import.value.wat()
            ));
        }
        for function in &self.program.functions {
            self.emit_function(function, &mut writer)?;
        }
        writer.dedent();
        writer.writeln(")");
        Ok(writer.finish())
    }

    fn emit_function(&self, function: &MirFunction, writer: &mut CodeWriter) -> Result<(), MirWasmTextProbeError> {
        let name = self.function_name(function);
        let mut signature = format!("(func ${name} (export \"{name}\")");
        for param in &function.params {
            signature.push_str(&format!(" (param ${} {})", local_name(param.local), self.wasm_ty(param.ty)?));
        }
        if let Some(result_ty) = self.wasm_result_ty(function.return_ty)? {
            signature.push_str(&format!(" (result {result_ty})"));
        }
        writer.writeln(&signature);
        writer.indent();
        let mut context = self.function_context(function)?;
        let param_locals = function
            .params
            .iter()
            .map(|param| param.local)
            .collect::<FxHashSet<_>>();
        for local in &function.locals {
            if !param_locals.contains(&local.id) {
                writer.writeln(&format!("  (local ${} {})", local_name(local.id), self.wasm_ty(local.ty)?));
            }
        }
        for temp in &function.temps {
            writer.writeln(&format!("  (local ${} {})", temp_name(temp.id), self.wasm_ty(temp.ty)?));
        }
        if function.blocks.len() == 1 && function.blocks[0].id == MirBlockId(0) {
            self.emit_single_block_function(function, &mut context, writer)?;
        } else {
            writer.writeln("  (local $__block i32)");
            self.emit_dispatch_function(function, &mut context, writer)?;
        }
        writer.dedent();
        writer.writeln(")");
        Ok(())
    }

    fn emit_single_block_function(
        &self,
        function: &MirFunction,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirWasmTextProbeError> {
        let block = &function.blocks[0];
        for stmt in &block.statements {
            self.emit_stmt(stmt, context, writer)?;
        }
        self.emit_terminator(&block.terminator, context, writer, TerminatorMode::SingleBlock)
    }

    fn emit_dispatch_function(
        &self,
        function: &MirFunction,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirWasmTextProbeError> {
        writer.writeln("  (local.set $__block (i32.const 0))");
        writer.writeln("  (loop $__dispatch");
        writer.indent();
        for block in &function.blocks {
            writer.writeln(&format!("  (if (i32.eq (local.get $__block) (i32.const {}))", block.id.0));
            writer.indent();
            writer.writeln("  (then");
            writer.indent();
            for stmt in &block.statements {
                self.emit_stmt(stmt, context, writer)?;
            }
            self.emit_terminator(&block.terminator, context, writer, TerminatorMode::Dispatch)?;
            writer.dedent();
            writer.writeln("  )");
            writer.dedent();
            writer.writeln("  )");
        }
        writer.writeln("  (unreachable)");
        writer.dedent();
        writer.writeln("  )");
        writer.writeln("  (unreachable)");
        Ok(())
    }

    fn emit_stmt(
        &self,
        stmt: &MirStmt,
        context: &mut FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirWasmTextProbeError> {
        match &stmt.kind {
            MirStmtKind::Assign { place, value } => {
                let expr = self.value_expr(value, context, writer)?;
                context.values.insert(value.id, expr.clone());
                context
                    .value_tys
                    .insert(value.id, self.scalar_ty(value.ty)?);
                self.emit_place_set(place, &expr, context, writer)
            }
            MirStmtKind::Call { destination, callee, args } => {
                let call = self.call_expr(callee, args, context)?;
                if let Some(destination) = destination {
                    self.emit_place_set(destination, &call, context, writer)
                } else {
                    writer.writeln(&format!("  {call}"));
                    Ok(())
                }
            }
            MirStmtKind::RuntimeCall { destination, call } => match (destination, &call.intrinsic) {
                (None, MirIntrinsic::Diagnostic(kind)) => {
                    let [arg] = call.args.as_slice() else {
                        return Err(MirWasmTextProbeError::unsupported("diagnostic runtime arity"));
                    };
                    let value = self.operand_ty(arg, context)?;
                    let import = DiagnosticImport { kind: *kind, value };
                    let arg = self.operand_expr(arg, context)?;
                    writer.writeln(&format!("  (call ${} {arg})", diagnostic_import_symbol(import)));
                    Ok(())
                }
                (Some(destination), MirIntrinsic::FormatString { template }) => {
                    let expr = self.format_string_call_expr(*template, &call.args, call.return_ty, context)?;
                    self.emit_place_set(destination, &expr, context, writer)
                }
                (Some(_), _) => Err(MirWasmTextProbeError::unsupported("value-returning runtime call")),
                (None, _) => Err(MirWasmTextProbeError::unsupported("runtime call")),
            },
            MirStmtKind::Construct { .. } => Err(MirWasmTextProbeError::unsupported("construct")),
        }
    }

    fn value_expr(
        &self,
        value: &MirValue,
        context: &FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<String, MirWasmTextProbeError> {
        match &value.kind {
            MirValueKind::Operand(operand) => self.operand_expr(operand, context),
            MirValueKind::Binary { op, lhs, rhs } => {
                let lhs_expr = self.operand_expr(lhs, context)?;
                let rhs_expr = self.operand_expr(rhs, context)?;
                let lhs_ty = self.operand_ty(lhs, context)?;
                let expr = if *op == MirBinOp::Add && lhs_ty == WasmValue::TextHandle {
                    format!("(call $__faber_text_concat {lhs_expr} {rhs_expr})")
                } else {
                    let op = wasm_bin_op(*op, lhs_ty)?;
                    format!("({op} {lhs_expr} {rhs_expr})")
                };
                writer.writeln(&format!("  ;; v{} = {expr}", value.id.0));
                Ok(expr)
            }
            MirValueKind::Unary { op, operand } => {
                let operand_expr = self.operand_expr(operand, context)?;
                let operand_ty = self.operand_ty(operand, context)?;
                let expr = wasm_un_op(*op, operand_ty, &operand_expr)?;
                writer.writeln(&format!("  ;; v{} = {expr}", value.id.0));
                Ok(expr)
            }
            MirValueKind::Option(_) => Err(MirWasmTextProbeError::unsupported("option value")),
        }
    }

    fn emit_place_set(
        &self,
        place: &MirPlace,
        expr: &str,
        _context: &FunctionContext,
        writer: &mut CodeWriter,
    ) -> Result<(), MirWasmTextProbeError> {
        if !place.projections.is_empty() {
            return Err(MirWasmTextProbeError::unsupported("place projection"));
        }
        match place.base {
            MirPlaceBase::Local(id) => {
                writer.writeln(&format!("  (local.set ${} {expr})", local_name(id)));
            }
            MirPlaceBase::Temp(id) => {
                writer.writeln(&format!("  (local.set ${} {expr})", temp_name(id)));
            }
        }
        Ok(())
    }

    fn emit_terminator(
        &self,
        terminator: &MirTerminator,
        context: &FunctionContext,
        writer: &mut CodeWriter,
        mode: TerminatorMode,
    ) -> Result<(), MirWasmTextProbeError> {
        match &terminator.kind {
            MirTerminatorKind::Return(Some(operand)) => {
                writer.writeln(&format!("  (return {})", self.operand_expr(operand, context)?));
                Ok(())
            }
            MirTerminatorKind::Return(None) => {
                writer.writeln("  (return)");
                Ok(())
            }
            MirTerminatorKind::Goto(target) if matches!(mode, TerminatorMode::Dispatch) => {
                self.emit_dispatch_jump(*target, writer);
                Ok(())
            }
            MirTerminatorKind::Branch { condition, then_block, else_block }
                if matches!(mode, TerminatorMode::Dispatch) =>
            {
                let condition = self.operand_expr(condition, context)?;
                writer.writeln(&format!("  (if {condition}"));
                writer.indent();
                writer.writeln("  (then");
                writer.indent();
                self.emit_dispatch_jump(*then_block, writer);
                writer.dedent();
                writer.writeln("  )");
                writer.writeln("  (else");
                writer.indent();
                self.emit_dispatch_jump(*else_block, writer);
                writer.dedent();
                writer.writeln("  )");
                writer.dedent();
                writer.writeln("  )");
                Ok(())
            }
            MirTerminatorKind::Unreachable => {
                writer.writeln("  (unreachable)");
                Ok(())
            }
            other => Err(MirWasmTextProbeError::unsupported(terminator_kind_name(other))),
        }
    }

    fn emit_dispatch_jump(&self, target: MirBlockId, writer: &mut CodeWriter) {
        writer.writeln(&format!("  (local.set $__block (i32.const {}))", target.0));
        writer.writeln("  (br $__dispatch)");
    }

    fn operand_expr(&self, operand: &MirOperand, context: &FunctionContext) -> Result<String, MirWasmTextProbeError> {
        match operand {
            MirOperand::Place(place) => self.place_expr(place, context),
            MirOperand::Value(id) => context
                .values
                .get(id)
                .cloned()
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined value v{}", id.0))),
            MirOperand::Constant(constant) => self.constant_expr(constant),
            MirOperand::Temp(id) => context
                .temps
                .get(id)
                .map(|_| format!("(local.get ${})", temp_name(*id)))
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined temp t{}", id.0))),
        }
    }

    fn place_expr(&self, place: &MirPlace, context: &FunctionContext) -> Result<String, MirWasmTextProbeError> {
        if !place.projections.is_empty() {
            return Err(MirWasmTextProbeError::unsupported("place projection"));
        }
        match place.base {
            MirPlaceBase::Local(id) => context
                .locals
                .get(&id)
                .map(|_| format!("(local.get ${})", local_name(id)))
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined local l{}", id.0))),
            MirPlaceBase::Temp(id) => context
                .temps
                .get(&id)
                .map(|_| format!("(local.get ${})", temp_name(id)))
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined temp t{}", id.0))),
        }
    }

    fn operand_ty(&self, operand: &MirOperand, context: &FunctionContext) -> Result<WasmValue, MirWasmTextProbeError> {
        match operand {
            MirOperand::Place(place) => self.place_ty(place, context),
            MirOperand::Value(id) => context
                .value_tys
                .get(id)
                .copied()
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined value v{}", id.0))),
            MirOperand::Constant(MirConstant::Int(_)) => Ok(WasmValue::I64),
            MirOperand::Constant(MirConstant::Float(_)) => Ok(WasmValue::F64),
            MirOperand::Constant(MirConstant::Bool(_)) => Ok(WasmValue::I32),
            MirOperand::Constant(MirConstant::String(_)) => Ok(WasmValue::TextHandle),
            MirOperand::Constant(other) => Err(MirWasmTextProbeError::unsupported(format!("constant {other:?}"))),
            MirOperand::Temp(id) => context
                .temps
                .get(id)
                .copied()
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined temp t{}", id.0))),
        }
    }

    fn place_ty(&self, place: &MirPlace, context: &FunctionContext) -> Result<WasmValue, MirWasmTextProbeError> {
        if !place.projections.is_empty() {
            return Err(MirWasmTextProbeError::unsupported("place projection"));
        }
        match place.base {
            MirPlaceBase::Local(id) => context
                .locals
                .get(&id)
                .copied()
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined local l{}", id.0))),
            MirPlaceBase::Temp(id) => context
                .temps
                .get(&id)
                .copied()
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("undefined temp t{}", id.0))),
        }
    }

    fn constant_expr(&self, constant: &MirConstant) -> Result<String, MirWasmTextProbeError> {
        match constant {
            MirConstant::Int(value) => Ok(format!("(i64.const {value})")),
            MirConstant::Float(value) => Ok(format!("(f64.const {value:?})")),
            MirConstant::Bool(value) => Ok(format!("(i32.const {})", if *value { 1 } else { 0 })),
            MirConstant::String(symbol) => Ok(format!("(i32.const {})", symbol.0)),
            MirConstant::Unit => Ok("(i32.const 0)".to_owned()),
            MirConstant::Nil => Err(MirWasmTextProbeError::unsupported("nil constant")),
        }
    }

    fn wasm_ty(&self, ty: MirType) -> Result<&'static str, MirWasmTextProbeError> {
        self.scalar_ty(ty).map(WasmValue::wat)
    }

    fn wasm_result_ty(&self, ty: MirType) -> Result<Option<&'static str>, MirWasmTextProbeError> {
        match self.types.get(ty.semantic_id()) {
            Type::Primitive(Primitive::Vacuum) => Ok(None),
            _ => self.wasm_ty(ty).map(Some),
        }
    }

    fn function_name(&self, function: &MirFunction) -> String {
        function
            .name
            .map(|symbol| sanitize_name(self.interner.resolve(symbol)))
            .unwrap_or_else(|| format!("f{}", function.id.0))
    }

    fn function_context(&self, function: &MirFunction) -> Result<FunctionContext, MirWasmTextProbeError> {
        let mut locals = FxHashMap::default();
        for local in &function.locals {
            locals.insert(local.id, self.scalar_ty(local.ty)?);
        }
        let mut temps = FxHashMap::default();
        for temp in &function.temps {
            temps.insert(temp.id, self.scalar_ty(temp.ty)?);
        }
        let mut value_tys = FxHashMap::default();
        for block in &function.blocks {
            for stmt in &block.statements {
                if let MirStmtKind::Assign { value, .. } = &stmt.kind {
                    value_tys.insert(value.id, self.scalar_ty(value.ty)?);
                }
            }
        }
        Ok(FunctionContext { values: FxHashMap::default(), value_tys, locals, temps })
    }

    fn scalar_ty(&self, ty: MirType) -> Result<WasmValue, MirWasmTextProbeError> {
        match self.types.get(ty.semantic_id()) {
            Type::Primitive(Primitive::Numerus) => Ok(WasmValue::I64),
            Type::Primitive(Primitive::Fractus) => Ok(WasmValue::F64),
            Type::Primitive(Primitive::Bivalens) => Ok(WasmValue::I32),
            Type::Primitive(Primitive::Textus) => Ok(WasmValue::TextHandle),
            Type::Alias(_, target) => self.scalar_ty(MirType::semantic(*target)),
            other => Err(MirWasmTextProbeError::unsupported(format!("type {other:?}"))),
        }
    }

    fn call_expr(
        &self,
        callee: &MirCallee,
        args: &[MirOperand],
        context: &FunctionContext,
    ) -> Result<String, MirWasmTextProbeError> {
        let callee = self.callee_name(callee)?;
        let mut call = format!("(call ${callee}");
        for arg in args {
            call.push(' ');
            call.push_str(&self.operand_expr(arg, context)?);
        }
        call.push(')');
        Ok(call)
    }

    fn format_string_call_expr(
        &self,
        template: crate::lexer::Symbol,
        args: &[MirOperand],
        return_ty: MirType,
        context: &FunctionContext,
    ) -> Result<String, MirWasmTextProbeError> {
        if self.scalar_ty(return_ty)? != WasmValue::TextHandle {
            return Err(MirWasmTextProbeError::unsupported("format string return type"));
        }
        let import = TextFormatImport {
            args: args
                .iter()
                .map(|arg| self.operand_ty(arg, context))
                .collect::<Result<Vec<_>, _>>()?,
        };
        let mut call = format!("(call ${} (i32.const {})", text_format_import_symbol(&import), template.0);
        for arg in args {
            call.push(' ');
            call.push_str(&self.operand_expr(arg, context)?);
        }
        call.push(')');
        Ok(call)
    }

    fn callee_name(&self, callee: &MirCallee) -> Result<String, MirWasmTextProbeError> {
        match callee {
            MirCallee::Function(id) => self
                .program
                .functions
                .iter()
                .find(|function| function.id == *id)
                .map(|function| self.function_name(function))
                .ok_or_else(|| MirWasmTextProbeError::unsupported(format!("unknown function f{}", id.0))),
            MirCallee::Definition(def_id) => self
                .program
                .functions
                .iter()
                .find(|function| function.source == Some(*def_id))
                .map(|function| self.function_name(function))
                .ok_or_else(|| MirWasmTextProbeError::unsupported("external definition call")),
            MirCallee::Value(_) => Err(MirWasmTextProbeError::unsupported("value callee")),
        }
    }

    fn required_diagnostic_imports(&self) -> Result<Vec<DiagnosticImport>, MirWasmTextProbeError> {
        let mut imports = FxHashSet::default();
        for function in &self.program.functions {
            let context = self.function_context(function)?;
            for block in &function.blocks {
                for stmt in &block.statements {
                    let MirStmtKind::RuntimeCall { destination, call } = &stmt.kind else {
                        continue;
                    };
                    if destination.is_some() {
                        continue;
                    }
                    let MirIntrinsic::Diagnostic(kind) = call.intrinsic else {
                        continue;
                    };
                    let [arg] = call.args.as_slice() else {
                        continue;
                    };
                    imports.insert(DiagnosticImport { kind, value: self.operand_ty(arg, &context)? });
                }
            }
        }
        let mut imports = imports.into_iter().collect::<Vec<_>>();
        imports.sort_by_key(|import| diagnostic_import_name(*import));
        Ok(imports)
    }

    fn requires_text_concat_import(&self) -> Result<bool, MirWasmTextProbeError> {
        for function in &self.program.functions {
            let context = self.function_context(function)?;
            for block in &function.blocks {
                for stmt in &block.statements {
                    let MirStmtKind::Assign { value, .. } = &stmt.kind else {
                        continue;
                    };
                    let MirValueKind::Binary { op: MirBinOp::Add, lhs, .. } = &value.kind else {
                        continue;
                    };
                    if self.operand_ty(lhs, &context)? == WasmValue::TextHandle {
                        return Ok(true);
                    }
                }
            }
        }
        Ok(false)
    }

    fn required_text_format_imports(&self) -> Result<Vec<TextFormatImport>, MirWasmTextProbeError> {
        let mut imports = FxHashSet::default();
        for function in &self.program.functions {
            let context = self.function_context(function)?;
            for block in &function.blocks {
                for stmt in &block.statements {
                    let MirStmtKind::RuntimeCall { destination: Some(_), call } = &stmt.kind else {
                        continue;
                    };
                    if !matches!(call.intrinsic, MirIntrinsic::FormatString { .. }) {
                        continue;
                    }
                    if self.scalar_ty(call.return_ty)? != WasmValue::TextHandle {
                        continue;
                    }
                    imports.insert(TextFormatImport {
                        args: call
                            .args
                            .iter()
                            .map(|arg| self.operand_ty(arg, &context))
                            .collect::<Result<Vec<_>, _>>()?,
                    });
                }
            }
        }
        let mut imports = imports.into_iter().collect::<Vec<_>>();
        imports.sort_by_key(text_format_import_name);
        Ok(imports)
    }
}

fn local_name(id: MirLocalId) -> String {
    format!("l{}", id.0)
}

fn temp_name(id: MirTempId) -> String {
    format!("t{}", id.0)
}

fn sanitize_name(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn wasm_bin_op(op: MirBinOp, lhs_ty: WasmValue) -> Result<&'static str, MirWasmTextProbeError> {
    match op {
        MirBinOp::Add if lhs_ty == WasmValue::I64 => Ok("i64.add"),
        MirBinOp::Sub if lhs_ty == WasmValue::I64 => Ok("i64.sub"),
        MirBinOp::Mul if lhs_ty == WasmValue::I64 => Ok("i64.mul"),
        MirBinOp::Div if lhs_ty == WasmValue::I64 => Ok("i64.div_s"),
        MirBinOp::Mod if lhs_ty == WasmValue::I64 => Ok("i64.rem_s"),
        MirBinOp::Add if lhs_ty == WasmValue::F64 => Ok("f64.add"),
        MirBinOp::Sub if lhs_ty == WasmValue::F64 => Ok("f64.sub"),
        MirBinOp::Mul if lhs_ty == WasmValue::F64 => Ok("f64.mul"),
        MirBinOp::Div if lhs_ty == WasmValue::F64 => Ok("f64.div"),
        MirBinOp::Eq if lhs_ty == WasmValue::I64 => Ok("i64.eq"),
        MirBinOp::NotEq if lhs_ty == WasmValue::I64 => Ok("i64.ne"),
        MirBinOp::Lt if lhs_ty == WasmValue::I64 => Ok("i64.lt_s"),
        MirBinOp::Gt if lhs_ty == WasmValue::I64 => Ok("i64.gt_s"),
        MirBinOp::LtEq if lhs_ty == WasmValue::I64 => Ok("i64.le_s"),
        MirBinOp::GtEq if lhs_ty == WasmValue::I64 => Ok("i64.ge_s"),
        MirBinOp::Eq if lhs_ty == WasmValue::F64 => Ok("f64.eq"),
        MirBinOp::NotEq if lhs_ty == WasmValue::F64 => Ok("f64.ne"),
        MirBinOp::Lt if lhs_ty == WasmValue::F64 => Ok("f64.lt"),
        MirBinOp::Gt if lhs_ty == WasmValue::F64 => Ok("f64.gt"),
        MirBinOp::LtEq if lhs_ty == WasmValue::F64 => Ok("f64.le"),
        MirBinOp::GtEq if lhs_ty == WasmValue::F64 => Ok("f64.ge"),
        MirBinOp::Eq if lhs_ty == WasmValue::I32 => Ok("i32.eq"),
        MirBinOp::NotEq if lhs_ty == WasmValue::I32 => Ok("i32.ne"),
        MirBinOp::And => Ok("i32.and"),
        MirBinOp::Or => Ok("i32.or"),
        _ => Err(MirWasmTextProbeError::unsupported(format!("binary op {op:?}"))),
    }
}

fn wasm_un_op(op: MirUnOp, operand_ty: WasmValue, operand: &str) -> Result<String, MirWasmTextProbeError> {
    match (op, operand_ty) {
        (MirUnOp::Neg, WasmValue::I64) => Ok(format!("(i64.sub (i64.const 0) {operand})")),
        (MirUnOp::Neg, WasmValue::F64) => Ok(format!("(f64.neg {operand})")),
        (MirUnOp::Not, WasmValue::I32) => Ok(format!("(i32.eqz {operand})")),
        (MirUnOp::BitNot, WasmValue::I64) => Ok(format!("(i64.xor {operand} (i64.const -1))")),
        _ => Err(MirWasmTextProbeError::unsupported(format!("unary op {op:?}"))),
    }
}

impl WasmValue {
    fn wat(self) -> &'static str {
        match self {
            WasmValue::I32 | WasmValue::TextHandle => "i32",
            WasmValue::I64 => "i64",
            WasmValue::F64 => "f64",
        }
    }

    fn abi_name(self) -> &'static str {
        match self {
            WasmValue::I32 => "i32",
            WasmValue::I64 => "i64",
            WasmValue::F64 => "f64",
            WasmValue::TextHandle => "text",
        }
    }
}

fn text_format_import_name(import: &TextFormatImport) -> String {
    let suffix = if import.args.is_empty() {
        "0".to_owned()
    } else {
        let args = import
            .args
            .iter()
            .map(|arg| arg.abi_name())
            .collect::<Vec<_>>()
            .join("_");
        format!("{}_{}", import.args.len(), args)
    };
    format!("format_{suffix}")
}

fn text_format_import_symbol(import: &TextFormatImport) -> String {
    format!("__faber_text_{}", text_format_import_name(import))
}

fn diagnostic_import_name(import: DiagnosticImport) -> &'static str {
    match (import.kind, import.value) {
        (MirDiagnosticKind::Nota, WasmValue::I32) => "nota_i32",
        (MirDiagnosticKind::Nota, WasmValue::I64) => "nota_i64",
        (MirDiagnosticKind::Nota, WasmValue::F64) => "nota_f64",
        (MirDiagnosticKind::Nota, WasmValue::TextHandle) => "nota_text",
        (MirDiagnosticKind::Vide, WasmValue::I32) => "vide_i32",
        (MirDiagnosticKind::Vide, WasmValue::I64) => "vide_i64",
        (MirDiagnosticKind::Vide, WasmValue::F64) => "vide_f64",
        (MirDiagnosticKind::Vide, WasmValue::TextHandle) => "vide_text",
        (MirDiagnosticKind::Mone, WasmValue::I32) => "mone_i32",
        (MirDiagnosticKind::Mone, WasmValue::I64) => "mone_i64",
        (MirDiagnosticKind::Mone, WasmValue::F64) => "mone_f64",
        (MirDiagnosticKind::Mone, WasmValue::TextHandle) => "mone_text",
        (MirDiagnosticKind::Scribe, WasmValue::I32) => "scribe_i32",
        (MirDiagnosticKind::Scribe, WasmValue::I64) => "scribe_i64",
        (MirDiagnosticKind::Scribe, WasmValue::F64) => "scribe_f64",
        (MirDiagnosticKind::Scribe, WasmValue::TextHandle) => "scribe_text",
    }
}

fn diagnostic_import_symbol(import: DiagnosticImport) -> String {
    format!("__faber_diag_{}", diagnostic_import_name(import))
}

fn terminator_kind_name(kind: &MirTerminatorKind) -> &'static str {
    match kind {
        MirTerminatorKind::Return(_) => "return",
        MirTerminatorKind::ReturnError(_) => "return_error",
        MirTerminatorKind::TryCall { .. } => "try_call",
        MirTerminatorKind::Goto(_) => "goto",
        MirTerminatorKind::Branch { .. } => "branch",
        MirTerminatorKind::Switch { .. } => "switch",
        MirTerminatorKind::Unreachable => "unreachable",
    }
}

#[cfg(test)]
#[path = "wasm_text_test.rs"]
mod tests;
