mod types;

use super::{CodeWriter, Codegen, CodegenError};
use crate::hir::{DefId, HirItemKind, HirProgram};
use crate::lexer::{Interner, Symbol};
use crate::semantic::TypeTable;
use crate::TypeScriptOutput;
use rustc_hash::FxHashMap;

pub struct TsCodegen<'a> {
    names: FxHashMap<DefId, Symbol>,
    interner: &'a Interner,
}

impl<'a> TsCodegen<'a> {
    pub fn new(hir: &HirProgram, interner: &'a Interner) -> Self {
        let mut codegen = Self { names: FxHashMap::default(), interner };
        codegen.names = codegen.collect_names(hir);
        codegen
    }

    pub(super) fn resolve_symbol(&self, sym: Symbol) -> &str {
        self.interner.resolve(sym)
    }

    pub(super) fn resolve_def(&self, def_id: DefId) -> &str {
        self.names
            .get(&def_id)
            .map(|sym| self.resolve_symbol(*sym))
            .unwrap_or("unresolved_def")
    }

    fn collect_names(&self, hir: &HirProgram) -> FxHashMap<DefId, Symbol> {
        let mut names = FxHashMap::default();
        for item in &hir.items {
            match &item.kind {
                HirItemKind::Function(func) => {
                    names.insert(item.def_id, func.name);
                    for type_param in &func.type_params {
                        names.insert(type_param.def_id, type_param.name);
                    }
                    for param in &func.params {
                        names.insert(param.def_id, param.name);
                    }
                }
                HirItemKind::Struct(strukt) => {
                    names.insert(item.def_id, strukt.name);
                    for type_param in &strukt.type_params {
                        names.insert(type_param.def_id, type_param.name);
                    }
                    for field in &strukt.fields {
                        names.insert(field.def_id, field.name);
                    }
                    for method in &strukt.methods {
                        names.insert(method.def_id, method.func.name);
                        for type_param in &method.func.type_params {
                            names.insert(type_param.def_id, type_param.name);
                        }
                        for param in &method.func.params {
                            names.insert(param.def_id, param.name);
                        }
                    }
                }
                HirItemKind::Enum(enum_item) => {
                    names.insert(item.def_id, enum_item.name);
                    for type_param in &enum_item.type_params {
                        names.insert(type_param.def_id, type_param.name);
                    }
                    for variant in &enum_item.variants {
                        names.insert(variant.def_id, variant.name);
                    }
                }
                HirItemKind::Interface(interface) => {
                    names.insert(item.def_id, interface.name);
                    for type_param in &interface.type_params {
                        names.insert(type_param.def_id, type_param.name);
                    }
                }
                HirItemKind::TypeAlias(alias) => {
                    names.insert(item.def_id, alias.name);
                }
                HirItemKind::Const(const_item) => {
                    names.insert(item.def_id, const_item.name);
                }
                HirItemKind::Import(import) => {
                    for item in &import.items {
                        names.insert(item.def_id, item.alias.unwrap_or(item.name));
                    }
                }
            }
        }
        names
    }
}

impl Codegen for TsCodegen<'_> {
    type Output = TypeScriptOutput;

    fn generate(
        &self,
        _hir: &HirProgram,
        _types: &TypeTable,
        _interner: &Interner,
    ) -> Result<TypeScriptOutput, CodegenError> {
        let mut w = CodeWriter::new();
        w.writeln("// Generated by radix - do not edit");
        Ok(TypeScriptOutput { code: w.finish() })
    }
}

#[cfg(test)]
#[path = "mod_test.rs"]
mod tests;
