// Generated by radix - do not edit

const x: number = 2;

(() => {
    {
        ((x > 2) ? (() => { return 10;
         })() : (() => { return ((x === 2) ? (() => { return 20;
         })() : (() => { return 30;
         })()); })());
        undefined;
    }})();

