canonical_terms = [
  "ab",
  "abstractus",
  "ad",
  "adfirma",
  "alias",
  "⊜",
  "∧",
  "ante",
  "arena",
  "argumenta",
  "→",
  "⇥",
  "←",
  "@",
  "aut",
  "bivalens",
  "![",
  "!.",
  "≠",
  "!(",
  "cape",
  "⊻",
  "casu",
  "cede",
  "ceteri",
  "ceterum",
  "clausura",
  "cli",
  "⇒",
  "copia",
  "cura",
  "curata",
  "cursor",
  "custodi",
  "de",
  "descriptio",
  "≫",
  "discerne",
  "discretio",
  "‥",
  "dum",
  "ego",
  "elige",
  "…",
  "≡",
  "=",
  "errata",
  "est",
  "et",
  "ex",
  "exitus",
  "fac",
  "falsum",
  "finge",
  "fixum",
  "fixus",
  "fragilis",
  "fractus",
  "functio",
  "futura",
  "futurum",
  "generis",
  "genus",
  "≥",
  "iace",
  "iacit",
  "ignotum",
  "immutata",
  "imperia",
  "imperium",
  "implet",
  "importa",
  "in",
  "incipiet",
  "incipit",
  "inter",
  "intra",
  "itera",
  "lege",
  "lineam",
  "≤",
  "lista",
  "manifest",
  "metior",
  "⊖",
  "mone",
  "mori",
  "negativum",
  "nexum",
  "nihil",
  "numquam",
  "numerus",
  "non est",
  "non",
  "nonnihil",
  "nonnulla",
  "nulla",
  "omitte",
  "omnia",
  "operandus",
  "optio",
  "optiones",
  "ordo",
  "objectum",
  "octeti",
  "pactum",
  "per",
  "perge",
  "⊚",
  "∨",
  "∪",
  "⊕",
  "positivum",
  "postpara",
  "postparabit",
  "prae",
  "praefixum",
  "praepara",
  "praeparabit",
  "prima",
  "promissum",
  "privata",
  "pro",
  "proba",
  "probandum",
  "protecta",
  "publica",
  "?[",
  "?.",
  "?(",
  "redde",
  "repete",
  "requirit",
  "rumpe",
  "scribe",
  "scriptum",
  "string",
  "block-string",
  "§",
  "secus",
  "sed",
  "si",
  "sic",
  "sin",
  "≪",
  "⊘",
  "solum_in",
  "solum",
  "sparge",
  "sponte",
  "⊛",
  "sub",
  "summa",
  "tacet",
  "tabula",
  "tag",
  "temporis",
  "targets",
  "textus",
  "¬",
  "typus",
  "ubi",
  "ubique",
  "ultima",
  "usque",
  "ut",
  "varia",
  "vel",
  "versio",
  "⇢",
  "vacuum",
  "verum",
  "vide",
  "∴",
]

legacy_terms = [
  "==",
  "!=",
  "<=",
  ">=",
  "->",
  "===",
  "!==",
  "demum",
  "tempta",
]

excluded_terms = [
  "+",
  "-",
  "*",
  "/",
  "%",
]
