//! Rust Code Generation
//!
//! ARCHITECTURE OVERVIEW
//! =====================
//! This module implements Faber-to-Rust transpilation. It transforms HIR into
//! idiomatic Rust source code, handling error propagation (Result<T, String>),
//! reference modes (de/in/ex), and async/await desugaring.
//!
//! COMPILER PHASE: Codegen
//! INPUT: HirProgram (fully-analyzed HIR), TypeTable, Interner
//! OUTPUT: RustOutput (compilable Rust source code)
//!
//! DESIGN PHILOSOPHY
//! =================
//! - Idiomatic Rust: Generate code that a Rust programmer would write.
//!   WHY: Output should integrate seamlessly with existing Rust ecosystems.
//! - Error propagation analysis: Automatically determine which functions return Result.
//!   WHY: Faber's `iace` (throw) requires Result wrapper; propagate upward transitively.
//! - Reference mode mapping: Translate de/in/ex to &T, &mut T, and owned T.
//!   WHY: Faber's borrow semantics map directly to Rust's ownership system.
//!
//! TRADE-OFFS
//! ==========
//! - All failable functions use String error type (simple but untyped).
//! - Imports are collected post-codegen by scanning output text (avoids complex tracking).
//! - Entry point `incipit` blocks never propagate errors (always use panic! for throws).

mod decl;
mod expr;
mod failable;
mod stmt;
mod types;

use super::{names::NameCatalog, CodeWriter, Codegen, CodegenError};
use crate::hir::{DefId, HirItem, HirItemKind, HirProgram};
use crate::lexer::{Interner, Symbol};
use crate::semantic::TypeTable;
use crate::RustOutput;
use rustc_hash::FxHashSet;
use std::collections::BTreeSet;

// =============================================================================
// CORE
// =============================================================================
//
// The RustCodegen struct pre-computes name resolution and failable function
// analysis during construction, then uses this information during generation.
// This two-phase approach simplifies code generation logic.

/// Rust code generator.
///
/// WHY: Holds pre-analyzed state (names, failable functions) to enable correct
/// error propagation and reference resolution during code generation.
pub struct RustCodegen<'a> {
    /// DefId -> Symbol map for all definitions plus symbol resolution.
    names: NameCatalog<'a>,

    /// Set of DefIds for functions that can throw (return Result)
    failable_defs: FxHashSet<DefId>,
}

impl<'a> RustCodegen<'a> {
    pub fn new(hir: &HirProgram, interner: &'a Interner) -> Self {
        let mut codegen = Self { names: NameCatalog::new(hir, interner), failable_defs: FxHashSet::default() };
        codegen.failable_defs = codegen.collect_failable_functions(hir);
        codegen
    }

    fn generate_prelude(&self, w: &mut CodeWriter, imports: &BTreeSet<String>) {
        w.writeln("// Generated by radix - do not edit");
        w.newline();
        w.writeln("#![allow(unused_imports)]");
        w.writeln("#![allow(unused_variables)]");
        w.writeln("#![allow(dead_code)]");
        w.newline();

        for import in imports {
            w.write("use ");
            w.write(import);
            w.writeln(";");
        }

        if !imports.is_empty() {
            w.newline();
        }
    }

    pub(super) fn resolve_symbol(&self, sym: Symbol) -> &str {
        self.names.resolve_symbol(sym)
    }

    pub(super) fn resolve_def(&self, def_id: DefId) -> &str {
        self.names.resolve_def(def_id)
    }

    pub(super) fn is_failable_def(&self, def_id: DefId) -> bool {
        self.failable_defs.contains(&def_id)
    }

    pub(super) fn is_failable_method_name(&self, method: Symbol) -> bool {
        self.names
            .iter()
            .any(|(def_id, name)| *name == method && self.failable_defs.contains(def_id))
    }

    fn generate_item(&self, item: &HirItem, types: &TypeTable, w: &mut CodeWriter) -> Result<(), CodegenError> {
        match &item.kind {
            HirItemKind::Function(func) => {
                decl::generate_function(self, item.def_id, func, types, w)?;
            }
            HirItemKind::Struct(s) => {
                decl::generate_struct(self, s, types, w)?;
            }
            HirItemKind::Enum(e) => {
                decl::generate_enum(self, e, types, w)?;
            }
            HirItemKind::Interface(i) => {
                decl::generate_trait(self, i, types, w)?;
            }
            HirItemKind::TypeAlias(a) => {
                decl::generate_type_alias(self, a, types, w)?;
            }
            HirItemKind::Const(c) => {
                decl::generate_const(self, c, types, w)?;
            }
            HirItemKind::Import(_) => {
                // Handled in prelude or use statements
            }
        }
        Ok(())
    }

    /// Transitively compute which functions can throw errors.
    ///
    /// WHY: Functions that call throwing functions must propagate Result, but
    /// this is a transitive property requiring fixed-point analysis. We compute
    /// it upfront to avoid repeated traversals during codegen.
    ///
    /// EDGE: `tempta` with catch block suppresses error propagation from body.
    fn collect_failable_functions(&self, hir: &HirProgram) -> FxHashSet<DefId> {
        failable::collect_failable_functions(self, hir)
    }
}

fn normalize_import_path(path: &str) -> String {
    let canonical = path.replace("::", "/");
    if canonical.starts_with('@') {
        return String::new();
    }

    let mut segments = Vec::new();
    for segment in canonical.split('/') {
        if segment.is_empty() || segment == "." || segment == ".." {
            continue;
        }
        segments.push(segment);
    }

    if segments.is_empty() {
        return String::new();
    }

    if matches!(segments[0], "crate" | "self" | "super" | "std" | "core" | "alloc") {
        return segments.join("::");
    }

    format!("crate::{}", segments.join("::"))
}

// =============================================================================
// HELPERS
// =============================================================================
//
// Import collection is done post-codegen by scanning the generated source text.
// WHY: Simpler than tracking imports during traversal; Rust types are known ahead.

/// Scan generated code for Rust types that require imports.
///
/// WHY: HashMap/HashSet aren't in Rust prelude; auto-import them if used.
fn collect_prelude_imports(code: &str) -> BTreeSet<String> {
    let mut imports = BTreeSet::new();
    if code.contains("HashMap<") {
        imports.insert("std::collections::HashMap".to_owned());
    }
    if code.contains("HashSet<") {
        imports.insert("std::collections::HashSet".to_owned());
    }
    if code.contains("Future<Output =") {
        imports.insert("std::future::Future".to_owned());
    }
    imports
}

fn collect_hir_imports(codegen: &RustCodegen<'_>, hir: &HirProgram) -> BTreeSet<String> {
    let mut imports = BTreeSet::new();
    for item in &hir.items {
        let HirItemKind::Import(import) = &item.kind else {
            continue;
        };

        let path = normalize_import_path(codegen.resolve_symbol(import.path));
        if path.is_empty() {
            continue;
        }

        for import_item in &import.items {
            let name = codegen.resolve_symbol(import_item.name);
            if let Some(alias) = import_item.alias {
                let alias_name = codegen.resolve_symbol(alias);
                if alias_name == name {
                    imports.insert(format!("{path} as {alias_name}"));
                } else {
                    imports.insert(format!("{path}::{name} as {alias_name}"));
                }
            } else {
                imports.insert(format!("{path}::{name}"));
            }
        }
    }
    imports
}

impl Codegen for RustCodegen<'_> {
    type Output = RustOutput;

    fn generate(&self, hir: &HirProgram, types: &TypeTable, _interner: &Interner) -> Result<RustOutput, CodegenError> {
        self.generate_output(hir, types, false)
    }
}

impl RustCodegen<'_> {
    fn generate_output(
        &self,
        hir: &HirProgram,
        types: &TypeTable,
        module_mode: bool,
    ) -> Result<RustOutput, CodegenError> {
        let mut body = CodeWriter::new();

        for item in &hir.items {
            self.generate_item(item, types, &mut body)?;
            body.newline();
        }

        // Generate main if there's an entry point
        if let Some(entry) = &hir.entry {
            body.writeln("fn main() {");
            let mut entry_result = Ok(());
            body.indented(|w| {
                for stmt in &entry.stmts {
                    if entry_result.is_err() {
                        return;
                    }
                    entry_result = stmt::generate_stmt(self, stmt, types, w, false, true, false);
                }
                if let Some(expr) = &entry.expr {
                    if entry_result.is_err() {
                        return;
                    }
                    entry_result = expr::generate_expr(self, expr, types, w, false, true, false);
                    w.writeln(";");
                }
            });
            entry_result?;
            body.writeln("}");
        }

        let body_code = body.finish();
        let mut imports = collect_hir_imports(self, hir);
        imports.extend(collect_prelude_imports(&body_code));

        let mut w = CodeWriter::new();
        if module_mode {
            for import in &imports {
                w.write("use ");
                w.write(import);
                w.writeln(";");
            }
            if !imports.is_empty() {
                w.newline();
            }
        } else {
            self.generate_prelude(&mut w, &imports);
        }
        w.write(&body_code);

        Ok(RustOutput { code: w.finish() })
    }
}

pub fn generate_module(hir: &HirProgram, types: &TypeTable, interner: &Interner) -> Result<RustOutput, CodegenError> {
    super::reject_hir_errors(hir)?;
    RustCodegen::new(hir, interner).generate_output(hir, types, true)
}

#[cfg(test)]
#[path = "mod_test.rs"]
mod tests;
