//! Generated Rust prelude, imports, and helper type emission.

use super::RustCodegen;
use crate::codegen::CodeWriter;
use crate::hir::visit::{walk_expr, HirVisitor};
use crate::hir::{HirBlock, HirExpr, HirExprKind, HirItemKind, HirProgram};
use std::collections::BTreeSet;

pub(super) fn generate_prelude(writer: &mut CodeWriter, imports: &BTreeSet<String>) {
    writer.writeln("// Generated by radix - do not edit");
    writer.newline();
    writer.writeln("#![allow(unused_imports)]");
    writer.writeln("#![allow(unused_variables)]");
    writer.writeln("#![allow(dead_code)]");
    writer.writeln("#![allow(non_snake_case)]");
    writer.newline();

    for import in imports {
        if matches!(import.as_str(), "__faber_value" | "__faber_ad") {
            continue;
        }
        writer.write("use ");
        writer.write(import);
        writer.writeln(";");
    }

    if !imports.is_empty() {
        writer.newline();
    }

    if imports.contains("__faber_value") {
        generate_faber_value_helper(writer);
        writer.newline();
    }
    if imports.contains("__faber_ad") {
        generate_faber_ad_helper(writer);
        writer.newline();
    }
}

fn normalize_import_path(path: &str) -> String {
    let canonical = path.replace("::", "/");
    if canonical.starts_with('@') {
        return String::new();
    }

    let mut segments = Vec::new();
    for segment in canonical.split('/') {
        if segment.is_empty() || segment == "." || segment == ".." {
            continue;
        }
        segments.push(segment);
    }

    if segments.is_empty() {
        return String::new();
    }

    if matches!(segments[0], "crate" | "self" | "super" | "std" | "core" | "alloc") {
        return segments.join("::");
    }

    format!("crate::{}", segments.join("::"))
}

/// Scan generated code for Rust types that require imports.
///
/// WHY: this backend keeps import emission at the generated-output boundary.
/// Explicit source imports are available from HIR, but helper types such as
/// `HashMap`, `HashSet`, and `Future` arise from Rust lowering decisions in
/// sub-emitters. Scanning the completed body keeps that target policy local
/// without threading an import accumulator through every expression path.
pub(super) fn collect_prelude_imports(code: &str) -> BTreeSet<String> {
    let mut imports = BTreeSet::new();
    if code.contains("HashMap<") {
        imports.insert("std::collections::HashMap".to_owned());
    }
    if code.contains("HashSet<") {
        imports.insert("std::collections::HashSet".to_owned());
    }
    if code.contains("Future<Output =") {
        imports.insert("std::future::Future".to_owned());
    }
    if code.contains("FaberValue") {
        imports.insert("__faber_value".to_owned());
    }
    if code.contains("__faber_ad::<") {
        imports.insert("__faber_ad".to_owned());
    }
    imports
}

fn generate_faber_ad_helper(writer: &mut CodeWriter) {
    writer.writeln("#[cfg(target_arch = \"wasm32\")]");
    writer.writeln("#[link(wasm_import_module = \"\")]");
    writer.writeln("extern \"C\" {");
    writer.indented(|writer| {
        writer.writeln("#[link_name = \"capability-call\"]");
        writer.writeln("fn __faber_syscall(route_code: i32) -> i32;");
        writer.writeln("#[link_name = \"capability-text-len\"]");
        writer.writeln("fn __faber_syscall_text_len() -> usize;");
        writer.writeln("#[link_name = \"capability-text-read\"]");
        writer.writeln("fn __faber_syscall_text_read(ptr: *mut u8, len: usize) -> usize;");
    });
    writer.writeln("}");
    writer.newline();
    writer.writeln("#[cfg(target_arch = \"wasm32\")]");
    writer.writeln("trait __FaberAdResult {");
    writer.indented(|writer| {
        writer.writeln("fn __faber_from_syscall() -> Self;");
    });
    writer.writeln("}");
    writer.newline();
    writer.writeln("#[cfg(target_arch = \"wasm32\")]");
    writer.writeln("impl __FaberAdResult for () {");
    writer.indented(|writer| {
        writer.writeln("fn __faber_from_syscall() -> Self {}");
    });
    writer.writeln("}");
    writer.newline();
    writer.writeln("#[cfg(target_arch = \"wasm32\")]");
    writer.writeln("impl __FaberAdResult for String {");
    writer.indented(|writer| {
        writer.writeln("fn __faber_from_syscall() -> Self {");
        writer.indented(|writer| {
            writer.writeln("let len = unsafe { __faber_syscall_text_len() };");
            writer.writeln("let mut bytes = vec![0_u8; len];");
            writer.writeln("let written = unsafe { __faber_syscall_text_read(bytes.as_mut_ptr(), bytes.len()) };");
            writer.writeln("bytes.truncate(written);");
            writer.writeln("String::from_utf8(bytes).unwrap_or_default()");
        });
        writer.writeln("}");
    });
    writer.writeln("}");
    writer.newline();
    writer.writeln("#[cfg(target_arch = \"wasm32\")]");
    writer.writeln("fn __faber_ad<T, A>(capability: &str, _args: A) -> Result<T, String>");
    writer.writeln("where");
    writer.indented(|writer| {
        writer.writeln("T: __FaberAdResult,");
    });
    writer.writeln("{");
    writer.indented(|writer| {
        writer.writeln("let route_code = __faber_ad_route_code(capability)?;");
        writer.writeln("let status = unsafe { __faber_syscall(route_code) };");
        writer.writeln("if status == 0 {");
        writer.indented(|writer| {
            writer.writeln("Ok(T::__faber_from_syscall())");
        });
        writer.writeln("} else {");
        writer.indented(|writer| {
            writer.writeln("Err(format!(\"E_NO_ROUTE: unresolved capability {}\", capability))");
        });
        writer.writeln("}");
    });
    writer.writeln("}");
    writer.newline();
    writer.writeln("#[cfg(target_arch = \"wasm32\")]");
    writer.writeln("fn __faber_ad_route_code(capability: &str) -> Result<i32, String> {");
    writer.indented(|writer| {
        writer.writeln("match capability {");
        writer.indented(|writer| {
            writer.writeln("\"host:echo\" => Ok(1),");
            writer.writeln("\"pg:query\" => Ok(2),");
            writer.writeln("_ => Err(format!(\"E_NO_ROUTE: unresolved capability {}\", capability)),");
        });
        writer.writeln("}");
    });
    writer.writeln("}");
    writer.newline();
    writer.writeln("#[cfg(not(target_arch = \"wasm32\"))]");
    writer.writeln("fn __faber_ad<T, A>(capability: &str, _args: A) -> Result<T, String> {");
    writer.indented(|writer| {
        writer.writeln("Err(format!(\"E_NO_ROUTE: unresolved capability {}\", capability))");
    });
    writer.writeln("}");
}

fn generate_faber_value_helper(writer: &mut CodeWriter) {
    writer.writeln("#[derive(Debug, Clone, PartialEq)]");
    writer.writeln("enum FaberValue {");
    writer.indented(|writer| {
        writer.writeln("Nihil,");
        writer.writeln("Bivalens(bool),");
        writer.writeln("Numerus(i64),");
        writer.writeln("Fractus(f64),");
        writer.writeln("Textus(String),");
        writer.writeln("Lista(Vec<FaberValue>),");
        writer.writeln("Tabula(std::collections::HashMap<String, FaberValue>),");
    });
    writer.writeln("}");
    writer.newline();
    writer.writeln("impl Default for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn default() -> Self {");
        writer.indented(|writer| {
            writer.writeln("FaberValue::Nihil");
        });
        writer.writeln("}");
    });
    writer.writeln("}");
    writer.newline();
    writer.writeln("impl From<()> for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn from(_: ()) -> Self { FaberValue::Nihil }");
    });
    writer.writeln("}");
    writer.writeln("impl From<bool> for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: bool) -> Self { FaberValue::Bivalens(value) }");
    });
    writer.writeln("}");
    writer.writeln("impl From<i64> for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: i64) -> Self { FaberValue::Numerus(value) }");
    });
    writer.writeln("}");
    writer.writeln("impl From<f64> for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: f64) -> Self { FaberValue::Fractus(value) }");
    });
    writer.writeln("}");
    writer.writeln("impl From<String> for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: String) -> Self { FaberValue::Textus(value) }");
    });
    writer.writeln("}");
    writer.writeln("impl From<&str> for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: &str) -> Self { FaberValue::Textus(value.to_string()) }");
    });
    writer.writeln("}");
    writer.writeln("impl<T> From<Vec<T>> for FaberValue where T: Into<FaberValue> {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: Vec<T>) -> Self {");
        writer.indented(|writer| {
            writer.writeln("FaberValue::Lista(value.into_iter().map(Into::into).collect())");
        });
        writer.writeln("}");
    });
    writer.writeln("}");
    writer.writeln("impl<T> From<std::collections::HashMap<String, T>> for FaberValue where T: Into<FaberValue> {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: std::collections::HashMap<String, T>) -> Self {");
        writer.indented(|writer| {
            writer.writeln("FaberValue::Tabula(value.into_iter().map(|(key, value)| (key, value.into())).collect())");
        });
        writer.writeln("}");
    });
    writer.writeln("}");
}

pub(super) fn block_contains_await(block: &HirBlock) -> bool {
    struct AwaitFinder {
        found: bool,
    }

    impl HirVisitor for AwaitFinder {
        fn visit_expr(&mut self, expr: &HirExpr) {
            if self.found {
                return;
            }
            if matches!(expr.kind, HirExprKind::Cede(_)) {
                self.found = true;
                return;
            }
            walk_expr(self, expr);
        }
    }

    let mut finder = AwaitFinder { found: false };
    finder.visit_block(block);
    finder.found
}

pub(super) fn generate_block_on_helper(writer: &mut CodeWriter) {
    writer.writeln("fn __faber_block_on<F: std::future::Future>(future: F) -> F::Output {");
    writer.indented(|writer| {
        writer.writeln("tokio::runtime::Builder::new_current_thread()");
        writer.indented(|writer| {
            writer.writeln(".enable_all()");
            writer.writeln(".build()");
            writer.writeln(".expect(\"failed to build Faber async runtime\")");
            writer.writeln(".block_on(future)");
        });
    });
    writer.writeln("}");
}

pub(super) fn collect_hir_imports(codegen: &RustCodegen<'_>, hir: &HirProgram) -> BTreeSet<String> {
    let mut imports = BTreeSet::new();
    for item in &hir.items {
        let HirItemKind::Import(import) = &item.kind else {
            continue;
        };

        let path = normalize_import_path(codegen.resolve_symbol(import.path));
        if path.is_empty() {
            continue;
        }

        for import_item in &import.items {
            let name = codegen.resolve_symbol(import_item.name);
            if let Some(alias) = import_item.alias {
                let alias_name = codegen.resolve_symbol(alias);
                if alias_name == name {
                    if path == format!("crate::{alias_name}") {
                        continue;
                    }
                    imports.insert(format!("{path} as {alias_name}"));
                } else {
                    imports.insert(format!("{path}::{name} as {alias_name}"));
                }
            } else {
                imports.insert(format!("{path}::{name}"));
            }
        }
    }
    imports
}
