//! Generated Rust prelude, imports, and helper type emission.

use super::RustCodegen;
use crate::codegen::CodeWriter;
use crate::hir::visit::{walk_expr, HirVisitor};
use crate::hir::{HirBlock, HirExpr, HirExprKind, HirItemKind, HirProgram};
use std::collections::BTreeSet;

pub(super) fn generate_prelude(writer: &mut CodeWriter, imports: &BTreeSet<String>) {
    writer.writeln("// Generated by radix - do not edit");
    writer.newline();
    writer.writeln("#![allow(unused_imports)]");
    writer.writeln("#![allow(unused_variables)]");
    writer.writeln("#![allow(dead_code)]");
    writer.writeln("#![allow(non_snake_case)]");
    writer.newline();

    for import in imports {
        if matches!(import.as_str(), "__faber_value" | "__faber_ad") {
            continue;
        }
        writer.write("use ");
        writer.write(import);
        writer.writeln(";");
    }

    if !imports.is_empty() {
        writer.newline();
    }

    if imports.contains("__faber_value") {
        generate_faber_value_helper(writer);
        writer.newline();
    }
    if imports.contains("__faber_ad") {
        generate_faber_ad_helper(writer);
        writer.newline();
    }
}

fn normalize_import_path(path: &str) -> String {
    let canonical = path.replace("::", "/");
    if canonical.starts_with('@') {
        return String::new();
    }

    let mut segments = Vec::new();
    for segment in canonical.split('/') {
        if segment.is_empty() || segment == "." || segment == ".." {
            continue;
        }
        segments.push(segment);
    }

    if segments.is_empty() {
        return String::new();
    }

    if matches!(segments[0], "crate" | "self" | "super" | "std" | "core" | "alloc") {
        return segments.join("::");
    }

    format!("crate::{}", segments.join("::"))
}

/// Scan generated code for Rust types that require imports.
///
/// WHY: this backend keeps import emission at the generated-output boundary.
/// Explicit source imports are available from HIR, but helper types such as
/// `HashMap`, `HashSet`, and `Future` arise from Rust lowering decisions in
/// sub-emitters. Scanning the completed body keeps that target policy local
/// without threading an import accumulator through every expression path.
pub(super) fn collect_prelude_imports(code: &str) -> BTreeSet<String> {
    let mut imports = BTreeSet::new();
    if code.contains("HashMap<") {
        imports.insert("std::collections::HashMap".to_owned());
    }
    if code.contains("HashSet<") {
        imports.insert("std::collections::HashSet".to_owned());
    }
    if code.contains("Future<Output =") {
        imports.insert("std::future::Future".to_owned());
    }
    if code.contains("FaberValue") {
        imports.insert("__faber_value".to_owned());
    }
    if code.contains("__faber_ad::<") {
        imports.insert("__faber_ad".to_owned());
    }
    imports
}

fn generate_faber_ad_helper(writer: &mut CodeWriter) {
    writer.writeln("fn __faber_ad<T, A>(capability: &str, _args: A) -> Result<T, String> {");
    writer.indented(|writer| {
        writer.writeln("Err(format!(\"E_NO_ROUTE: unresolved capability {}\", capability))");
    });
    writer.writeln("}");
}

fn generate_faber_value_helper(writer: &mut CodeWriter) {
    writer.writeln("#[derive(Debug, Clone, PartialEq)]");
    writer.writeln("enum FaberValue {");
    writer.indented(|writer| {
        writer.writeln("Nihil,");
        writer.writeln("Bivalens(bool),");
        writer.writeln("Numerus(i64),");
        writer.writeln("Fractus(f64),");
        writer.writeln("Textus(String),");
        writer.writeln("Lista(Vec<FaberValue>),");
        writer.writeln("Tabula(std::collections::HashMap<String, FaberValue>),");
    });
    writer.writeln("}");
    writer.newline();
    writer.writeln("impl Default for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn default() -> Self {");
        writer.indented(|writer| {
            writer.writeln("FaberValue::Nihil");
        });
        writer.writeln("}");
    });
    writer.writeln("}");
    writer.newline();
    writer.writeln("impl From<()> for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn from(_: ()) -> Self { FaberValue::Nihil }");
    });
    writer.writeln("}");
    writer.writeln("impl From<bool> for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: bool) -> Self { FaberValue::Bivalens(value) }");
    });
    writer.writeln("}");
    writer.writeln("impl From<i64> for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: i64) -> Self { FaberValue::Numerus(value) }");
    });
    writer.writeln("}");
    writer.writeln("impl From<f64> for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: f64) -> Self { FaberValue::Fractus(value) }");
    });
    writer.writeln("}");
    writer.writeln("impl From<String> for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: String) -> Self { FaberValue::Textus(value) }");
    });
    writer.writeln("}");
    writer.writeln("impl From<&str> for FaberValue {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: &str) -> Self { FaberValue::Textus(value.to_string()) }");
    });
    writer.writeln("}");
    writer.writeln("impl<T> From<Vec<T>> for FaberValue where T: Into<FaberValue> {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: Vec<T>) -> Self {");
        writer.indented(|writer| {
            writer.writeln("FaberValue::Lista(value.into_iter().map(Into::into).collect())");
        });
        writer.writeln("}");
    });
    writer.writeln("}");
    writer.writeln("impl<T> From<std::collections::HashMap<String, T>> for FaberValue where T: Into<FaberValue> {");
    writer.indented(|writer| {
        writer.writeln("fn from(value: std::collections::HashMap<String, T>) -> Self {");
        writer.indented(|writer| {
            writer.writeln("FaberValue::Tabula(value.into_iter().map(|(key, value)| (key, value.into())).collect())");
        });
        writer.writeln("}");
    });
    writer.writeln("}");
}

pub(super) fn block_contains_await(block: &HirBlock) -> bool {
    struct AwaitFinder {
        found: bool,
    }

    impl HirVisitor for AwaitFinder {
        fn visit_expr(&mut self, expr: &HirExpr) {
            if self.found {
                return;
            }
            if matches!(expr.kind, HirExprKind::Cede(_)) {
                self.found = true;
                return;
            }
            walk_expr(self, expr);
        }
    }

    let mut finder = AwaitFinder { found: false };
    finder.visit_block(block);
    finder.found
}

pub(super) fn generate_block_on_helper(writer: &mut CodeWriter) {
    writer.writeln("fn __faber_block_on<F: std::future::Future>(future: F) -> F::Output {");
    writer.indented(|writer| {
        writer.writeln("fn raw_waker() -> std::task::RawWaker {");
        writer.indented(|writer| {
            writer.writeln("unsafe fn clone(_: *const ()) -> std::task::RawWaker { raw_waker() }");
            writer.writeln("unsafe fn wake(_: *const ()) {}");
            writer.writeln("unsafe fn wake_by_ref(_: *const ()) {}");
            writer.writeln("unsafe fn drop(_: *const ()) {}");
            writer.writeln("static VTABLE: std::task::RawWakerVTable = std::task::RawWakerVTable::new(clone, wake, wake_by_ref, drop);");
            writer.writeln("std::task::RawWaker::new(std::ptr::null(), &VTABLE)");
        });
        writer.writeln("}");
        writer.writeln("let waker = unsafe { std::task::Waker::from_raw(raw_waker()) };");
        writer.writeln("let mut context = std::task::Context::from_waker(&waker);");
        writer.writeln("let mut future = std::pin::pin!(future);");
        writer.writeln("loop {");
        writer.indented(|writer| {
            writer.writeln("match std::future::Future::poll(future.as_mut(), &mut context) {");
            writer.indented(|writer| {
                writer.writeln("std::task::Poll::Ready(value) => return value,");
                writer.writeln("std::task::Poll::Pending => std::thread::yield_now(),");
            });
            writer.writeln("}");
        });
        writer.writeln("}");
    });
    writer.writeln("}");
}

pub(super) fn collect_hir_imports(codegen: &RustCodegen<'_>, hir: &HirProgram) -> BTreeSet<String> {
    let mut imports = BTreeSet::new();
    for item in &hir.items {
        let HirItemKind::Import(import) = &item.kind else {
            continue;
        };

        let path = normalize_import_path(codegen.resolve_symbol(import.path));
        if path.is_empty() {
            continue;
        }

        for import_item in &import.items {
            let name = codegen.resolve_symbol(import_item.name);
            if let Some(alias) = import_item.alias {
                let alias_name = codegen.resolve_symbol(alias);
                if alias_name == name {
                    if path == format!("crate::{alias_name}") {
                        continue;
                    }
                    imports.insert(format!("{path} as {alias_name}"));
                } else {
                    imports.insert(format!("{path}::{name} as {alias_name}"));
                }
            } else {
                imports.insert(format!("{path}::{name}"));
            }
        }
    }
    imports
}
