name: CI

on:
    pull_request:
    workflow_dispatch:

jobs:
    radix:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - name: Format check
              run: cargo fmt --manifest-path radix/Cargo.toml --all -- --check
            - name: Test radix workspace
              run: cargo test --manifest-path radix/Cargo.toml
